import { sqliteTable, text, integer, real, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { bills } from './schema';

export const doctorCommissionRules = sqliteTable('doctor_commission_rules', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  doctorId: integer('doctor_id').notNull(),
  serviceType: text('service_type').notNull(), // 'lab_test', 'consultation_fee', 'referral'
  labTestId: integer('lab_test_id'),
  category: text('category'),
  incentiveType: text('incentive_type').notNull().default('performer'), // 'performer', 'prescriber', 'referrer'
  rateType: text('rate_type').notNull().default('percent'), // 'percent', 'flat'
  rateValue: integer('rate_value').notNull().default(0),
  waiverPolicy: text('waiver_policy').notNull().default('full_earned'),
  protectedRateBps: integer('protected_rate_bps').notNull().default(0),
  protectedFlatAmount: real('protected_flat_amount').notNull().default(0),
  canonicalSourceKey: text('canonical_source_key'),
  ruleVersion: integer('rule_version').notNull().default(1),
  effectiveFrom: text('effective_from').default(sql`CURRENT_DATE`),
  effectiveTo: text('effective_to'),
  isActive: integer('is_active').notNull().default(1),
  notes: text('notes'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at').default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  index('idx_doctor_comm_rules_tenant_doctor').on(table.tenantId, table.doctorId, table.serviceType, table.isActive),
  index('idx_doctor_comm_rules_test').on(table.tenantId, table.labTestId, table.isActive),
  uniqueIndex('uq_doctor_commission_rules_canonical_source_key')
    .on(table.tenantId, table.canonicalSourceKey)
    .where(sql`${table.canonicalSourceKey} IS NOT NULL`),
  check('doctor_comm_rules_service_type_check', sql`service_type IN ('lab_test','consultation_fee','referral','procedure','ipd_round')`),
  check('doctor_comm_rules_rate_type_check', sql`rate_type IN ('percent','flat')`),
  check('doctor_comm_rules_incentive_type_check', sql`incentive_type IN ('performer','prescriber','referrer')`),
  check('doctor_comm_rules_version_check', sql`rule_version > 0`),
]);

export const diagnosticPerformerPayoutRules = sqliteTable('diagnostic_performer_payout_rules', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  billingServiceItemId: integer('billing_service_item_id').notNull(),
  diagnosticKind: text('diagnostic_kind').notNull(),
  rateType: text('rate_type').notNull(),
  rateValue: real('rate_value').notNull().default(0),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  isActive: integer('is_active').notNull().default(1),
  notes: text('notes'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  index('idx_diag_performer_rules_lookup').on(
    table.tenantId,
    table.billingServiceItemId,
    table.isActive,
    table.effectiveFrom,
    table.effectiveTo,
  ),
  index('idx_diag_performer_rules_kind').on(table.tenantId, table.diagnosticKind, table.isActive),
  check('diag_performer_rules_kind_check', sql`diagnostic_kind IN ('lab','radiology')`),
  check('diag_performer_rules_rate_type_check', sql`rate_type IN ('flat','percent')`),
  check('diag_performer_rules_rate_value_check', sql`rate_value >= 0`),
  check('diag_performer_rules_percent_check', sql`rate_type != 'percent' OR rate_value <= 10000`),
  check('diag_performer_rules_active_check', sql`is_active IN (0,1)`),
  check('diag_performer_rules_date_check', sql`effective_to IS NULL OR date(effective_to) >= date(effective_from)`),
]);

export const diagnosticPerformerReserves = sqliteTable('diagnostic_performer_reserves', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  ruleId: integer('rule_id').notNull(),
  billId: integer('bill_id').notNull(),
  invoiceItemId: integer('invoice_item_id').notNull(),
  patientId: integer('patient_id'),
  visitId: integer('visit_id'),
  billingServiceItemId: integer('billing_service_item_id').notNull(),
  diagnosticKind: text('diagnostic_kind').notNull(),
  labTestId: integer('lab_test_id'),
  radiologyImagingItemId: integer('radiology_imaging_item_id'),
  testCode: text('test_code'),
  testName: text('test_name').notNull(),
  unitSequence: integer('unit_sequence').notNull(),
  unitServiceAmount: real('unit_service_amount').notNull(),
  unitDiscountAmount: real('unit_discount_amount').notNull().default(0),
  netUnitServiceAmount: real('net_unit_service_amount').notNull(),
  ruleRateType: text('rule_rate_type').notNull(),
  ruleRateValue: real('rule_rate_value').notNull(),
  reservedAmount: real('reserved_amount').notNull(),
  status: text('status').notNull().default('reserved'),
  assignedDoctorId: integer('assigned_doctor_id'),
  commissionAccrualId: integer('commission_accrual_id'),
  settlementId: integer('settlement_id'),
  canonicalSourceKey: text('canonical_source_key'),
  reservedAt: text('reserved_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
  paidAt: text('paid_at'),
  cancelledAt: text('cancelled_at'),
  cancelledBy: integer('cancelled_by'),
  reversedAt: text('reversed_at'),
  reversedBy: integer('reversed_by'),
  cancelReason: text('cancel_reason'),
  createdBy: integer('created_by'),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  uniqueIndex('uq_diag_performer_reserve_unit').on(table.tenantId, table.invoiceItemId, table.unitSequence),
  uniqueIndex('uq_diag_performer_reserve_accrual')
    .on(table.tenantId, table.commissionAccrualId)
    .where(sql`commission_accrual_id IS NOT NULL`),
  uniqueIndex('uq_diagnostic_performer_reserve_canonical_source_key')
    .on(table.tenantId, table.canonicalSourceKey)
    .where(sql`canonical_source_key IS NOT NULL`),
  index('idx_diag_performer_reserves_status').on(table.tenantId, table.status, table.reservedAt),
  index('idx_diag_performer_reserves_service').on(table.tenantId, table.billingServiceItemId, table.status, table.reservedAt),
  index('idx_diag_performer_reserves_bill').on(table.tenantId, table.billId, table.invoiceItemId),
  index('idx_diag_performer_reserves_settlement').on(table.tenantId, table.settlementId),
  check('diag_performer_reserves_kind_check', sql`diagnostic_kind IN ('lab','radiology')`),
  check('diag_performer_reserves_rate_type_check', sql`rule_rate_type IN ('flat','percent')`),
  check('diag_performer_reserves_status_check', sql`status IN ('reserved','paid','cancelled','reversed')`),
  check('diag_performer_reserves_unit_sequence_check', sql`unit_sequence > 0`),
  check('diag_performer_reserves_amounts_check', sql`unit_service_amount >= 0 AND unit_discount_amount >= 0 AND net_unit_service_amount >= 0 AND rule_rate_value >= 0 AND reserved_amount >= 0`),
]);

export const doctorCommissionAccruals = sqliteTable('doctor_commission_accruals', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  doctorId: integer('doctor_id').notNull(),
  patientId: integer('patient_id'),
  visitId: integer('visit_id'),
  billId: integer('bill_id'),
  labOrderId: integer('lab_order_id'),
  labOrderItemId: integer('lab_order_item_id'),
  labTestId: integer('lab_test_id'),
  settlementId: integer('settlement_id'),
  canonicalSourceKey: text('canonical_source_key'),
  sourceType: text('source_type').notNull(), // 'lab_test', 'consultation_fee', 'referral'
  incentiveType: text('incentive_type').notNull().default('performer'), // 'performer', 'prescriber', 'referrer'
  grossAmount: integer('gross_amount').notNull().default(0),
  commissionBaseAmount: real('commission_base_amount').notNull().default(0),
  performerReserveAmount: real('performer_reserve_amount').notNull().default(0),
  performerReserveId: integer('performer_reserve_id'),
  commissionRuleId: integer('commission_rule_id'),
  commissionRuleVersionSnapshot: integer('commission_rule_version_snapshot'),
  commissionReasonCode: text('commission_reason_code'),
  commissionRateBps: integer('commission_rate_bps').notNull().default(0),
  commissionFlatAmount: integer('commission_flat_amount').notNull().default(0),
  commissionAmount: integer('commission_amount').notNull().default(0),
  earnedCommissionAmount: real('earned_commission_amount').notNull().default(0),
  waiverPolicySnapshot: text('waiver_policy_snapshot').notNull().default('full_earned'),
  protectedRateBpsSnapshot: integer('protected_rate_bps_snapshot').notNull().default(0),
  protectedFlatAmountSnapshot: real('protected_flat_amount_snapshot').notNull().default(0),
  protectedCommissionAmount: real('protected_commission_amount').notNull().default(0),
  maximumWaiverAmount: real('maximum_waiver_amount').notNull().default(0),
  requestedWaiverAmount: real('requested_waiver_amount').notNull().default(0),
  hospitalFundedOverflowAmount: real('hospital_funded_overflow_amount').notNull().default(0),
  doctorWaiverAmount: real('doctor_waiver_amount').notNull().default(0),
  payableCommissionAmount: real('payable_commission_amount').notNull().default(0),
  paidAmount: real('paid_amount').notNull().default(0),
  balanceAmount: real('balance_amount').notNull().default(0),
  waiverReason: text('waiver_reason'),
  waiverAllocationId: integer('waiver_allocation_id'),
  status: text('status').notNull().default('accrued'), // 'accrued', 'approved', 'paid', 'cancelled'
  accruedDate: text('accrued_date').default(sql`CURRENT_DATE`),
  paidDate: text('paid_date'),
  notes: text('notes'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at').default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  index('idx_doctor_comm_accruals_tenant_status').on(table.tenantId, table.status, table.accruedDate),
  index('idx_doctor_comm_accruals_doctor').on(table.tenantId, table.doctorId, table.accruedDate),
  index('idx_doctor_comm_accruals_bill').on(table.tenantId, table.billId),
  index('idx_dr_comm_accruals_settlement').on(table.tenantId, table.settlementId),
  uniqueIndex('uq_doctor_commission_accrual_canonical_source_key')
    .on(table.tenantId, table.canonicalSourceKey)
    .where(sql`canonical_source_key IS NOT NULL`),
  uniqueIndex('uq_doctor_commission_accrual_performer_reserve')
    .on(table.tenantId, table.performerReserveId)
    .where(sql`performer_reserve_id IS NOT NULL`),
  check('doctor_comm_accruals_source_type_check', sql`source_type IN ('lab_test','consultation_fee','referral','procedure','ipd_round')`),
  check('doctor_comm_accruals_status_check', sql`status IN ('accrued','approved','paid','cancelled')`),
  check('doctor_comm_accruals_incentive_type_check', sql`incentive_type IN ('performer','prescriber','referrer')`),
  check('doctor_comm_accruals_rule_version_snapshot_check', sql`commission_rule_version_snapshot IS NULL OR commission_rule_version_snapshot > 0`),
  check('doctor_comm_accruals_reason_code_check', sql`commission_reason_code IS NULL OR commission_reason_code IN ('rule_matched','no_matching_rule','doctor_missing','bill_unpaid','cancelled','refunded','eligible_base_zero','doctor_waived','manual_adjustment','reversal','held_for_review')`),
]);

export const doctorCommissionSettlements = sqliteTable('doctor_commission_settlements', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  doctorId: integer('doctor_id').notNull(),
  settlementDate: text('settlement_date').default(sql`CURRENT_DATE`),
  totalAmount: real('total_amount').notNull().default(0),
  paymentMode: text('payment_mode').notNull().default('cash'),
  referenceNo: text('reference_no'),
  settlementNo: text('settlement_no'),
  grossCommissionAmount: real('gross_commission_amount').notNull().default(0),
  advanceDeduction: real('advance_deduction').notNull().default(0),
  otherAdjustment: real('other_adjustment').notNull().default(0),
  roundingAdjustment: real('rounding_adjustment').notNull().default(0),
  netPaidAmount: real('net_paid_amount').notNull().default(0),
  receiverType: text('receiver_type').notNull().default('doctor'),
  receiverName: text('receiver_name'),
  receiverReference: text('receiver_reference'),
  paymentMethod: text('payment_method').notNull().default('cash'),
  counterSessionId: integer('counter_session_id'),
  counterId: integer('counter_id'),
  cashMovementId: integer('cash_movement_id'),
  attachmentKey: text('attachment_key'),
  idempotencyKey: text('idempotency_key'),
  accountingVoucherId: integer('accounting_voucher_id'),
  reversedAt: text('reversed_at'),
  reversedBy: integer('reversed_by'),
  reversalReason: text('reversal_reason'),
  reversalVoucherId: integer('reversal_voucher_id'),
  notes: text('notes'),
  voucherId: integer('voucher_id'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  index('idx_dr_comm_settlements_tenant_doctor').on(table.tenantId, table.doctorId, table.settlementDate),
  uniqueIndex('idx_doctor_commission_settlements_no').on(table.tenantId, table.settlementNo),
  uniqueIndex('idx_doctor_commission_settlements_idempotency').on(table.tenantId, table.idempotencyKey),
  index('idx_doctor_commission_settlements_accounting_voucher').on(table.tenantId, table.accountingVoucherId),
  index('idx_doctor_commission_settlements_reversal').on(table.tenantId, table.reversedAt),
  check('doctor_comm_settlements_payment_mode_check', sql`payment_mode IN ('cash','bank','cheque','card','mobile_banking','other')`),
  check('doctor_comm_settlements_receiver_type_check', sql`receiver_type IN ('doctor','assistant','representative')`),
  check('doctor_comm_settlements_payment_method_check', sql`payment_method IN ('cash','bank','mobile_banking')`),
]);

export const doctorCommissionAdjustments = sqliteTable('doctor_commission_adjustments', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  doctorId: integer('doctor_id').notNull(),
  accrualId: integer('accrual_id').notNull(),
  creditNoteId: integer('credit_note_id').notNull(),
  creditNoteItemId: integer('credit_note_item_id'),
  billId: integer('bill_id').notNull(),
  billItemId: integer('bill_item_id').notNull(),
  adjustmentType: text('adjustment_type').notNull(),
  amount: real('amount').notNull(),
  returnedQuantity: real('returned_quantity').notNull().default(0),
  originalQuantity: real('original_quantity').notNull().default(1),
  returnRatio: real('return_ratio').notNull().default(0),
  status: text('status').notNull().default('recorded'),
  settlementId: integer('settlement_id'),
  reason: text('reason'),
  metadataJson: text('metadata_json'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  uniqueIndex('uq_doctor_commission_adjustments_credit_accrual_type')
    .on(table.tenantId, table.creditNoteId, table.accrualId, table.adjustmentType),
  index('idx_doctor_commission_adjustments_doctor_status')
    .on(table.tenantId, table.doctorId, table.status, table.createdAt),
  index('idx_doctor_commission_adjustments_credit_note')
    .on(table.tenantId, table.creditNoteId, table.billItemId),
  check('doctor_commission_adjustment_type_check', sql`adjustment_type IN ('reversal','clawback')`),
  check('doctor_commission_adjustment_amount_check', sql`amount >= 0`),
  check('doctor_commission_adjustment_status_check', sql`status IN ('recorded','outstanding','applied','settled','cancelled')`),
]);

export const doctorCommissionAdjustmentApplications = sqliteTable('doctor_commission_adjustment_applications', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  adjustmentId: integer('adjustment_id').notNull(),
  settlementId: integer('settlement_id').notNull(),
  amount: real('amount').notNull(),
  createdBy: integer('created_by'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  uniqueIndex('uq_doctor_commission_adjustment_applications_adjustment_settlement')
    .on(table.tenantId, table.adjustmentId, table.settlementId),
  index('idx_doctor_commission_adjustment_applications_adjustment')
    .on(table.tenantId, table.adjustmentId, table.createdAt),
  index('idx_doctor_commission_adjustment_applications_settlement')
    .on(table.tenantId, table.settlementId, table.createdAt),
  check('doctor_commission_adjustment_application_amount_check', sql`amount > 0`),
]);

export const doctorCommissionSettlementItems = sqliteTable('doctor_commission_settlement_items', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  settlementId: integer('settlement_id').notNull().references(() => doctorCommissionSettlements.id, { onDelete: 'cascade' }),
  accrualId: integer('accrual_id').notNull().references(() => doctorCommissionAccruals.id, { onDelete: 'restrict' }),
  doctorId: integer('doctor_id').notNull(),
  sourceType: text('source_type').notNull(),
  invoiceId: integer('invoice_id'),
  billId: integer('bill_id'),
  patientId: integer('patient_id'),
  serviceDate: text('service_date'),
  grossAmount: real('gross_amount').notNull().default(0),
  commissionAmount: real('commission_amount').notNull().default(0),
  calculatedCommissionAmount: real('calculated_commission_amount'),
  overrideAmount: real('override_amount'),
  overrideReason: text('override_reason'),
  overriddenBy: integer('overridden_by'),
  overriddenAt: text('overridden_at'),
  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  uniqueIndex('idx_doctor_commission_settlement_items_accrual').on(table.tenantId, table.accrualId),
  index('idx_doctor_commission_settlement_items_settlement').on(table.tenantId, table.settlementId),
  index('idx_doctor_commission_settlement_items_doctor_date').on(table.tenantId, table.doctorId, table.serviceDate),
]);

export const billDiscountAllocations = sqliteTable('bill_discount_allocations', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  billId: integer('bill_id').notNull(),
  billItemId: integer('bill_item_id'),
  settlementId: integer('settlement_id'),
  allocationType: text('allocation_type').notNull(),
  discountReason: text('discount_reason').notNull().default('normal_hospital_discount'),
  doctorId: integer('doctor_id'),
  amount: real('amount').notNull().default(0),
  percent: real('percent'),
  referenceName: text('reference_name'),
  approvalStatus: text('approval_status').notNull().default('recorded'),
  approvedBy: integer('approved_by'),
  note: text('note'),
  metadataJson: text('metadata_json'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  index('idx_bill_discount_allocations_bill').on(table.tenantId, table.billId),
  index('idx_bill_discount_allocations_settlement').on(table.tenantId, table.settlementId),
  index('idx_bill_discount_allocations_doctor').on(table.tenantId, table.doctorId, table.createdAt),
  index('idx_bill_discount_allocations_type_date').on(table.tenantId, table.allocationType, table.createdAt),
]);

export const fractionPercents = sqliteTable('fraction_percents', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  serviceItemId: integer('service_item_id'),
  billItemCategory: text('bill_item_category'),
  hospitalPercent: real('hospital_percent').notNull().default(60),
  doctorPercent: real('doctor_percent').notNull().default(40),
  isActive: integer('is_active').notNull().default(1),
  createdBy: integer('created_by'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at'),
}, (table) => [
  index('idx_fraction_percents_tenant').on(table.tenantId),
]);

export const fractionCalculations = sqliteTable('fraction_calculations', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  billId: integer('bill_id').notNull().references(() => bills.id),
  invoiceItemId: integer('invoice_item_id'),
  doctorId: integer('doctor_id').notNull(),
  grossAmount: real('gross_amount').notNull(),
  hospitalAmount: real('hospital_amount').notNull(),
  doctorAmount: real('doctor_amount').notNull(),
  fractionPercentId: integer('fraction_percent_id').references(() => fractionPercents.id),
  status: text('status').notNull().default('calculated'),
  settledDate: text('settled_date'),
  settlementId: integer('settlement_id'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at'),
}, (table) => [
  index('idx_fraction_calc_bill').on(table.tenantId, table.billId),
  index('idx_fraction_calc_doctor').on(table.tenantId, table.doctorId),
  index('idx_fraction_calc_status').on(table.tenantId, table.status),
]);

export const bankDepositRequests = sqliteTable('bank_deposit_requests', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  requestNo: text('request_no').notNull(),
  counterSessionId: integer('counter_session_id').notNull(),
  counterId: integer('counter_id').notNull(),
  requestedBy: integer('requested_by').notNull(),
  requestedAmount: real('requested_amount').notNull(),
  proposedBankName: text('proposed_bank_name'),
  requestNote: text('request_note'),
  status: text('status').notNull().default('pending'),
  idempotencyKey: text('idempotency_key').notNull(),
  cashMovementId: integer('cash_movement_id'),
  bankTransactionId: integer('bank_transaction_id'),
  confirmedBankName: text('confirmed_bank_name'),
  confirmedReferenceNo: text('confirmed_reference_no'),
  confirmedDate: text('confirmed_date'),
  confirmedBy: integer('confirmed_by'),
  confirmedAt: text('confirmed_at'),
  rejectionReason: text('rejection_reason'),
  rejectedBy: integer('rejected_by'),
  rejectedAt: text('rejected_at'),
  resolutionType: text('resolution_type'),
  resolutionNote: text('resolution_note'),
  resolvedBy: integer('resolved_by'),
  resolvedAt: text('resolved_at'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
  updatedAt: text('updated_at'),
}, (table) => [
  uniqueIndex('idx_bank_deposit_requests_no').on(table.tenantId, table.requestNo),
  uniqueIndex('idx_bank_deposit_requests_idempotency').on(table.tenantId, table.idempotencyKey),
  index('idx_bank_deposit_requests_status').on(table.tenantId, table.status, table.createdAt),
  index('idx_bank_deposit_requests_session').on(table.tenantId, table.counterSessionId),
  index('idx_bank_deposit_requests_requester').on(table.tenantId, table.requestedBy, table.createdAt),
  check('bank_deposit_requests_amount_check', sql`requested_amount > 0`),
  check('bank_deposit_requests_status_check', sql`status IN ('pending','approved','rejected','resolved')`),
  check('bank_deposit_requests_resolution_check', sql`resolution_type IS NULL OR resolution_type IN ('deposited','returned_to_counter','manual_adjustment')`),
]);

export const bankTransactions = sqliteTable('bank_transactions', {
  id: integer().primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  type: text('type').notNull(),
  amount: real('amount').notNull().default(0),
  bankName: text('bank_name'),
  referenceNo: text('reference_no'),
  description: text('description'),
  date: text('date').notNull(),
  bankDepositRequestId: integer('bank_deposit_request_id'),
  createdBy: integer('created_by'),
  createdAt: text('created_at').default(sql`(datetime('now', '+6 hours'))`),
}, (table) => [
  index('idx_bank_transactions_tenant_date').on(table.tenantId, table.date),
  index('idx_bank_transactions_tenant_type_date').on(table.tenantId, table.type, table.date),
  uniqueIndex('idx_bank_transactions_deposit_request').on(table.tenantId, table.bankDepositRequestId),
  check('bank_transactions_type_check', sql`type IN ('deposit','card_settlement','supplier_payment','other')`),
]);
