export const queryKeys = {
  doctors: {
    all: ['doctors'] as const,
    dashboard: () => ['doctors', 'dashboard'] as const,
    ipdRounds: (date?: string) => ['doctors', 'ipdRounds', date ?? 'today'] as const,
    list: () => ['doctors', 'list'] as const,
    detail: (id: number) => ['doctors', 'detail', id] as const,
  },
  invitations: {
    all: ['invitations'] as const,
    list: (filters?: Record<string, unknown>) => ['invitations', 'list', filters ?? {}] as const,
    forDoctor: (doctorId: number) => ['invitations', 'forDoctor', doctorId] as const,
  },
  appointments: {
    all: ['appointments'] as const,
    today: (date?: string) => ['appointments', 'today', date] as const,
    list: (filters: Record<string, unknown>) => ['appointments', 'list', filters] as const,
    detail: (id: number) => ['appointments', 'detail', id] as const,
  },
  approvals: {
    all: ['approvals'] as const,
    list: (type?: string, status?: string) => ['approvals', 'list', type, status] as const,
    counts: () => ['approvals', 'counts'] as const,
    summary: () => ['approvals', 'summary'] as const,
  },
  actionCenter: {
    summary: () => ['action-center', 'summary'] as const,
    exceptions: {
      all: ['action-center', 'exceptions'] as const,
      list: (filters: Record<string, unknown>) => ['action-center', 'exceptions', 'list', filters] as const,
      detail: (id: number) => ['action-center', 'exceptions', 'detail', id] as const,
      events: (id: number) => ['action-center', 'exceptions', 'events', id] as const,
    },
    collections: {
      all: ['action-center', 'collections'] as const,
      list: (filters: Record<string, unknown>) => ['action-center', 'collections', 'list', filters] as const,
      detail: (sourceKey: string) => ['action-center', 'collections', 'detail', sourceKey] as const,
      events: (sourceKey: string) => ['action-center', 'collections', 'events', sourceKey] as const,
    },
    tasks: {
      all: ['action-center', 'tasks'] as const,
      list: (filters: Record<string, unknown>) => ['action-center', 'tasks', 'list', filters] as const,
      detail: (id: number) => ['action-center', 'tasks', 'detail', id] as const,
      events: (id: number) => ['action-center', 'tasks', 'events', id] as const,
    },
  },
  billing: {
    all: ['billing'] as const,
    list: (filters: Record<string, unknown>) => ['billing', 'list', filters] as const,
    dues: () => ['billing', 'dues'] as const,
    detail: (id: number) => ['billing', 'detail', id] as const,
    invoiceInspector: (id: number) => ['billing', 'invoiceInspector', id] as const,
    pending: (admissionId: string | number) => ['billing', 'pending', admissionId] as const,
    billVersions: (billId: number) => ['billing', 'billVersions', billId] as const,
  },
  ipdDoctorRounds: {
    all: ['ipdDoctorRounds'] as const,
    list: (admissionId: number) => ['ipdDoctorRounds', admissionId] as const,
  },
  patients: {
    all: ['patients'] as const,
    list: (filters: Record<string, unknown>) => ['patients', 'list', filters] as const,
    detail: (id: number) => ['patients', 'detail', id] as const,
    summary: (id: number) => ['patients', 'summary', id] as const,
  },
  laboratory: {
    all: ['laboratory'] as const,
    tests: () => ['laboratory', 'tests'] as const,
    list: (filters?: Record<string, unknown>) => ['laboratory', 'list', filters] as const,
    detail: (id: number) => ['laboratory', 'detail', id] as const,
    workflowDashboard: (department?: string) => ['laboratory', 'workflow-dashboard', department ?? 'all'] as const,
    worklist: (stage: string, filters?: Record<string, unknown>) => ['laboratory', 'worklist', stage, filters] as const,
    departments: () => ['laboratory', 'departments'] as const,
    testComponents: (testId: number) => ['laboratory', 'test-components', testId] as const,
  },
  pharmacy: {
    all: ['pharmacy'] as const,
    summary: () => ['pharmacy', 'summary'] as const,
    lowStock: () => ['pharmacy', 'lowStock'] as const,
    expiring: () => ['pharmacy', 'expiring'] as const,
    medicines: (filters?: Record<string, unknown>) => ['pharmacy', 'medicines', filters] as const,
    detail: (id: number) => ['pharmacy', 'detail', id] as const,
    invoices: (filters?: Record<string, unknown>) => ['pharmacy', 'invoices', filters] as const,
    purchaseOrders: (filters?: Record<string, unknown>) => ['pharmacy', 'purchaseOrders', filters] as const,
    goodsReceipts: () => ['pharmacy', 'goodsReceipts'] as const,
    dispatches: () => ['pharmacy', 'dispatches'] as const,
    prescriptionQueue: (filters?: Record<string, unknown>) => ['pharmacy', 'prescriptionQueue', filters] as const,
    items: (search?: string) => ['pharmacy', 'items', search] as const,
    categories: () => ['pharmacy', 'categories'] as const,
    generics: () => ['pharmacy', 'generics'] as const,
    uom: () => ['pharmacy', 'uom'] as const,
    packingTypes: () => ['pharmacy', 'packingTypes'] as const,
    suppliers: () => ['pharmacy', 'suppliers'] as const,
    stock: () => ['pharmacy', 'stock'] as const,
    invoiceReceipt: (id: string) => ['pharmacy', 'invoiceReceipt', id] as const,
    salesReport: (filters?: Record<string, string>) => ['pharmacy', 'salesReport', filters] as const,
    stockReport: (filters?: Record<string, string>) => ['pharmacy', 'stockReport', filters] as const,
    expiryReport: (filters?: Record<string, string>) => ['pharmacy', 'expiryReport', filters] as const,
    pendingGrnApprovals: () => ['pharmacy', 'pendingGrnApprovals'] as const,
    pendingWriteOffApprovals: () => ['pharmacy', 'pendingWriteOffApprovals'] as const,
    pendingPurchaseOrders: () => ['pharmacy', 'pendingPurchaseOrders'] as const,
    deposits: () => ['pharmacy', 'deposits'] as const,
    settlements: () => ['pharmacy', 'settlements'] as const,
    writeOffs: () => ['pharmacy', 'writeOffs'] as const,
    returns: (filters?: Record<string, unknown>) => ['pharmacy', 'returns', filters] as const,
    narcotics: () => ['pharmacy', 'narcotics'] as const,
    dosageTemplates: () => ['pharmacy', 'dosageTemplates'] as const,
    taxConfig: () => ['pharmacy', 'taxConfig'] as const,
    patientBillingSummary: (patientId: number) => ['pharmacy', 'patientBillingSummary', patientId] as const,
    patientBillHistory: (patientId: number, page: number) => ['pharmacy', 'patientBillHistory', patientId, page] as const,
    patientProvisional: (patientId: number) => ['pharmacy', 'patientProvisional', patientId] as const,
    patientDeposits: (patientId: number) => ['pharmacy', 'patientDeposits', patientId] as const,
    supplierLedger: (supplierId: string, filters?: Record<string, string>) => ['pharmacy', 'supplierLedger', supplierId, filters] as const,
    dispensaryStock: (filters?: Record<string, unknown>) => ['pharmacy', 'dispensaryStock', filters] as const,
    itemPriceHistory: (itemId: string) => ['pharmacy', 'itemPriceHistory', itemId] as const,
  },
  nursing: {
    all: ['nursing'] as const,
    patients: (filters?: Record<string, unknown>) => ['nursing', 'patients', filters] as const,
    records: (tab: string, patientId?: number) => ['nursing', 'records', tab, patientId] as const,
    opd: () => ['nursing', 'opd'] as const,
    wards: () => ['nursing', 'wards'] as const,
    favourites: () => ['nursing', 'favourites'] as const,
    clinicalSummary: (patientId: number) => ['nursing', 'clinicalSummary', patientId] as const,
    medicationDue: (filters?: Record<string, unknown>) => ['nursing', 'medicationDue', filters] as const,
    marSchedule: (patientId: number | 'all', date?: string) => ['nursing', 'marSchedule', patientId, date] as const,
    medicationOrders: (patientId: number) => ['nursing', 'medicationOrders', patientId] as const,
    activityLog: (patientId: number) => ['nursing', 'activity-log', patientId] as const,
    ivDrugs: (patientId: number) => ['nursing', 'iv-drugs', patientId] as const,
    investigationResults: (patientId: number) => ['nursing', 'investigation-results', patientId] as const,
    notes: (patientId: number) => ['nursing', 'notes', patientId] as const,
    io: (patientId: number) => ['nursing', 'io', patientId] as const,
    carePlan: (patientId: number) => ['nursing', 'care-plan', patientId] as const,
    diet: (patientId: number) => ['nursing', 'diet', patientId] as const,
    dietTypes: () => ['nursing', 'diet-types'] as const,
    assignments: (filters?: Record<string, string>) => ['nursing', 'assignments', filters] as const,
    workloadStats: () => ['nursing', 'assignments', 'stats'] as const,
    nursingReports: (filters?: Record<string, string>) => ['nursing', 'reports', filters] as const,
  },
  nurseStation: {
    all: ['nurseStation'] as const,
    dashboard: () => ['nurseStation', 'dashboard'] as const,
    vitals: () => ['nurseStation', 'vitals'] as const,
    vitalsTrends: (patientId: number) => ['nurseStation', 'vitalsTrends', patientId] as const,
    respiratory: (patientId: number) => ['nurseStation', 'respiratory', patientId] as const,
  },
  reception: {
    all: ['reception'] as const,
    dashboard: () => ['reception', 'dashboard'] as const,
    visits: (date: string) => ['reception', 'visits', date] as const,
    visitServices: (visitId: number) => ['reception', 'visitServices', visitId] as const,
    services: (search?: string, dept?: string) => ['reception', 'services', search, dept] as const,
    dailyReport: (date: string, staffId?: string) => ['reception', 'dailyReport', date, staffId] as const,
  },
  cashOperations: {
    overview: (filters?: Record<string, unknown>) => filters ? ['cashOperations', 'overview', filters] as const : ['cashOperations', 'overview'] as const,
    activity: (filters?: Record<string, unknown>) => ['cashOperations', 'activity', filters] as const,
    settings: () => ['cashOperations', 'settings'] as const,
  },
  emergency: {
    all: ['emergency'] as const,
    patients: (filters?: Record<string, unknown>) => ['emergency', 'patients', filters] as const,
    stats: () => ['emergency', 'stats'] as const,
  },
  radiology: {
    all: ['radiology'] as const,
    requisitions: (filters?: Record<string, unknown>) => ['radiology', 'requisitions', filters] as const,
    reports: (filters?: Record<string, unknown>) => ['radiology', 'reports', filters] as const,
    stats: () => ['radiology', 'stats'] as const,
    types: () => ['radiology', 'types'] as const,
    items: () => ['radiology', 'items'] as const,
    dicom: () => ['radiology', 'dicom'] as const,
  },
  admissions: {
    all: ['admissions'] as const,
    list: (filters: Record<string, unknown>) => ['admissions', 'list', filters] as const,
    stats: () => ['admissions', 'stats'] as const,
    beds: (filters?: Record<string, unknown>) => ['admissions', 'beds', filters] as const,
  },
  queue: {
    all: ['queue'] as const,
    overview: (filters: Record<string, string>) => ['queue', 'overview', filters] as const,
    display: () => ['queue', 'display'] as const,
    tokens: (filters: Record<string, string>) => ['queue', 'tokens', filters] as const,
    stats: () => ['queue', 'stats'] as const,
    departments: () => ['queue', 'departments'] as const,
    patientSearch: (term: string) => ['queue', 'patientSearch', term] as const,
  },
  tokenReservations: {
    all: ['tokenReservations'] as const,
    list: (filters: Record<string, string>) => ['tokenReservations', 'list', filters] as const,
    ranges: (filters: Record<string, string>) => ['tokenReservations', 'ranges', filters] as const,
    available: (filters: Record<string, string>) => ['tokenReservations', 'available', filters] as const,
  },
  inventory: {
    all: ['inventory'] as const,
    dashboard: () => ['inventory', 'dashboard'] as const,
    lowStock: () => ['inventory', 'lowStock'] as const,
    recentRequisitions: () => ['inventory', 'recentRequisitions'] as const,
    itemsCount: () => ['inventory', 'itemsCount'] as const,
    pendingPOCount: () => ['inventory', 'pendingPOCount'] as const,
    stock: (filters?: Record<string, unknown>) => ['inventory', 'stock', filters] as const,
    requisitions: (filters?: Record<string, unknown>) => ['inventory', 'requisitions', filters] as const,
    purchaseOrders: (filters?: Record<string, unknown>) => ['inventory', 'purchaseOrders', filters] as const,
    goodsReceipts: (filters?: Record<string, unknown>) => ['inventory', 'goodsReceipts', filters] as const,
    dispatches: (filters?: Record<string, unknown>) => ['inventory', 'dispatches', filters] as const,
    items: () => ['inventory', 'items'] as const,
    vendors: () => ['inventory', 'vendors'] as const,
    stores: () => ['inventory', 'stores'] as const,
    stockAdjustments: () => ['inventory', 'stockAdjustments'] as const,
    valuation: () => ['inventory', 'valuation'] as const,
    accountingSummary: () => ['inventory', 'accountingSummary'] as const,
    accountingTransactions: (days: number) => ['inventory', 'accountingTransactions', days] as const,
  },
  consultations: {
    all: ['consultations'] as const,
    list: (filters?: Record<string, unknown>) => ['consultations', 'list', filters] as const,
    detail: (id: number) => ['consultations', 'detail', id] as const,
  },
  discharge: {
    all: ['discharge'] as const,
    detail: (admissionId: string) => ['discharge', 'detail', admissionId] as const,
  },
  ot: {
    all: ['ot'] as const,
    bookings: (filters?: Record<string, unknown>) => ['ot', 'bookings', filters] as const,
    stats: () => ['ot', 'stats'] as const,
    rooms: () => ['ot', 'rooms'] as const,
    overview: (patientId: number) => ['ot', 'overview', patientId] as const,
    clearance: (bookingId: number) => ['ot', 'clearance', bookingId] as const,
    consents: (bookingId: number) => ['ot', 'consents', bookingId] as const,
    vitals: (bookingId: number) => ['ot', 'vitals', bookingId] as const,
    inventory: (bookingId: number) => ['ot', 'inventory', bookingId] as const,
    bill: (bookingId: number) => ['ot', 'bill', bookingId] as const,
    recovery: (bookingId: number) => ['ot', 'recovery', bookingId] as const,
    audit: (bookingId: number) => ['ot', 'audit', bookingId] as const,
    safetyChecklist: (bookingId: number) => ['ot', 'safetyChecklist', bookingId] as const,
    anesthesia: (bookingId: number) => ['ot', 'anesthesia', bookingId] as const,
    commissionRules: () => ['ot', 'commissionRules'] as const,
    commissions: (bookingId: number) => ['ot', 'commissions', bookingId] as const,
    settings: () => ['ot', 'settings'] as const,
  },
  carePlans: {
    all: ['carePlans'] as const,
    list: (patientId: number) => ['carePlans', 'list', patientId] as const,
  },
  vitals: {
    all: ['vitals'] as const,
    list: (patientId: string) => ['vitals', 'list', patientId] as const,
  },
  md: {
    all: ['md'] as const,
    dailyIncome: () => ['md', 'dailyIncome'] as const,
    dailyExpenses: () => ['md', 'dailyExpenses'] as const,
    monthlySummary: () => ['md', 'monthlySummary'] as const,
    stats: (date?: string) => ['md', 'stats', date ?? 'today'] as const,
    securityAlerts: () => ['md', 'securityAlerts'] as const,
    kpiBreakdown: (metric: string, range?: string) => ['md', 'kpiBreakdown', metric, range ?? 'current'] as const,
  },
  staff: {
    all: ['staff'] as const,
    list: () => ['staff', 'list'] as const,
  },
  settings: {
    all: ['settings'] as const,
    mfa: () => ['settings', 'mfa'] as const,
  },
  dischargePlanning: {
    all: ['dischargePlanning'] as const,
    list: (filters?: Record<string, unknown>) => ['dischargePlanning', 'list', filters] as const,
    stats: () => ['dischargePlanning', 'stats'] as const,
    detail: (id: number) => ['dischargePlanning', 'detail', id] as const,
  },
  prescriptions: {
    all: ['prescriptions'] as const,
    list: (filters?: Record<string, unknown>) => ['prescriptions', 'list', filters] as const,
    detail: (id: number) => ['prescriptions', 'detail', id] as const,
  },
  accounting: {
    all: ['accounting'] as const,
    dashboard: () => ['accounting', 'dashboard'] as const,
    income: (filters?: Record<string, string>) => ['accounting', 'income', filters] as const,
    expenses: (filters?: Record<string, string>) => ['accounting', 'expenses', filters] as const,
    receiptQueue: (filters?: Record<string, string>) => ['accounting', 'receiptQueue', filters] as const,
    journals: (filters?: Record<string, string>) => ['accounting', 'journals', filters] as const,
    chartOfAccounts: (filters?: Record<string, string>) => ['accounting', 'chartOfAccounts', filters] as const,
    profitLoss: (month: string) => ['accounting', 'profitLoss', month] as const,
    profitHistory: () => ['accounting', 'profitHistory'] as const,
    recurring: () => ['accounting', 'recurring'] as const,
    accounts: () => ['accounting', 'accounts'] as const,
    fiscalYears: () => ['accounting', 'fiscalYears'] as const,
    pendingVouchers: () => ['accounting', 'pendingVouchers'] as const,
  },
  admin: {
    all: ['admin'] as const,
    dashboard: (date?: string) => ['admin', 'dashboard', date ?? 'today'] as const,
    securityAlerts: (date?: string) => ['admin', 'security-alerts', date ?? 'today'] as const,
    activeCounters: () => ['admin', 'active-counters'] as const,
    cashControl: (date: string) => ['admin', 'cash-control', date] as const,
    fraudAlerts: () => ['admin', 'fraud-alerts'] as const,
    operatorPerformance: (days?: number) => ['admin', 'operator-performance', days] as const,
    opdMonitor: () => ['admin', 'opd-monitor'] as const,
    diagnosticMonitor: () => ['admin', 'diagnostic-monitor'] as const,
    ipdMonitor: () => ['admin', 'ipd-monitor'] as const,
    pharmacyMonitor: () => ['admin', 'pharmacy-monitor'] as const,
    exportHistory: () => ['admin', 'export-history'] as const,
    loginSessions: () => ['admin', 'login-sessions'] as const,
    suspiciousActivities: () => ['admin', 'suspicious-activities'] as const,
    executiveOverview: () => ['admin', 'executive-overview'] as const,
    revenueAnalytics: () => ['admin', 'revenue-analytics'] as const,
    notificationRules: () => ['admin', 'notification-rules'] as const,
    approvalPolicies: () => ['admin', 'approval-policies'] as const,
    discountRules: () => ['admin', 'discount-rules'] as const,
    cashDrawerDetail: (id: string) => ['admin', 'cash-drawer', id] as const,
    refundDetail: (id: string) => ['admin', 'refund', id] as const,
    auditExplorer: () => ['admin', 'audit-explorer'] as const,
    patientRecordAccess: () => ['admin', 'patient-record-access'] as const,
    expenseDetail: (id: string) => ['admin', 'expense', id] as const,
    doctorPayoutDetail: (id: string) => ['admin', 'doctor-payout', id] as const,
    discountReferenceAnalytics: () => ['admin', 'discount-references'] as const,
    escalationRules: () => ['admin', 'escalation-rules'] as const,
    shiftHandover: () => ['admin', 'shift-handover'] as const,
    shiftHandoverDetail: (id: string) => ['admin', 'shift-handover', id] as const,
    dailyCollection: (date: string) => ['admin', 'daily-collection', date] as const,
    expenses: (filters?: Record<string, unknown>) => ['admin', 'expenses', filters] as const,
    doctorCommission: () => ['admin', 'doctor-commission'] as const,
    dueReceivables: () => ['admin', 'due-receivables'] as const,
    pendingApprovals: () => ['admin', 'pending-approvals'] as const,
    pendingApprovalsSummary: () => ['admin', 'pending-approvals', 'summary'] as const,
    alertsExceptions: () => ['admin', 'alerts'] as const,
    tasksFollowups: () => ['admin', 'tasks'] as const,
    inventoryAlerts: () => ['admin', 'inventory-alerts'] as const,
    hospitalProfile: () => ['admin', 'hospital-profile'] as const,
    deptAnalytics: () => ['admin', 'dept-analytics'] as const,
    doctorAnalytics: () => ['admin', 'doctor-analytics'] as const,
    financialAudit: () => ['admin', 'financial-audit'] as const,
    revenueTrend: () => ['admin', 'revenue-trend'] as const,
    paymentBreakdown: () => ['admin', 'payment-breakdown'] as const,
    financialControl: (startDate: string, endDate: string) => ['admin', 'financial-control', startDate, endDate] as const,
    patientAgeAnalytics: (periodQuery: string) => ['admin', 'patient-age-analytics', periodQuery] as const,
    patientAgeDetails: (detailQuery: string) => ['admin', 'patient-age-details', detailQuery] as const,
    patientAnalytics: () => ['admin', 'patient-analytics'] as const,
    inventoryAnalytics: () => ['admin', 'inventory-analytics'] as const,
  },
  ipdReports: {
    admissions: (from: string, to: string) => ['ipdReports', 'admissions', from, to] as const,
    discharges: (from: string, to: string) => ['ipdReports', 'discharges', from, to] as const,
    transfers: (from: string, to: string) => ['ipdReports', 'transfers', from, to] as const,
    revenue: (from: string, to: string) => ['ipdReports', 'revenue', from, to] as const,
    wardPatients: () => ['ipdReports', 'wardPatients'] as const,
  },
  shareholders: {
    all: ['shareholders'] as const,
    list: () => ['shareholders', 'list'] as const,
    calculate: (month: string) => ['shareholders', 'calculate', month] as const,
  },
  bloodBank: {
    all: ['bloodBank'] as const,
    stock: () => ['bloodBank', 'stock'] as const,
    stats: () => ['bloodBank', 'stats'] as const,
    donors: (filters?: Record<string, unknown>) => ['bloodBank', 'donors', filters] as const,
    donations: (filters?: Record<string, unknown>) => ['bloodBank', 'donations', filters] as const,
    crossMatch: () => ['bloodBank', 'crossMatch'] as const,
    transfusions: () => ['bloodBank', 'transfusions'] as const,
  },
  documents: {
    all: ['documents'] as const,
    list: (filters?: Record<string, unknown>) => ['documents', 'list', filters] as const,
    summary: (patientId: string) => ['documents', 'summary', patientId] as const,
  },
  procedureOrders: {
    all: ['procedureOrders'] as const,
    list: () => ['procedureOrders', 'list'] as const,
  },
  assets: {
    all: ['assets'] as const,
    list: (filters?: Record<string, unknown>) => ['assets', 'list', filters] as const,
    stats: () => ['assets', 'stats'] as const,
    amc: () => ['assets', 'amc'] as const,
    maintenance: (filters?: Record<string, unknown>) => ['assets', 'maintenance', filters] as const,
    allocations: () => ['assets', 'allocations'] as const,
  },
  ePrescribing: {
    all: ['ePrescribing'] as const,
    stats: () => ['ePrescribing', 'stats'] as const,
    formulary: (filters?: Record<string, unknown>) => ['ePrescribing', 'formulary', filters] as const,
    interactions: (filters?: Record<string, unknown>) => ['ePrescribing', 'interactions', filters] as const,
  },
  hr: {
    all: ['hr'] as const,
    dashboard: () => ['hr', 'dashboard'] as const,
    staff: () => ['hr', 'staff'] as const,
    leaveCategories: () => ['hr', 'leave', 'categories'] as const,
    leaveRequests: () => ['hr', 'leave', 'requests'] as const,
    shifts: () => ['hr', 'attendance', 'shifts'] as const,
    attendanceSummary: (month: string) => ['hr', 'attendance', 'summary', month] as const,
    attendanceReport: (from: string, to: string) => ['hr', 'attendance', 'report', from, to] as const,
    salaryHeads: () => ['hr', 'payroll', 'salary-heads'] as const,
    payrollRuns: () => ['hr', 'payroll', 'runs'] as const,
    salaryStructure: (staffId: string) => ['hr', 'payroll', 'structure', staffId] as const,
    payslipAdjustments: (runId: number) => ['hr', 'payroll', 'adjustments', runId] as const,
    staffList: () => ['hr', 'staff-list'] as const,
  },
  telemedicine: {
    all: ['telemedicine'] as const,
    rooms: () => ['telemedicine', 'rooms'] as const,
    consultations: () => ['telemedicine', 'consultations'] as const,
  },
  dutyRoster: {
    all: ['dutyRoster'] as const,
    roster: (from: string, to: string) => ['dutyRoster', 'roster', from, to] as const,
    rotations: () => ['dutyRoster', 'rotations'] as const,
    holidays: () => ['dutyRoster', 'holidays'] as const,
    overtimeRules: () => ['dutyRoster', 'overtimeRules'] as const,
  },
  attendance: {
    all: ['attendance'] as const,
    live: () => ['attendance', 'live'] as const,
    punchLog: (date: string, page: number, staff: string) => ['attendance', 'punchLog', date, page, staff] as const,
    devices: () => ['attendance', 'devices'] as const,
    enrollments: (staffId: number) => ['attendance', 'enrollments', staffId] as const,
    staffOptions: () => ['attendance', 'staffOptions'] as const,
  },
  allergies: {
    all: ['allergies'] as const,
    list: (patientId: string) => ['allergies', 'list', patientId] as const,
  },
  vaccination: {
    all: ['vaccination'] as const,
    stats: () => ['vaccination', 'stats'] as const,
    patientSearch: (search: string) => ['vaccination', 'patientSearch', search] as const,
    patientRecords: (patientId: number) => ['vaccination', 'patientRecords', patientId] as const,
    activeVaccines: () => ['vaccination', 'activeVaccines'] as const,
    catalog: (search: string) => ['vaccination', 'catalog', search] as const,
    dueReport: () => ['vaccination', 'dueReport'] as const,
    rangeReport: (from: string, to: string) => ['vaccination', 'rangeReport', from, to] as const,
  },
  whatsapp: {
    all: ['whatsapp'] as const,
    messages: (filters?: Record<string, string>) => ['whatsapp', 'messages', filters] as const,
    stats: () => ['whatsapp', 'stats'] as const,
    templates: () => ['whatsapp', 'templates'] as const,
    config: () => ['whatsapp', 'config'] as const,
  },
  ambulance: {
    all: ['ambulance'] as const,
    active: () => ['ambulance', 'active'] as const,
    stats: () => ['ambulance', 'stats'] as const,
    trips: () => ['ambulance', 'trips'] as const,
    vehicles: () => ['ambulance', 'vehicles'] as const,
  },
  kitchen: {
    all: ['kitchen'] as const,
    orders: (filters?: Record<string, unknown>) => ['kitchen', 'orders', filters] as const,
    stats: (date: string) => ['kitchen', 'stats', date] as const,
    wardSummary: (date: string) => ['kitchen', 'wardSummary', date] as const,
    dietTypes: () => ['kitchen', 'dietTypes'] as const,
    mealSchedules: () => ['kitchen', 'mealSchedules'] as const,
  },
  cssd: {
    all: ['cssd'] as const,
    inventory: () => ['cssd', 'inventory'] as const,
    stats: () => ['cssd', 'stats'] as const,
    cycles: () => ['cssd', 'cycles'] as const,
    sets: () => ['cssd', 'sets'] as const,
    collections: () => ['cssd', 'collections'] as const,
  },
  billingReports: {
    all: ['billingReports'] as const,
    dailySales: (date: string) => ['billingReports', 'daily-sales', date] as const,
    daybook: (startDate: string, endDate: string) => ['billingReports', 'daybook', startDate, endDate] as const,
    deptDaybook: (startDate: string, endDate: string) => ['billingReports', 'dept-daybook', startDate, endDate] as const,
    doctorIncome: (startDate: string, endDate: string) => ['billingReports', 'doctor-income', startDate, endDate] as const,
    itemSummary: (startDate: string, endDate: string) => ['billingReports', 'item-summary', startDate, endDate] as const,
    userCash: (startDate: string, endDate: string) => ['billingReports', 'user-cash', startDate, endDate] as const,
    paymentMode: (startDate: string, endDate: string) => ['billingReports', 'payment-mode', startDate, endDate] as const,
    handover: (startDate: string, endDate: string) => ['billingReports', 'handover', startDate, endDate] as const,
    discount: (startDate: string, endDate: string) => ['billingReports', 'discount', startDate, endDate] as const,
    denomination: (date: string) => ['billingReports', 'denomination', date] as const,
  },
  billingMaster: {
    all: ['billingMaster'] as const,
    schemes: (page: number) => ['billingMaster', 'schemes', page] as const,
    priceCategories: (page: number) => ['billingMaster', 'priceCategories', page] as const,
    departments: (page: number) => ['billingMaster', 'departments', page] as const,
    items: (page: number, search?: string, deptId?: number | null) => ['billingMaster', 'items', page, search, deptId] as const,
    fiscalYears: (page: number) => ['billingMaster', 'fiscalYears', page] as const,
    creditOrgs: (page: number) => ['billingMaster', 'creditOrgs', page] as const,
    packages: (page: number) => ['billingMaster', 'packages', page] as const,
    memberships: (page: number) => ['billingMaster', 'memberships', page] as const,
    depositHeads: (page: number) => ['billingMaster', 'depositHeads', page] as const,
    counters: (page: number) => ['billingMaster', 'counters', page] as const,
    referralHospitals: () => ['billingMaster', 'referralHospitals'] as const,
  },
  billingHandover: {
    all: ['billingHandover'] as const,
    list: (filters?: Record<string, unknown>) => ['billingHandover', 'list', filters] as const,
  },
  billCancellation: {
    all: ['billCancellation'] as const,
    list: () => ['billCancellation', 'list'] as const,
  },
  creditNotes: {
    all: ['creditNotes'] as const,
    list: (filters?: Record<string, unknown>) => ['creditNotes', 'list', filters] as const,
  },
  deposits: {
    all: ['deposits'] as const,
    list: (filters?: Record<string, unknown>) => ['deposits', 'list', filters] as const,
    advanceReport: (filters?: Record<string, unknown>) => ['deposits', 'advance-report', filters] as const,
    balance: (patientId: string) => ['deposits', 'balance', patientId] as const,
  },
  settlements: {
    all: ['settlements'] as const,
    list: (filters?: Record<string, unknown>) => ['settlements', 'list', filters] as const,
  },
  provisional: {
    all: ['provisional'] as const,
    list: (filters?: Record<string, unknown>) => ['provisional', 'list', filters] as const,
    summary: (filters?: Record<string, unknown>) => ['provisional', 'summary', filters] as const,
  },
  commissions: {
    all: ['commissions'] as const,
    list: (filters?: Record<string, unknown>) => ['commissions', 'list', filters] as const,
    doctorRules: (filters?: Record<string, unknown>) => ['commissions', 'doctorRules', filters] as const,
    doctorAccruals: (filters?: Record<string, unknown>) => ['commissions', 'doctorAccruals', filters] as const,
    doctorPayables: (filters?: Record<string, unknown>) => ['commissions', 'doctorPayables', filters] as const,
    settlements: (filters?: Record<string, unknown>) => ['commissions', 'settlements', filters] as const,
    settlementDetail: (id: number) => ['commissions', 'settlementDetail', id] as const,
  },
  permissions: {
    all: ['permissions'] as const,
    catalog: () => ['permissions', 'catalog'] as const,
    matrix: () => ['permissions', 'matrix'] as const,
    user: (userId: number) => ['permissions', 'user', userId] as const,
    modules: () => ['permissions', 'modules'] as const,
    staffSearch: (query: string) => ['permissions', 'staffSearch', query] as const,
  },
  consents: {
    all: ['consents'] as const,
    list: (filters?: Record<string, unknown>) => ['consents', 'list', filters] as const,
    templates: () => ['consents', 'templates'] as const,
  },
  housekeeping: {
    all: ['housekeeping'] as const,
    tasks: (filters?: Record<string, string>) => ['housekeeping', 'tasks', filters] as const,
    stats: () => ['housekeeping', 'stats'] as const,
    areas: () => ['housekeeping', 'areas'] as const,
    complaints: () => ['housekeeping', 'complaints'] as const,
    beds: () => ['housekeeping', 'beds'] as const,
  },
  laundry: {
    all: ['laundry'] as const,
    collections: (filters?: Record<string, string>) => ['laundry', 'collections', filters] as const,
    stats: () => ['laundry', 'stats'] as const,
    linenTypes: () => ['laundry', 'linenTypes'] as const,
  },
  mortuary: {
    all: ['mortuary'] as const,
    list: (filters?: Record<string, string>) => ['mortuary', 'list', filters] as const,
    stats: () => ['mortuary', 'stats'] as const,
  },
  deathRecords: {
    all: ['deathRecords'] as const,
    list: (filters?: Record<string, unknown>) => ['deathRecords', 'list', filters] as const,
    detail: (id: string) => ['deathRecords', 'detail', id] as const,
  },
  reports: {
    all: ['reports'] as const,
    monthly: (year: string) => ['reports', 'monthly', year] as const,
    monthlySummary: (month: string) => ['reports', 'monthlySummary', month] as const,
    pl: (startDate: string, endDate: string) => ['reports', 'pl', startDate, endDate] as const,
    incomeBySource: (startDate: string, endDate: string) => ['reports', 'incomeBySource', startDate, endDate] as const,
    bedOccupancy: () => ['reports', 'bedOccupancy'] as const,
    departmentRevenue: (startDate: string, endDate: string) => ['reports', 'departmentRevenue', startDate, endDate] as const,
    doctorPerformance: (startDate: string, endDate: string) => ['reports', 'doctorPerformance', startDate, endDate] as const,
    pharmacyDispensing: (filters?: Record<string, string>) => ['reports', 'pharmacyDispensing', filters] as const,
    pharmacyStockValue: () => ['reports', 'pharmacyStockValue'] as const,
    pharmacyExpiry: (days: string) => ['reports', 'pharmacyExpiry', days] as const,
    pharmacyTopDispensed: (filters?: Record<string, string>) => ['reports', 'pharmacyTopDispensed', filters] as const,
    appointmentNoShow: (filters?: Record<string, string>) => ['reports', 'appointmentNoShow', filters] as const,
    appointmentUtilization: (filters?: Record<string, string>) => ['reports', 'appointmentUtilization', filters] as const,
    appointmentPeakHours: (filters?: Record<string, string>) => ['reports', 'appointmentPeakHours', filters] as const,
    appointmentDailyVolume: (days: string) => ['reports', 'appointmentDailyVolume', days] as const,
    labByCategory: (filters?: Record<string, string>) => ['reports', 'labByCategory', filters] as const,
    labTat: (filters?: Record<string, string>) => ['reports', 'labTat', filters] as const,
    labTopTests: (filters?: Record<string, string>) => ['reports', 'labTopTests', filters] as const,
    labTrend: (days: string) => ['reports', 'labTrend', days] as const,
    labProfitability: (filters?: Record<string, string>) => ['reports', 'labProfitability', filters] as const,
    labDoctorSummary: (filters?: Record<string, string>) => ['reports', 'labDoctorSummary', filters] as const,
  },
  groupAttendance: {
    all: ['groupAttendance'] as const,
    sessions: () => ['groupAttendance', 'sessions'] as const,
    members: (sessionId: number) => ['groupAttendance', 'members', sessionId] as const,
    attendance: (sessionId: number) => ['groupAttendance', 'attendance', sessionId] as const,
  },
  patientDuplicates: {
    all: ['patientDuplicates'] as const,
    scan: (method: string) => ['patientDuplicates', 'scan', method] as const,
    stats: () => ['patientDuplicates', 'stats'] as const,
    history: () => ['patientDuplicates', 'history'] as const,
    compare: (id1: number, id2: number) => ['patientDuplicates', 'compare', id1, id2] as const,
  },
  patientTimeline: {
    all: ['patientTimeline'] as const,
    events: (patientId: string) => ['patientTimeline', 'events', patientId] as const,
  },
  website: {
    all: ['website'] as const,
    config: () => ['website', 'config'] as const,
    services: () => ['website', 'services'] as const,
    gallery: () => ['website', 'gallery'] as const,
    blogPosts: () => ['website', 'blogPosts'] as const,
    reviews: () => ['website', 'reviews'] as const,
    departments: () => ['website', 'departments'] as const,
  },
  printTemplates: {
    all: ['printTemplates'] as const,
    list: (filters?: Record<string, unknown>) => ['printTemplates', 'list', filters] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    list: (filter: string, offset: number) => ['notifications', 'list', filter, offset] as const,
  },
  auditLog: {
    all: ['auditLog'] as const,
    logs: () => ['auditLog', 'logs'] as const,
  },
  qualityKpi: {
    all: ['qualityKpi'] as const,
    dashboard: (dateFrom: string, dateTo: string) => ['qualityKpi', 'dashboard', dateFrom, dateTo] as const,
    trends: (dateFrom: string, dateTo: string) => ['qualityKpi', 'trends', dateFrom, dateTo] as const,
  },
  trackAnything: {
    all: ['trackAnything'] as const,
    configs: () => ['trackAnything', 'configs'] as const,
    patientData: (patientId: number) => ['trackAnything', 'patientData', patientId] as const,
    patientSearch: (search: string) => ['trackAnything', 'patientSearch', search] as const,
  },
  branches: {
    all: ['branches'] as const,
    analytics: (slug: string) => ['branches', 'analytics', slug] as const,
  },
  marketingReferral: {
    all: ['marketingReferral'] as const,
    schemes: () => ['marketingReferral', 'schemes'] as const,
    organizations: () => ['marketingReferral', 'organizations'] as const,
    parties: () => ['marketingReferral', 'parties'] as const,
    report: (filters?: Record<string, string>) => ['marketingReferral', 'report', filters] as const,
  },
  digitalPrescription: {
    all: ['digitalPrescription'] as const,
    detail: (id: number) => ['digitalPrescription', 'detail', id] as const,
    formularySearch: (q: string) => ['digitalPrescription', 'formularySearch', q] as const,
  },
  healthRecord: {
    all: ['healthRecord'] as const,
    lookup: (nid: string) => ['healthRecord', 'lookup', nid] as const,
    summary: (token: string) => ['healthRecord', 'summary', token] as const,
    linkedRecords: (patientId: string) => ['healthRecord', 'linkedRecords', patientId] as const,
    consents: (patientId: string) => ['healthRecord', 'consents', patientId] as const,
  },
  priorAuth: {
    all: ['priorAuth'] as const,
    list: () => ['priorAuth', 'list'] as const,
  },
  biomedicalWaste: {
    all: ['biomedicalWaste'] as const,
    collections: () => ['biomedicalWaste', 'collections'] as const,
    categories: () => ['biomedicalWaste', 'categories'] as const,
    stats: () => ['biomedicalWaste', 'stats'] as const,
  },
  lbfForms: {
    all: ['lbfForms'] as const,
    list: () => ['lbfForms', 'list'] as const,
    detail: (formId: number) => ['lbfForms', 'detail', formId] as const,
  },
  doctorSchedules: {
    all: ['doctorSchedules'] as const,
    doctors: () => ['doctorSchedules', 'doctors'] as const,
    list: (doctorId: number) => ['doctorSchedules', 'list', doctorId] as const,
  },
  superAdmin: {
    all: ['superAdmin'] as const,
    onboarding: (status: string) => ['superAdmin', 'onboarding', status] as const,
    hospitals: () => ['superAdmin', 'hospitals'] as const,
    hospitalDetail: (id: string) => ['superAdmin', 'hospitalDetail', id] as const,
  },
  audit: {
    all: ['audit'] as const,
    logs: (filters?: Record<string, string>) => ['audit', 'logs', filters] as const,
  },
  inventoryLedger: {
    all: ['inventoryLedger'] as const,
    transactions: (filters?: Record<string, unknown>) => ['inventoryLedger', 'transactions', filters] as const,
  },
  lab: {
    all: ['lab'] as const,
    catalog: () => ['lab', 'catalog'] as const,
  },
  labMachines: {
    all: ['labMachines'] as const,
    list: () => ['labMachines', 'list'] as const,
    testMap: (machineId: number) => ['labMachines', 'testMap', machineId] as const,
    logs: (machineId: number, filter?: string) => ['labMachines', 'logs', machineId, filter] as const,
    unmatchedResults: (machineId: number, status?: string) => ['labMachines', 'unmatchedResults', machineId, status] as const,
    logDetail: (machineId: number, logId: number) => ['labMachines', 'logDetail', machineId, logId] as const,
  },
  labSettings: {
    all: ['labSettings'] as const,
    categories: () => ['labSettings', 'categories'] as const,
    templates: () => ['labSettings', 'templates'] as const,
    vendors: () => ['labSettings', 'vendors'] as const,
    runNumber: () => ['labSettings', 'runNumber'] as const,
    referenceRanges: () => ['labSettings', 'referenceRanges'] as const,
    rejectionReasons: () => ['labSettings', 'rejectionReasons'] as const,
    govReports: () => ['labSettings', 'govReports'] as const,
  },
  labQc: {
    all: ['labQc'] as const,
    controls: () => ['labQc', 'controls'] as const,
    ranges: () => ['labQc', 'ranges'] as const,
    readings: (controlId?: number) => ['labQc', 'readings', controlId] as const,
    calibrations: (machineId?: number) => ['labQc', 'calibrations', machineId] as const,
    upcomingCalibrations: () => ['labQc', 'calibrations', 'upcoming'] as const,
    overdueCalibrations: () => ['labQc', 'calibrations', 'overdue'] as const,
  },
  labGovReporting: {
    all: ['labGovReporting'] as const,
    reports: (filters?: Record<string, string>) => ['labGovReporting', 'reports', filters] as const,
  },
  labOrders: {
    all: ['labOrders'] as const,
    catalog: (search?: string) => ['labOrders', 'catalog', search] as const,
  },
  medicalRecords: {
    all: ['medicalRecords'] as const,
    stats: () => ['medicalRecords', 'stats'] as const,
    list: (filters?: Record<string, unknown>) => ['medicalRecords', 'list', filters] as const,
    births: (filters?: Record<string, unknown>) => ['medicalRecords', 'births', filters] as const,
    deaths: (filters?: Record<string, unknown>) => ['medicalRecords', 'deaths', filters] as const,
    icd10: (search?: string) => ['medicalRecords', 'icd10', search] as const,
    referrals: (filters?: Record<string, unknown>) => ['medicalRecords', 'referrals', filters] as const,
  },
  patientChart: {
    all: ['patientChart'] as const,
    detail: (patientId: string, includeAi?: boolean) => ['patientChart', 'detail', patientId, includeAi] as const,
    source: (patientId: string, sourceId: string) => ['patientChart', 'source', patientId, sourceId] as const,
    soapTemplates: () => ['patientChart', 'soapTemplates'] as const,
    labCatalog: (search: string) => ['patientChart', 'labCatalog', search] as const,
    timeline: (patientId: string) => ['patientChart', 'timeline', patientId] as const,
  },
  camos: {
    all: ['camos'] as const,
    categories: () => ['camos', 'categories'] as const,
    subcategories: (categoryId: number) => ['camos', 'subcategories', categoryId] as const,
    items: (subcategoryId: number) => ['camos', 'items', subcategoryId] as const,
    assessments: (patientId: number) => ['camos', 'assessments', patientId] as const,
    patientSearch: (query: string) => ['camos', 'patientSearch', query] as const,
  },
  billPrint: {
    all: ['billPrint'] as const,
    detail: (billId: string) => ['billPrint', 'detail', billId] as const,
  },
  labReport: {
    all: ['labReport'] as const,
    detail: (labId: string) => ['labReport', 'detail', labId] as const,
  },
  prescriptionPrint: {
    all: ['prescriptionPrint'] as const,
    detail: (prescriptionId: string) => ['prescriptionPrint', 'detail', prescriptionId] as const,
  },
  queueDisplay: {
    all: ['queueDisplay'] as const,
    data: () => ['queueDisplay', 'data'] as const,
  },
  dental: {
    all: ['dental'] as const,
    chart: (patientId: number) => ['dental', 'chart', patientId] as const,
    treatments: (patientId: number) => ['dental', 'treatments', patientId] as const,
  },
  psychiatry: {
    all: ['psychiatry'] as const,
    mse: (patientId: number) => ['psychiatry', 'mse', patientId] as const,
  },
  eyeExam: {
    all: ['eyeExam'] as const,
    list: (patientId: number) => ['eyeExam', 'list', patientId] as const,
  },
  physicalExam: {
    all: ['physicalExam'] as const,
    lines: () => ['physicalExam', 'lines'] as const,
    list: (patientId: number) => ['physicalExam', 'list', patientId] as const,
  },
  dictation: {
    all: ['dictation'] as const,
    list: (status?: string) => ['dictation', 'list', status] as const,
    stats: () => ['dictation', 'stats'] as const,
  },
  questionnaires: {
    all: ['questionnaires'] as const,
    list: () => ['questionnaires', 'list'] as const,
    detail: (id: number) => ['questionnaires', 'detail', id] as const,
  },
  feeSheet: {
    all: ['feeSheet'] as const,
    list: (patientId: number) => ['feeSheet', 'list', patientId] as const,
  },
  mlc: {
    all: ['mlc'] as const,
    list: (filters?: Record<string, string>) => ['mlc', 'list', filters] as const,
    stats: () => ['mlc', 'stats'] as const,
    detail: (id: number) => ['mlc', 'detail', id] as const,
  },
  orderSets: {
    all: ['orderSets'] as const,
    list: (filters?: Record<string, string>) => ['orderSets', 'list', filters] as const,
    detail: (id: number) => ['orderSets', 'detail', id] as const,
    favorites: () => ['orderSets', 'favorites'] as const,
  },
  clinicalReminders: {
    all: ['clinicalReminders'] as const,
    rules: () => ['clinicalReminders', 'rules'] as const,
    patientReminders: (patientId: string) => ['clinicalReminders', 'patient', patientId] as const,
  },
  ai: {
    patientSummary: (patientId: number) => ['ai', 'patient-summary', patientId] as const,
  },
  clinical: {
    all: ['clinical'] as const,
    notes: (patientId: string) => ['clinical', 'notes', patientId] as const,
    noteDetail: (noteId: number) => ['clinical', 'note', noteId] as const,
    problems: (patientId: string) => ['clinical', 'problems', patientId] as const,
    medications: (patientId: string) => ['clinical', 'medications', patientId] as const,
    history: (patientId: string, type: string) => ['clinical', 'history', patientId, type] as const,
    diagnosis: (patientId: string) => ['clinical', 'diagnosis', patientId] as const,
    encounters: (patientId: string) => ['clinical', 'encounters', patientId] as const,
    encounterSummary: (encounterId: number) => ['clinical', 'encounter', encounterId, 'summary'] as const,
  },
  visits: {
    all: ['visits'] as const,
    list: (filters?: Record<string, unknown>) => ['visits', 'list', filters] as const,
    detail: (id: number) => ['visits', 'detail', id] as const,
  },
  dueAging: {
    all: ['dueAging'] as const,
    summary: (asOfDate?: string) => ['dueAging', 'summary', asOfDate] as const,
    details: (bucket: string, asOfDate?: string) => ['dueAging', 'details', bucket, asOfDate] as const,
  },
  cashBook: {
    all: ['cashBook'] as const,
    summary: (date: string) => ['cashBook', 'summary', date] as const,
    transactions: (date: string) => ['cashBook', 'transactions', date] as const,
  },
  bankBook: {
    all: ['bankBook'] as const,
    summary: (date: string) => ['bankBook', 'summary', date] as const,
    transactions: (date: string) => ['bankBook', 'transactions', date] as const,
  },
};
