import {
  LayoutDashboard, Users, FlaskConical, Receipt, Package,
  UserCog, PieChart, Settings, Building2, Wallet, TrendingDown,
  BedDouble, Stethoscope, Shield, ShieldAlert,
  Siren, Scissors, ArrowRightLeft,
  BarChart3, CalendarDays, Activity,
  CreditCard, Percent, ShieldCheck, ClipboardCheck,
  RefreshCw, ShoppingCart, MessageSquare,
  Printer,
  TrendingUp,
} from 'lucide-react';
import type { NavGroup } from './Sidebar';

/**
 * Admin sidebar structure — Starter HIS first, advanced modules lower.
 *
 * This is presentation cleanup only: routes, permissions, APIs, and feature
 * modules remain intact. The top groups prioritize operational control:
 * pending approvals → billing/cash → reagent/stock → patient setup.
 */
export const adminNavGroups: NavGroup[] = [
  {
    items: [
      { labelKey: 'dashboard', path: 'dashboard', icon: <LayoutDashboard className="w-4.5 h-4.5" /> },
    ],
  },
  {
    groupKey: 'groupActionCenter',
    items: [
      { labelKey: 'actionCenterOverview', path: 'action', icon: <LayoutDashboard className="w-4.5 h-4.5" /> },
      { labelKey: 'approvals', path: 'action/approvals', icon: <ShieldCheck className="w-4.5 h-4.5" /> },
      { labelKey: 'exceptions', path: 'action/exceptions', icon: <ShieldAlert className="w-4.5 h-4.5" /> },
      { labelKey: 'collections', path: 'action/collections', icon: <Wallet className="w-4.5 h-4.5" /> },
      { labelKey: 'tasks', path: 'action/tasks', icon: <ClipboardCheck className="w-4.5 h-4.5" /> },
    ],
  },
  {
    groupKey: 'groupPatientExperience',
    items: [
      { labelKey: 'reviewModeration', path: 'patient-experience/reviews', icon: <MessageSquare className="w-4.5 h-4.5" /> },
      { labelKey: 'marketplaceBookings', path: 'marketplace-bookings', icon: <CalendarDays className="w-4.5 h-4.5" /> },
    ],
  },
  {
    groupKey: 'groupStarterControl',
    items: [
      { labelKey: 'billingCounter', path: 'billing-counter', icon: <CreditCard className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'billingDashboard', path: 'billing', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'provisionalBilling', path: 'billing-provisional', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'billingReports', path: 'billing-reports', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'cashControl', path: 'cash/drawers', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'cashBankBook', path: 'cash-bank-book', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
      { labelKey: 'transactionControl', path: 'transaction-control', icon: <ShieldCheck className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'shiftHandover', path: 'cash/handover', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'handover:read' },
      { labelKey: 'billingHandover', path: 'billing-handover', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'billingCancellation', path: 'billing-cancellation', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'payments', path: 'payments', icon: <CreditCard className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'deposits', path: 'deposits', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'creditNotes', path: 'credit-notes', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'settlements', path: 'settlements', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'cashDeposits', path: 'cash/deposits', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'discountReview', path: 'cash/discounts', icon: <Percent className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'discountAnalytics', path: 'cash/discounts/analytics', icon: <Percent className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'refunds', path: 'cash/refunds', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'expenses', path: 'cash/expenses', icon: <TrendingDown className="w-4.5 h-4.5" />, requiredPermission: 'expenses:read' },
      { labelKey: 'doctorCommissions', path: 'cash/commissions', icon: <Percent className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
      {
        labelKey: 'accountingFinance',
        path: 'accounting',
        icon: <Wallet className="w-4.5 h-4.5" />,
        requiredPermission: 'accounting:read',
        children: [
          { labelKey: 'accounting', path: 'accounting', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
          { labelKey: 'income', path: 'income', icon: <TrendingUp className="w-4.5 h-4.5" />, requiredPermission: 'income:read' },
          { labelKey: 'expenses', path: 'expenses', icon: <TrendingDown className="w-4.5 h-4.5" />, requiredPermission: 'expenses:read' },
          { labelKey: 'recurring', path: 'recurring', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'expenses:read' },
          { labelKey: 'accounts', path: 'accounts', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
          { labelKey: 'journal', path: 'journal', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
          { labelKey: 'commissions', path: 'commissions', icon: <Percent className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
          { labelKey: 'shareholders', path: 'shareholders', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'shareholders:read' },
          { labelKey: 'profitLoss', path: 'profit-loss', icon: <TrendingUp className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
          { labelKey: 'fiscalYearSettings', path: 'fiscal-year-settings', icon: <CalendarDays className="w-4.5 h-4.5" />, requiredPermission: 'fiscalYear:write' },
          { labelKey: 'voucherVerification', path: 'voucher-verification', icon: <ShieldCheck className="w-4.5 h-4.5" />, requiredPermission: 'voucher:verify' },
        ],
      },
    ],
  },
  {
    groupKey: 'groupReagentStock',
    items: [
      { labelKey: 'inventoryDashboard', path: 'inventory', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
      { labelKey: 'reagentControl', path: 'reagent-control', icon: <FlaskConical className="w-4.5 h-4.5" />, requiredPermission: 'lab_machines:read' },
      {
        labelKey: 'inventoryMain',
        path: 'inventory',
        icon: <Package className="w-4.5 h-4.5" />,
        requiredPermission: 'inventory:read',
        children: [
          { labelKey: 'inventoryQuickStart', path: 'inventory/quick-start', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'stockOverview', path: 'inventory/overview', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'stockList', path: 'inventory/stock', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'inventoryAlerts', path: 'inventory/alerts', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'inventoryLedger', path: 'inventory/ledger', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'inventoryTraceability', path: 'inventory/traceability', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'inventoryMasterData', path: 'inventory/master-data', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'inventoryAccounting', path: 'inventory/accounting', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'accounting:read' },
        ],
      },
      {
        labelKey: 'inventoryProcurement',
        path: 'inventory/purchase',
        icon: <ShoppingCart className="w-4.5 h-4.5" />,
        requiredPermission: 'inventory:write',
        children: [
          { labelKey: 'purchaseRequests', path: 'inventory/purchase', icon: <ShoppingCart className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'purchaseOrders', path: 'inventory/po', icon: <ShoppingCart className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'newPurchaseOrder', path: 'inventory/po/new', icon: <ShoppingCart className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'goodsReceipts', path: 'inventory/gr', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'newGoodsReceipt', path: 'inventory/gr/new', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'requisitions', path: 'inventory/requisitions', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'newRequisition', path: 'inventory/requisitions/new', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'rfq', path: 'inventory/rfq', icon: <ShoppingCart className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'importExport', path: 'inventory/import-export', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'donations', path: 'inventory/donations', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'returnToVendor', path: 'inventory/return-to-vendor', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
        ],
      },
      {
        labelKey: 'inventoryOperations',
        path: 'inventory/issues',
        icon: <Activity className="w-4.5 h-4.5" />,
        requiredPermission: 'inventory:consume',
        children: [
          { labelKey: 'dispatches', path: 'inventory/dispatches', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'newDispatch', path: 'inventory/dispatches/new', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'stockIssues', path: 'inventory/issues', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'inventory:consume' },
          { labelKey: 'transfers', path: 'inventory/transfers', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'inventory:transfer' },
          { labelKey: 'returns', path: 'inventory/returns', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'inventory:consume' },
          { labelKey: 'stockCounts', path: 'inventory/counts', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'stockAdjustment', path: 'inventory/stock/adjust', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:adjust' },
          { labelKey: 'stockAdjustments', path: 'inventory/adjustments', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:adjust' },
          { labelKey: 'adjustmentRequests', path: 'inventory/adjustment-requests', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'writeOffs', path: 'inventory/write-off', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
        ],
      },
      {
        labelKey: 'inventoryAutomation',
        path: 'inventory/consumption-rules',
        icon: <ShieldCheck className="w-4.5 h-4.5" />,
        requiredPermission: 'inventory:write',
        children: [
          { labelKey: 'inventoryConsumptionRules', path: 'inventory/consumption-rules', icon: <ShieldCheck className="w-4.5 h-4.5" />, requiredPermission: 'inventory:write' },
          { labelKey: 'inventoryConsumptionQueue', path: 'inventory/consumption-queue', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'inventory:consume' },
          { labelKey: 'inventoryConsumptionExceptions', path: 'inventory/consumption-exceptions', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'inventory:consume' },
        ],
      },
      { labelKey: 'inventoryReports', path: 'inventory/reports', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'inventory:reports' },
    ],
  },
  {
    groupKey: 'groupPatientServices',
    items: [
      { labelKey: 'patients', path: 'patients', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
      { labelKey: 'newPatient', path: 'patients/new', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'patients:write' },
      { labelKey: 'doctors', path: 'doctors', icon: <Stethoscope className="w-4.5 h-4.5" />, requiredPermission: 'doctor:read' },
      { labelKey: 'appointments', path: 'appointments', icon: <CalendarDays className="w-4.5 h-4.5" />, requiredPermission: 'appointments:read' },
      { labelKey: 'incomingReferrals', path: 'referrals', icon: <ArrowRightLeft className="w-4.5 h-4.5" /> },
      { labelKey: 'createReferral', path: 'referrals/new', icon: <ArrowRightLeft className="w-4.5 h-4.5" /> },
      { labelKey: 'patientPortal', path: 'patient-portal', icon: <Users className="w-4.5 h-4.5" /> },
      { labelKey: 'patientDuplicates', path: 'patient-duplicates', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
      { labelKey: 'patientCardScan', path: 'patient-card-scan', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
      { labelKey: 'importRecords', path: 'import-records', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'patients:write' },
      { labelKey: 'healthRecords', path: 'health-records', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
      { labelKey: 'medicalRecords', path: 'medical-records', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
      { labelKey: 'deathRecords', path: 'death-records', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
      { labelKey: 'servicesPricing', path: 'billing-master', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'billing:read' },
      { labelKey: 'branchesDepartments', path: 'settings/departments', icon: <Building2 className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      {
        labelKey: 'clinicalWorkspace',
        path: 'clinical',
        icon: <Stethoscope className="w-4.5 h-4.5" />,
        requiredPermission: 'patients:read',
        children: [
          { labelKey: 'aiAssistant', path: 'ai-assistant', icon: <Activity className="w-4.5 h-4.5" /> },
          { labelKey: 'consultationNotes', path: 'consultation-notes', icon: <Receipt className="w-4.5 h-4.5" /> },
          { labelKey: 'newPrescription', path: 'prescriptions/new', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'prescriptions:write' },
          { labelKey: 'ePrescribing', path: 'e-prescribing', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'prescriptions:write' },
          { labelKey: 'clinicalAssessments', path: 'clinical', icon: <Stethoscope className="w-4.5 h-4.5" /> },
          { labelKey: 'carePlans', path: 'care-plans', icon: <ClipboardCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'trackAnything', path: 'track-anything', icon: <Activity className="w-4.5 h-4.5" /> },
          { labelKey: 'priorAuth', path: 'prior-auth', icon: <ShieldCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'procedureOrders', path: 'procedure-orders', icon: <ClipboardCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'questionnaires', path: 'questionnaires', icon: <ClipboardCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'formBuilder', path: 'form-builder', icon: <Settings className="w-4.5 h-4.5" /> },
          { labelKey: 'orderSets', path: 'order-sets', icon: <ClipboardCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'clinicalReminders', path: 'clinical-reminders', icon: <ShieldAlert className="w-4.5 h-4.5" /> },
          { labelKey: 'consents', path: 'consents', icon: <ShieldCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'documents', path: 'documents', icon: <Receipt className="w-4.5 h-4.5" /> },
          { labelKey: 'telemedicine', path: 'telemedicine', icon: <Activity className="w-4.5 h-4.5" /> },
        ],
      },
      {
        labelKey: 'specialtyClinical',
        path: 'dental',
        icon: <Stethoscope className="w-4.5 h-4.5" />,
        children: [
          { labelKey: 'dental', path: 'dental', icon: <Stethoscope className="w-4.5 h-4.5" /> },
          { labelKey: 'psychiatry', path: 'psychiatry', icon: <Stethoscope className="w-4.5 h-4.5" /> },
          { labelKey: 'eyeExam', path: 'eye-exam', icon: <Stethoscope className="w-4.5 h-4.5" /> },
          { labelKey: 'physicalExam', path: 'physical-exam', icon: <Stethoscope className="w-4.5 h-4.5" /> },
          { labelKey: 'dictation', path: 'dictation', icon: <Activity className="w-4.5 h-4.5" /> },
          { labelKey: 'groupAttendance', path: 'group-attendance', icon: <Users className="w-4.5 h-4.5" /> },
          { labelKey: 'feeSheet', path: 'fee-sheet', icon: <Receipt className="w-4.5 h-4.5" /> },
          { labelKey: 'camos', path: 'camos', icon: <ClipboardCheck className="w-4.5 h-4.5" /> },
        ],
      },
      {
        labelKey: 'diagnosticsAndInsurance',
        path: 'radiology',
        icon: <FlaskConical className="w-4.5 h-4.5" />,
        children: [
          { labelKey: 'radiology', path: 'radiology', icon: <FlaskConical className="w-4.5 h-4.5" /> },
          { labelKey: 'vaccination', path: 'vaccination', icon: <ShieldCheck className="w-4.5 h-4.5" /> },
          { labelKey: 'insuranceClaims', path: 'insurance-claims', icon: <Shield className="w-4.5 h-4.5" /> },
          { labelKey: 'insuranceBilling', path: 'insurance-billing', icon: <Shield className="w-4.5 h-4.5" /> },
        ],
      },
    ],
  },
  {
    groupKey: 'groupReportsAnalytics',
    items: [
      { labelKey: 'reports', path: 'reports', icon: <PieChart className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'reportsPdf', path: 'reports/pdf', icon: <Printer className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'collectionReports', path: 'cash/collections', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'labReports', path: 'reports/lab', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'pharmacyReports', path: 'reports/pharmacy', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'appointmentReports', path: 'reports/appointments', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsBranches', path: 'analytics/branches', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsExecutive', path: 'analytics/executive', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsRevenue', path: 'analytics/revenue', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsDepartments', path: 'analytics/departments', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsDoctors', path: 'analytics/doctors', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsPatients', path: 'analytics/patients', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsInventory', path: 'analytics/inventory', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
      { labelKey: 'analyticsBuilder', path: 'analytics/builder', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
    ],
  },
  {
    groupKey: 'groupAdvancedOperations',
    items: [
      { labelKey: 'dutyMonitor', path: 'monitor/operations', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'dashboard:read' },
      { labelKey: 'opdAppointments', path: 'monitor/opd', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'appointments:read' },
      { labelKey: 'diagnosticMonitor', path: 'monitor/lab', icon: <FlaskConical className="w-4.5 h-4.5" />, requiredPermission: 'tests:read' },
      { labelKey: 'pharmacyMonitor', path: 'monitor/pharmacy', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'pharmacy:read' },
      { labelKey: 'emergencyMonitor', path: 'monitor/emergency', icon: <Siren className="w-4.5 h-4.5" />, requiredPermission: 'emergency:read' },
      { labelKey: 'emergency', path: 'emergency', icon: <Siren className="w-4.5 h-4.5" />, requiredPermission: 'emergency:read' },
      { labelKey: 'triage', path: 'triage', icon: <Siren className="w-4.5 h-4.5" /> },
      {
        labelKey: 'ipdBeds',
        path: 'beds',
        icon: <BedDouble className="w-4.5 h-4.5" />,
        requiredPermission: 'admissions:read',
        children: [
          { labelKey: 'beds', path: 'beds', icon: <BedDouble className="w-4.5 h-4.5" />, requiredPermission: 'admissions:read' },
          { labelKey: 'admissions', path: 'admissions', icon: <BedDouble className="w-4.5 h-4.5" />, requiredPermission: 'admissions:read' },
          { labelKey: 'ipBilling', path: 'ip-billing', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'ip-billing:read' },
          { labelKey: 'ipdReports', path: 'ipd-reports', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
          { labelKey: 'nurseTasks', path: 'nurse-tasks', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'nursing:read' },
          { labelKey: 'wardSupply', path: 'ward-supply', icon: <Package className="w-4.5 h-4.5" />, requiredPermission: 'inventory:read' },
          { labelKey: 'dischargePlanning', path: 'discharge-planning', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'nursing:read' },
          { labelKey: 'housekeeping', path: 'housekeeping', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'admissions:read' },
          { labelKey: 'allergies', path: 'allergies', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'patients:read' },
          { labelKey: 'notifications', path: 'notifications', icon: <MessageSquare className="w-4.5 h-4.5" /> },
          { labelKey: 'nurseWorkload', path: 'nurse-workload', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'nursing:read' },
          { labelKey: 'nurseStation', path: 'nurse-station', icon: <Stethoscope className="w-4.5 h-4.5" />, requiredPermission: 'nursing:read' },
          { labelKey: 'nursing', path: 'nursing', icon: <Stethoscope className="w-4.5 h-4.5" />, requiredPermission: 'nursing:read' },
          { labelKey: 'nurseReports', path: 'nurse-reports', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'nursing:read' },
          { labelKey: 'vitals', path: 'vitals', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'vitals:read' },
        ],
      },
      {
        labelKey: 'otProcedures',
        path: 'ot',
        icon: <Scissors className="w-4.5 h-4.5" />,
        requiredPermission: 'ot:read',
        children: [
          { labelKey: 'otDashboard', path: 'ot', icon: <Scissors className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
          { labelKey: 'otMonitor', path: 'monitor/ot', icon: <Scissors className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
          { labelKey: 'otCalendar', path: 'ot/calendar', icon: <CalendarDays className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
          { labelKey: 'otReports', path: 'ot/reports', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
          { labelKey: 'otSettings', path: 'ot/settings', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
          { labelKey: 'otCommissionRules', path: 'ot/commission-rules', icon: <Percent className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
          { labelKey: 'surgery', path: 'surgery', icon: <Scissors className="w-4.5 h-4.5" />, requiredPermission: 'ot:read' },
        ],
      },
      {
        labelKey: 'hospitalOperations',
        path: 'asset-management',
        icon: <Building2 className="w-4.5 h-4.5" />,
        children: [
          { labelKey: 'assetManagement', path: 'asset-management', icon: <Building2 className="w-4.5 h-4.5" /> },
          { labelKey: 'kitchen', path: 'kitchen', icon: <Package className="w-4.5 h-4.5" /> },
          { labelKey: 'bloodBank', path: 'blood-bank', icon: <Siren className="w-4.5 h-4.5" /> },
          { labelKey: 'mlc', path: 'mlc', icon: <ShieldAlert className="w-4.5 h-4.5" /> },
          { labelKey: 'cssd', path: 'cssd', icon: <Package className="w-4.5 h-4.5" /> },
          { labelKey: 'laundry', path: 'laundry', icon: <RefreshCw className="w-4.5 h-4.5" /> },
          { labelKey: 'ambulance', path: 'ambulance', icon: <Siren className="w-4.5 h-4.5" /> },
          { labelKey: 'mortuary', path: 'mortuary', icon: <Shield className="w-4.5 h-4.5" /> },
          { labelKey: 'maternity', path: 'maternity', icon: <Users className="w-4.5 h-4.5" /> },
          { labelKey: 'biomedicalWaste', path: 'biomedical-waste', icon: <ShieldAlert className="w-4.5 h-4.5" /> },
          { labelKey: 'queueManagement', path: 'queue-management', icon: <Activity className="w-4.5 h-4.5" /> },
        ],
      },
    ],
  },
  {
    groupKey: 'groupPeopleAccess',
    items: [
      { labelKey: 'staff', path: 'staff', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'staff:read' },
      { labelKey: 'accessControl', path: 'permissions', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'roles:manage' },
      { labelKey: 'hrDashboard', path: 'hr', icon: <UserCog className="w-4.5 h-4.5" />, requiredPermission: 'hr:read' },
      { labelKey: 'leave', path: 'hr/leave', icon: <CalendarDays className="w-4.5 h-4.5" />, requiredPermission: 'hr:read' },
      { labelKey: 'payrollGeneration', path: 'hr/payroll-generation', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'hr:read' },
      { labelKey: 'dutyRoster', path: 'duty-roster', icon: <CalendarDays className="w-4.5 h-4.5" />, requiredPermission: 'hr:read' },
      { labelKey: 'attendancePunch', path: 'attendance-punch', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'hr:read' },
      { labelKey: 'invitations', path: 'invitations', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'staff:write' },
      { labelKey: 'doctorSchedule', path: 'doctor-schedule', icon: <CalendarDays className="w-4.5 h-4.5" /> },
    ],
  },
  {
    groupKey: 'groupAdvancedLabLis',
    items: [
      { labelKey: 'tests', path: 'tests', icon: <FlaskConical className="w-4.5 h-4.5" />, requiredPermission: 'tests:read' },
      { labelKey: 'labDashboard', path: 'lab/dashboard', icon: <FlaskConical className="w-4.5 h-4.5" />, requiredPermission: 'tests:read' },
      { labelKey: 'labTests', path: 'lab/tests', icon: <FlaskConical className="w-4.5 h-4.5" />, requiredPermission: 'tests:read' },
      { labelKey: 'labOrders', path: 'lab/orders', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'tests:write' },
      { labelKey: 'newLabOrder', path: 'lab/order/new', icon: <ClipboardCheck className="w-4.5 h-4.5" />, requiredPermission: 'tests:write' },
      { labelKey: 'testCatalog', path: 'test-catalog', icon: <FlaskConical className="w-4.5 h-4.5" />, requiredPermission: 'tests:write' },
      { labelKey: 'advancedLabSettings', path: 'lab-settings', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'tests:read' },
      { labelKey: 'labMachines', path: 'lab-machines', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'lab_machines:read' },
      { labelKey: 'labMachineRoute', path: 'lab/machines', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'lab_machines:read' },
      { labelKey: 'labMonitoring', path: 'lab/monitoring', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'lab_machines:read' },
      { labelKey: 'labQc', path: 'lab/qc', icon: <ShieldCheck className="w-4.5 h-4.5" />, requiredPermission: 'tests:verify' },
      { labelKey: 'labReports', path: 'reports/lab', icon: <BarChart3 className="w-4.5 h-4.5" />, requiredPermission: 'reports:read' },
    ],
  },
  {
    groupKey: 'groupAuditSecurity',
    items: [
      { labelKey: 'auditExplorer', path: 'system-audit', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'audit', path: 'audit', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'activityLog', path: 'activity-log', icon: <Activity className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'sessions', path: 'sessions', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'financialAudit', path: 'audit/financial', icon: <Wallet className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'patientAccessAudit', path: 'audit/patient-access', icon: <Users className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'suspiciousActivities', path: 'audit/suspicious', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'exportHistory', path: 'audit/exports', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'safetyOverrideAudit', path: 'audit/safety-overrides', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
      { labelKey: 'offlineSyncReview', path: 'audit/offline-sync', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'audit:read' },
    ],
  },
  {
    groupKey: 'groupSettings',
    items: [
      { labelKey: 'settings', path: 'settings', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'setupWizard', path: 'setup', icon: <Settings className="w-4.5 h-4.5" /> },
      { labelKey: 'billingSettings', path: 'settings/billing', icon: <Receipt className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'emailSettings', path: 'settings/email', icon: <MessageSquare className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'appointmentSettings', path: 'settings/appointments', icon: <CalendarDays className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'securitySettings', path: 'settings/security', icon: <Shield className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'backupSettings', path: 'settings/backup', icon: <RefreshCw className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'importExportSettings', path: 'settings/import-export', icon: <ArrowRightLeft className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'approvalPolicies', path: 'settings/approval-policies', icon: <ShieldCheck className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'discountSettings', path: 'settings/discounts', icon: <Percent className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'notificationSettings', path: 'settings/notifications', icon: <MessageSquare className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'escalationRules', path: 'settings/escalation-rules', icon: <ShieldAlert className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'hospitalProfile', path: 'settings/hospital-profile', icon: <Building2 className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'paymentMethods', path: 'settings/payments', icon: <CreditCard className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'printLayouts', path: 'print-templates', icon: <Printer className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'smsEmail', path: 'settings/sms', icon: <MessageSquare className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'systemPreferences', path: 'settings/preferences', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'website', path: 'website', icon: <Building2 className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'softwareModules', path: 'software-modules', icon: <Settings className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'multiBranch', path: 'multi-branch', icon: <Building2 className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'mfa', path: 'mfa', icon: <Shield className="w-4.5 h-4.5" /> },
      { labelKey: 'printTemplates', path: 'print-templates', icon: <Printer className="w-4.5 h-4.5" />, requiredPermission: 'settings:read' },
      { labelKey: 'whatsapp', path: 'whatsapp', icon: <MessageSquare className="w-4.5 h-4.5" /> },
      { labelKey: 'inbox', path: 'inbox', icon: <MessageSquare className="w-4.5 h-4.5" /> },
      { labelKey: 'helpdesk', path: 'helpdesk', icon: <MessageSquare className="w-4.5 h-4.5" /> },
      { labelKey: 'marketingReferral', path: 'marketing-referral', icon: <ArrowRightLeft className="w-4.5 h-4.5" /> },
      { labelKey: 'qualityKpi', path: 'quality-kpi', icon: <BarChart3 className="w-4.5 h-4.5" /> },
      { labelKey: 'helpCenter', path: 'help', icon: <MessageSquare className="w-4.5 h-4.5" /> },
    ],
  },
];

export const adminIpdMonitoringRouteHints = [
  { labelKey: 'admissionsOverview', path: 'admissions' },
  { labelKey: 'ipBilling', path: 'ip-billing' },
  { labelKey: 'ipdReports', path: 'ipd-reports' },
] as const;


export const adminInventoryConsumptionRouteHints = [
  { labelKey: 'inventoryConsumptionRules', path: 'inventory/consumption-rules', requiredPermission: 'inventory:write' },
  { labelKey: 'inventoryConsumptionQueue', path: 'inventory/consumption-queue', requiredPermission: 'inventory:consume' },
  { labelKey: 'inventoryConsumptionExceptions', path: 'inventory/consumption-exceptions', requiredPermission: 'inventory:consume' },
] as const;

