-- Migration 0098: Terminology Seed Data (ICD-11 MMS + LOINC + SNOMED)
-- Seeds global terminology tables with BD-common codes

-- ============================================================
-- PART 1: ICD-11 MMS Codes (~560 Bangladesh-common conditions)
-- ============================================================
INSERT INTO catalog_icd11_mms (code, title) VALUES
  -- === INFECTIONS (01) ===
  ('1A00', 'Cholera'),
  ('1A01', 'Typhoid and paratyphoid fevers'),
  ('1A01.0', 'Typhoid fever'),
  ('1A02', 'Shigellosis'),
  ('1A03', 'Escherichia coli intestinal infection'),
  ('1A04', 'Campylobacter enteritis'),
  ('1A07', 'Amoebiasis'),
  ('1A40', 'Gastroenteritis and colitis of infectious origin'),
  ('1B10', 'Tuberculosis of respiratory system'),
  ('1B11', 'Tuberculosis of nervous system'),
  ('1B12', 'Tuberculosis of other organs'),
  ('1B13', 'Miliary tuberculosis'),
  ('1G91', 'Latent tuberculosis infection'),
  ('1B20', 'Leprosy'),
  ('1B50', 'Leptospirosis'),
  ('1B70', 'Lyme disease'),
  ('1B92', 'Scrub typhus'),
  ('1C10', 'Poliomyelitis'),
  ('1C11', 'Measles'),
  ('1C12', 'Rubella'),
  ('1C13', 'Pertussis'),
  ('1C14', 'Mumps'),
  ('1C15', 'Tetanus'),
  ('1C16', 'Diphtheria'),
  ('1C1F', 'Varicella'),
  ('1C40', 'Syphilis'),
  ('1A60', 'Gonorrhoea'),
  ('1A61', 'Chlamydial infection'),
  ('1A62', 'Trichomoniasis'),
  ('1C42', 'Human papillomavirus infection'),
  ('1C50', 'Human immunodeficiency virus disease without associated condition'),
  ('1C51', 'Human immunodeficiency virus disease with associated conditions'),
  ('1C60', 'Herpes simplex infections'),
  ('1C61', 'Herpes zoster'),
  ('1C62', 'Epstein-Barr virus infection'),
  ('1C62.1', 'Cytomegalovirus infection'),
  ('1C80', 'Dengue virus disease'),
  ('1C80.0', 'Dengue without warning signs'),
  ('1C80.1', 'Dengue with warning signs'),
  ('1C81', 'Severe dengue'),
  ('1C82', 'Chikungunya virus disease'),
  ('1C83', 'Zika virus disease'),
  ('1C84', 'Japanese encephalitis'),
  ('1C90', 'Yellow fever'),
  ('1D00', 'Rabies'),
  ('1D01', 'Ebola virus disease'),
  ('1D61', 'Nipah virus disease'),
  ('1D80', 'Influenza'),
  ('1D81', 'Avian influenza'),
  ('1D84', 'COVID-19'),
  ('1E31', 'Tinea pedis'),
  ('1E32', 'Tinea corporis'),
  ('1E33', 'Tinea cruris'),
  ('1E34', 'Tinea capitis'),
  ('1E35', 'Pityriasis versicolor'),
  ('1E50', 'Aspergillosis'),
  ('1E51', 'Histoplasmosis'),
  ('1F20', 'Cryptococcosis'),
  ('1F24', 'Candidiasis'),
  ('1F40', 'Malaria'),
  ('1F41', 'Plasmodium falciparum malaria'),
  ('1F42', 'Plasmodium vivax malaria'),
  ('1F54', 'Visceral leishmaniasis (Kala-azar)'),
  ('1F55', 'Cutaneous leishmaniasis'),
  ('1F64', 'Toxoplasmosis'),
  ('1G00', 'Ascariasis'),
  ('1G01', 'Hookworm infections'),
  ('1G02', 'Strongyloidiasis'),
  ('1G03', 'Trichuriasis'),
  ('1G04', 'Enterobiasis'),
  ('1G40', 'Schistosomiasis'),
  ('1G41', 'Lymphatic filariasis'),
  ('1A80', 'Acute hepatitis A'),
  ('1A81', 'Acute hepatitis B'),
  ('1A82', 'Acute hepatitis C'),
  ('1A83', 'Acute hepatitis E'),
  ('1A05', 'Salmonella enteritis'),
  ('1A06', 'Viral intestinal infection'),
  ('1A08', 'Intestinal infection due to other specified organisms'),
  ('1F21', 'Oral candidiasis'),
  
  -- === NEOPLASMS (02) ===
  ('2A20', 'Malignant neoplasm of stomach'),
  ('2A31', 'Malignant neoplasm of colon'),
  ('2A32', 'Malignant neoplasm of rectum'),
  ('2B30', 'Malignant neoplasm of liver'),
  ('2C21', 'Malignant neoplasm of bronchus or lung'),
  ('2C82', 'Malignant neoplasm of breast'),
  ('2C90', 'Malignant neoplasm of cervix uteri'),
  ('2C93', 'Malignant neoplasm of ovary'),
  ('2D00', 'Malignant neoplasm of prostate'),
  ('2D10', 'Malignant neoplasm of testis'),
  ('2C3X', 'Melanoma of skin'),
  ('2A83', 'Hodgkin lymphoma'),
  ('2B32', 'Leukaemia'),
  ('2F30', 'Leiomyoma of uterus'),
  ('2F71', 'Fibroadenoma of breast'),
  ('2B31', 'Malignant neoplasm of intrahepatic bile ducts'),
  ('2B60', 'Malignant neoplasm of pancreas'),
  ('2D40', 'Malignant neoplasm of kidney'),
  ('2D42', 'Malignant neoplasm of bladder'),
  ('2D81', 'Malignant neoplasm of thyroid gland'),
  ('2A00', 'Malignant neoplasm of lip'),
  ('2A02', 'Malignant neoplasm of tongue'),
  ('2A21', 'Malignant neoplasm of oesophagus'),
  ('2A85', 'Non-Hodgkin lymphoma'),
  ('2B20', 'Multiple myeloma'),
  ('2E61', 'Benign neoplasm of colon'),
  ('2F35', 'Benign ovarian cyst'),
  ('2F40', 'Benign neoplasm of prostate'),
  ('2F70', 'Benign neoplasm of breast'),
  ('2E80', 'Benign neoplasm of skin'),
  ('2E83', 'Haemangioma'),

  -- === DISEASES OF BLOOD (03) ===
  ('3A00', 'Iron deficiency anaemia'),
  ('3A01', 'Vitamin B12 deficiency anaemia'),
  ('3A52.0', 'Thalassaemia major'),
  ('3A52.1', 'Thalassaemia minor'),
  ('3A51', 'Sickle-cell disorders'),
  ('3B62', 'Idiopathic thrombocytopenic purpura'),
  ('3B80', 'Haemophilia A'),
  ('3A02', 'Folate deficiency anaemia'),
  ('3A52', 'Thalassaemia'),
  ('3A70', 'Aplastic anaemia'),
  ('3A90', 'Haemolytic anaemia'),
  ('3B60', 'Thrombocytopenia'),
  ('3B81', 'Haemophilia B'),

  -- === IMMUNE SYSTEM (04) ===
  ('4A60', 'Allergic rhinitis'),
  ('4A84', 'Anaphylaxis'),
  ('4B20', 'Sarcoidosis'),
  ('4A80', 'Food allergy'),
  ('4A85', 'Allergic contact dermatitis'),
  ('4A87', 'Drug allergy'),
  ('4A40', 'Immunodeficiency disorders'),
  ('4A00', 'Primary immunodeficiencies'),

  -- === ENDOCRINE / METABOLIC (05) ===
  ('5A00', 'Hypothyroidism'),
  ('5A01', 'Hyperthyroidism'),
  ('5A03', 'Simple goitre'),
  ('5A10', 'Type 1 diabetes mellitus'),
  ('5A11', 'Type 2 diabetes mellitus'),
  ('5A11.0', 'Type 2 diabetes mellitus without complications'),
  ('5A11.1', 'Type 2 diabetes mellitus with complications'),
  ('5A11.2', 'Diabetic retinopathy'),
  ('5A11.3', 'Diabetic nephropathy'),
  ('5A20', 'Hypoglycaemia'),
  ('5B54', 'Obesity'),
  ('5B5X', 'Malnutrition'),
  ('5B50', 'Kwashiorkor'),
  ('5B51', 'Marasmus'),
  ('5C50', 'Vitamin A deficiency'),
  ('5C54', 'Vitamin D deficiency'),
  ('5A02', 'Thyroiditis'),
  ('5A14', 'Diabetes mellitus, type unspecified'),
  ('5A12', 'Malnutrition-related diabetes mellitus'),
  ('5A40', 'Hypoparathyroidism'),
  ('5A41', 'Hyperparathyroidism'),
  ('5A60', 'Cushing syndrome'),
  ('5B55', 'Overweight'),
  ('5B81', 'Hypercholesterolaemia'),
  ('5B82', 'Hypertriglyceridaemia'),
  ('5B83', 'Mixed hyperlipidaemia'),
  ('5C58', 'Thiamine deficiency'),
  ('5B52', 'Severe acute malnutrition'),
  ('5B53', 'Moderate acute malnutrition'),
  ('5C53', 'Scurvy'),
  ('5C55', 'Vitamin E deficiency'),
  ('5C56', 'Vitamin K deficiency'),
  ('5A21', 'Hyperinsulinaemia'),
  ('5B80', 'Hypercholesterolaemia, familial'),
  ('5A04', 'Thyroid nodule'),
  ('5A61', 'Addison disease'),
  ('5A62', 'Hypopituitarism'),
  ('5A63', 'Hyperprolactinaemia'),

  -- === MENTAL / BEHAVIOURAL (06) ===
  ('6A00', 'Schizophrenia'),
  ('6A20', 'Bipolar type I disorder'),
  ('6A70', 'Single episode depressive disorder'),
  ('6B00', 'Generalised anxiety disorder'),
  ('6B40', 'Post-traumatic stress disorder'),
  ('6B61', 'Conversion disorder'),
  ('6C40', 'Disorders due to use of alcohol'),
  ('6A02', 'Schizoaffective disorder'),
  ('6A21', 'Bipolar type II disorder'),
  ('6A71', 'Recurrent depressive disorder'),
  ('6B01', 'Panic disorder'),
  ('6B03', 'Agoraphobia'),
  ('6B04', 'Social anxiety disorder'),
  ('6B20', 'Obsessive-compulsive disorder'),
  ('6B41', 'Complex post-traumatic stress disorder'),
  ('6B60', 'Dissociative neurological symptom disorder'),
  ('6C41', 'Disorders due to use of cannabis'),
  ('6C43', 'Disorders due to use of opioids'),
  ('6C44', 'Disorders due to use of nicotine'),
  ('6D10', 'Personality disorder'),
  ('6A05', 'Delusional disorder'),
  ('6C00', 'Anorexia nervosa'),
  ('6C01', 'Bulimia nervosa'),
  ('6A40', 'Attention deficit hyperactivity disorder'),
  ('6A02.0', 'Autism spectrum disorder'),
  ('6B62', 'Illness anxiety disorder'),
  ('6C20', 'Disorders due to use of cocaine'),
  ('6B02', 'Specific phobia'),
  ('6C42', 'Disorders due to use of sedatives'),
  ('6C45', 'Disorders due to use of volatile solvents'),
  ('6D11', 'Avoidant personality disorder'),
  ('6D12', 'Borderline personality disorder'),

  -- === SLEEP/WAKE (07) ===
  ('7A00', 'Insomnia'),
  ('7A40', 'Sleep apnoea'),
  ('7A20', 'Hypersomnolence'),
  ('7A60', 'Narcolepsy'),
  ('7B00', 'Restless legs syndrome'),

  -- === NEUROLOGICAL (08) ===
  ('8A0X', 'Migraine'),
  ('8A00', 'Epilepsy'),
  ('8B00', 'Alzheimer disease'),
  ('8B80', 'Transient ischaemic attack'),
  ('8B92', 'Stroke, not specified as ischaemic or haemorrhagic'),
  ('8C00', 'Bacterial meningitis'),
  ('8C03', 'Viral meningitis'),
  ('8D61', 'Guillain-Barre syndrome'),
  ('8D20', 'Cerebral palsy'),
  ('8A0X.0', 'Migraine without aura'),
  ('8A0X.1', 'Migraine with aura'),
  ('8A02', 'Tension-type headache'),
  ('8A03', 'Cluster headache'),
  ('8A01', 'Status epilepticus'),
  ('8B01', 'Vascular dementia'),
  ('8B20', 'Parkinson disease'),
  ('8B40', 'Multiple sclerosis'),
  ('8B90', 'Cerebral infarction'),
  ('8B91', 'Intracerebral haemorrhage'),
  ('8C01', 'Meningitis'),
  ('8C02', 'Encephalitis'),
  ('8C60', 'Bell palsy'),
  ('8C61', 'Trigeminal neuralgia'),
  ('8C62', 'Carpal tunnel syndrome'),
  ('8D60', 'Neuropathy, unspecified'),
  ('8B02', 'Dementia with Lewy bodies'),
  ('8B03', 'Frontotemporal dementia'),
  ('8D21', 'Hemiplegia'),
  ('8D22', 'Paraplegia'),
  ('8D23', 'Tetraplegia'),
  ('8B41', 'Neuromyelitis optica'),
  ('8C63', 'Diabetic neuropathy'),

  -- === VISUAL (09) ===
  ('9A80', 'Conjunctivitis'),
  ('9B10', 'Age-related cataract'),
  ('9B30', 'Glaucoma'),
  ('9C20', 'Myopia'),
  ('9A00', 'Blepharitis'),
  ('9A01', 'Hordeolum'),
  ('9A02', 'Chalazion'),
  ('9A81', 'Pterygium'),
  ('9B60', 'Macular degeneration'),
  ('9C21', 'Hypermetropia'),
  ('9C22', 'Astigmatism'),
  ('9C23', 'Presbyopia'),
  ('9C40', 'Strabismus'),
  ('9D00', 'Blindness'),
  ('9A10', 'Dry eye syndrome'),
  ('9B11', 'Congenital cataract'),
  ('9B31', 'Open-angle glaucoma'),
  ('9B32', 'Angle-closure glaucoma'),
  ('9C41', 'Amblyopia'),
  ('9A11', 'Corneal ulcer'),

  -- === EAR (10) ===
  ('AB10', 'Otitis media'),
  ('AC00', 'Hearing loss'),
  ('AA00', 'Otitis externa'),
  ('AB30', 'Meniere disease'),
  ('AB31', 'Tinnitus'),
  ('AB32', 'Vertigo'),
  ('AB1X', 'Mastoiditis'),
  ('AA01', 'Otitis media with effusion'),
  ('AB11', 'Cholesteatoma'),
  ('AC01', 'Sensorineural hearing loss'),
  ('AC02', 'Conductive hearing loss'),

  -- === CIRCULATORY (11) ===
  ('BA00', 'Essential hypertension'),
  ('BA04', 'Hypertensive crisis'),
  ('BA41', 'Acute myocardial infarction'),
  ('BA81', 'Heart failure'),
  ('BB01', 'Cor pulmonale'),
  ('BB40', 'Rheumatic heart disease'),
  ('BC02', 'Myocarditis'),
  ('BB41', 'Rheumatic mitral valve disease'),
  ('BA01', 'Secondary hypertension'),
  ('BA42', 'Subsequent myocardial infarction'),
  ('BD11', 'Ischaemic heart disease'),
  ('BA43', 'Angina pectoris'),
  ('BA80', 'Left ventricular failure'),
  ('BC40', 'Atrial fibrillation'),
  ('BC41', 'Atrial flutter'),
  ('BC42', 'Ventricular tachycardia'),
  ('BC00', 'Pericarditis'),
  ('BC01', 'Endocarditis'),
  ('BD30', 'Aortic aneurysm'),
  ('BD50', 'Varicose veins of lower extremities'),
  ('BD51', 'Deep vein thrombosis'),
  ('BD70', 'Pulmonary embolism'),
  ('BD71', 'Haemorrhoids'),
  ('BD40', 'Peripheral arterial disease'),
  ('BA40', 'Acute coronary syndrome'),
  ('BB42', 'Rheumatic aortic valve disease'),
  ('BB43', 'Rheumatic tricuspid valve disease'),
  ('BC43', 'Bradycardia'),
  ('BD31', 'Thoracic aortic aneurysm'),
  ('BD32', 'Abdominal aortic aneurysm'),
  ('BD52', 'Phlebitis and thrombophlebitis'),

  -- === RESPIRATORY (12) ===
  ('CA00', 'Acute upper respiratory infections'),
  ('CA01', 'Acute tonsillitis'),
  ('CA40', 'Pneumonia'),
  ('CA23', 'Asthma'),
  ('CA22', 'Chronic obstructive pulmonary disease'),
  ('CA82', 'Silicosis'),
  ('CA02', 'Acute pharyngitis'),
  ('CA03', 'Acute laryngitis'),
  ('CA04', 'Acute sinusitis'),
  ('CA42', 'Acute bronchitis'),
  ('CA24', 'Bronchiectasis'),
  ('CB80', 'Pleural effusion'),
  ('CB40', 'Pneumothorax'),
  ('CA80', 'Pulmonary fibrosis'),
  ('CA83', 'Pneumoconiosis'),
  ('CA05', 'Croup'),
  ('CA81', 'Asbestosis'),
  ('CA84', 'Hypersensitivity pneumonitis'),
  ('CB41', 'Haemothorax'),
  ('CA06', 'Acute epiglottitis'),
  ('CA25', 'Emphysema'),

  -- === DIGESTIVE (13) ===
  ('DA00', 'Dental caries'),
  ('DA20', 'Peptic ulcer disease'),
  ('DA24', 'Gastro-oesophageal reflux disease'),
  ('DB30', 'Acute appendicitis'),
  ('DB70', 'Haemorrhoids'),
  ('DC31', 'Cholecystitis'),
  ('DC11', 'Liver cirrhosis'),
  ('DC71', 'Fatty liver disease'),
  ('DA01', 'Gingivitis'),
  ('DA02', 'Periodontitis'),
  ('DA21', 'Gastric ulcer'),
  ('DA22', 'Duodenal ulcer'),
  ('DA25', 'Dyspepsia'),
  ('DB31', 'Other appendicitis'),
  ('DD90', 'Irritable bowel syndrome'),
  ('DC32', 'Cholelithiasis'),
  ('DB50', 'Crohn disease'),
  ('DB51', 'Ulcerative colitis'),
  ('DB10', 'Inguinal hernia'),
  ('DB11', 'Femoral hernia'),
  ('DB12', 'Umbilical hernia'),
  ('DC10', 'Alcoholic liver disease'),
  ('DB40', 'Acute pancreatitis'),
  ('DB41', 'Chronic pancreatitis'),
  ('DA40', 'Gastroenteritis'),
  ('DC12', 'Toxic liver disease'),
  ('DC13', 'Hepatic failure'),
  ('DB32', 'Peritonitis'),
  ('DB33', 'Intestinal obstruction'),
  ('DB52', 'Coeliac disease'),
  ('DB53', 'Radiation colitis'),
  ('DA23', 'Gastrojejunal ulcer'),
  ('DA26', 'Gastritis'),
  ('DA27', 'Duodenitis'),
  ('DA60', 'Acute appendicitis with peritonitis'),
  ('DA61', 'Acute appendicitis without peritonitis'),
  ('DB80', 'Anal fissure'),
  ('DB81', 'Anal fistula'),
  ('DC33', 'Cholangitis'),
  ('DC34', 'Gallstone pancreatitis'),

  -- === SKIN (14) ===
  ('EA90', 'Acne'),
  ('EA91', 'Eczema'),
  ('EA80', 'Psoriasis'),
  ('EF00', 'Scabies'),
  ('EE00', 'Cellulitis'),
  ('ED30', 'Urticaria'),
  ('EE01', 'Impetigo'),
  ('EA40', 'Alopecia'),
  ('EA41', 'Alopecia areata'),
  ('EB00', 'Vitiligo'),
  ('EE30', 'Warts'),
  ('EF01', 'Pediculosis'),
  ('EH60', 'Contact dermatitis'),
  ('EB80', 'Seborrhoeic dermatitis'),
  ('ED31', 'Angioedema'),
  ('EA92', 'Rosacea'),
  ('EF02', 'Tungiasis'),
  ('EA81', 'Lichen planus'),
  ('EB01', 'Melasma'),
  ('EB02', 'Albinism'),
  ('EE02', 'Erysipelas'),

  -- === MUSCULOSKELETAL (15) ===
  ('FA00', 'Osteoarthritis of knee'),
  ('FA20', 'Rheumatoid arthritis'),
  ('FA54', 'Gout'),
  ('FB10', 'Sciatica'),
  ('FA01', 'Osteoarthritis of hip'),
  ('FB50', 'Osteoporosis'),
  ('FB80', 'Scoliosis'),
  ('FB81', 'Kyphosis'),
  ('FC00', 'Systemic lupus erythematosus'),
  ('FA22', 'Ankylosing spondylitis'),
  ('FC10', 'Sjogren syndrome'),
  ('FA21', 'Juvenile idiopathic arthritis'),
  ('FA23', 'Reactive arthritis'),
  ('FA24', 'Psoriatic arthritis'),
  ('FB51', 'Osteomalacia'),
  ('FC01', 'Systemic sclerosis'),
  ('FC02', 'Dermatomyositis'),
  ('FB11', 'Spinal stenosis'),
  ('FB12', 'Spondylolisthesis'),
  ('ME85', 'Fibromyalgia'),

  -- === GENITOURINARY (16) ===
  ('GC00', 'Acute cystitis'),
  ('GB90', 'Chronic kidney disease'),
  ('GC70', 'Benign prostatic hyperplasia'),
  ('GA10', 'Endometriosis'),
  ('GA11', 'Pelvic inflammatory disease'),
  ('GC81', 'Vesicovaginal fistula'),
  ('GC01', 'Acute pyelonephritis'),
  ('GC08', 'Urinary tract infection, site not specified'),
  ('GB91', 'Acute kidney injury'),
  ('GC40', 'Nephrolithiasis'),
  ('GA30', 'Polycystic ovary syndrome'),
  ('GA31', 'Menstrual cycle irregularities'),
  ('GA32', 'Dysmenorrhoea'),
  ('GA33', 'Amenorrhoea'),
  ('GA34', 'Menorrhagia'),
  ('GA40', 'Vaginitis'),
  ('GA41', 'Vulvitis'),
  ('GB00', 'Erectile dysfunction'),
  ('GC82', 'Breast abscess'),
  ('GA12', 'Cervicitis'),
  ('GA13', 'Vaginal discharge'),
  ('GB41', 'Gestational thyroid dysfunction'),
  ('GB92', 'End-stage renal disease'),
  ('GC41', 'Ureterolithiasis'),
  ('GC42', 'Cystolithiasis'),
  ('GB01', 'Premature ejaculation'),
  ('GB02', 'Male infertility'),

  -- === PREGNANCY/CHILDBIRTH (18) ===
  ('GB40', 'Gestational diabetes'),
  ('JA00', 'Eclampsia'),
  ('JA01', 'Pre-eclampsia'),
  ('JA40', 'Postpartum haemorrhage'),
  ('JA60', 'Ectopic pregnancy'),
  ('KA81', 'Neonatal jaundice'),
  ('KA20', 'Birth asphyxia'),
  ('KA60', 'Neonatal sepsis'),
  ('JA02', 'Gestational hypertension'),
  ('JA20', 'Maternal care for single spontaneous delivery'),
  ('JA21', 'Maternal care for caesarean delivery'),
  ('JA61', 'Spontaneous abortion'),
  ('JA62', 'Medical abortion'),
  ('JA80', 'Hyperemesis gravidarum'),
  ('JB00', 'Placenta praevia'),
  ('JB01', 'Placental abruption'),
  ('JB20', 'Premature rupture of membranes'),
  ('JB21', 'Preterm labour'),
  ('JB40', 'Fetal distress'),
  ('JB60', 'Puerperal sepsis'),
  ('JA41', 'Delayed or secondary postpartum haemorrhage'),
  ('JA63', 'Missed abortion'),
  ('JA64', 'Incomplete abortion'),
  ('JA65', 'Complications following abortion'),
  ('JB02', 'Vasa praevia'),
  ('JB61', 'Postpartum depression'),
  ('JB62', 'Postpartum psychosis'),
  ('JA22', 'Maternal care for instrumental delivery'),
  ('JA23', 'Maternal care for breech delivery'),
  ('JA24', 'Maternal care for multiple delivery'),
  ('KA21', 'Preterm newborn'),
  ('KA22', 'Low birth weight newborn'),
  ('KA23', 'Extremely low birth weight newborn'),
  ('KA61', 'Congenital pneumonia'),
  ('KA62', 'Omphalitis of newborn'),
  ('LA50', 'Cleft lip or cleft palate'),
  ('LD40', 'Down syndrome'),
  ('KB00', 'Neonatal hypoglycaemia'),
  ('KA80', 'Neonatal aspiration syndromes'),

  -- === SYMPTOMS/SIGNS (21) ===
  ('MB43', 'Unspecified fever'),
  ('MG42', 'Headache'),
  ('ME05', 'Abdominal pain'),
  ('MG20', 'Fatigue'),
  ('MD10', 'Cough'),
  ('MF50', 'Nausea'),
  ('MF51', 'Vomiting'),
  ('MF54', 'Diarrhoea'),
  ('MF55', 'Constipation'),
  ('MG30', 'Chronic pain'),
  ('ME84', 'Low back pain'),
  ('ME82', 'Neck pain'),
  ('ME80', 'Joint pain'),
  ('MD00', 'Dyspnoea'),
  ('MB40', 'Chest pain'),
  ('MB41', 'Palpitations'),
  ('MD40', 'Syncope'),
  ('MC00', 'Dizziness'),
  ('MD42', 'Convulsions'),
  ('MD80', 'Oedema'),
  ('MG80', 'Weight loss'),
  ('MG81', 'Weight gain'),
  ('MA00', 'Dysuria'),
  ('MA01', 'Haematuria'),
  ('MB80', 'Jaundice'),
  ('ME20', 'Visual disturbance'),
  ('MC40', 'Tremor'),
  ('ME01', 'Chest pain on breathing'),
  ('MC01', 'Fainting'),
  ('MF52', 'Heartburn'),
  ('MF53', 'Dysphagia'),
  ('MA02', 'Polyuria'),
  ('MB81', 'Cyanosis'),
  ('MC41', 'Ataxia'),
  ('ME21', 'Diplopia'),

  -- === INJURIES AND TOXICOLOGY (22+) ===
  ('NC32', 'Fracture of radius'),
  ('NF80', 'Animal bite'),
  ('NF81', 'Snake bite'),
  ('NE60', 'Toxic effect of arsenic and its compounds'),
  ('NE64', 'Toxic effect of organophosphate and carbamate insecticides'),
  ('PA00', 'Road traffic crush injuries'),
  ('NC33', 'Fracture of ulna'),
  ('ND31', 'Fracture of femur'),
  ('ND32', 'Fracture of tibia'),
  ('NF03', 'Burn of first degree'),
  ('NF04', 'Burn of second degree'),
  ('NF05', 'Burn of third degree'),
  ('NB40', 'Concussion'),
  ('NE40', 'Sprain of ankle'),
  ('NE41', 'Sprain of wrist'),
  ('NE42', 'Sprain of knee'),
  ('ND80', 'Dislocation of shoulder'),
  ('NE61', 'Toxic effect of lead and its compounds'),
  ('NE62', 'Toxic effect of mercury and its compounds'),
  ('NE63', 'Toxic effect of carbon monoxide'),
  ('NE65', 'Toxic effect of rodenticides'),
  ('NE66', 'Toxic effect of snake venom'),
  ('NE67', 'Toxic effect of scorpion venom')
ON CONFLICT(code) DO NOTHING;

-- ============================================================
-- PART 2: LOINC Codes (~80 common lab tests + vital signs)
-- ============================================================
INSERT INTO catalog_loinc (loinc_num, component, long_common_name, class, units) VALUES
  -- Vital Signs (matching existing mappers.ts constants)
  ('8480-6',  'Systolic blood pressure',  'Systolic blood pressure',               'BP',     'mmHg'),
  ('8462-4',  'Diastolic blood pressure', 'Diastolic blood pressure',              'BP',     'mmHg'),
  ('8867-4',  'Heart rate',               'Heart rate',                            'PANEL.VS', 'beats/min'),
  ('8310-5',  'Body temperature',         'Body temperature',                      'PANEL.VS', '°C'),
  ('2708-6',  'Oxygen saturation',        'Oxygen saturation in Arterial blood',   'PANEL.VS', '%'),
  ('9279-1',  'Respiratory rate',         'Respiratory rate',                      'PANEL.VS', 'breaths/min'),
  ('29463-7', 'Body weight',              'Body weight',                           'PANEL.VS', 'kg'),
  ('85354-9', 'Blood pressure panel',     'Blood pressure panel',                  'BP',     ''),
  ('8302-2',  'Body height',              'Body height',                           'PANEL.VS', 'cm'),
  ('39156-5', 'Body mass index',          'Body mass index (BMI)',                 'PANEL.VS', 'kg/m2'),

  -- CBC (Complete Blood Count)
  ('6690-2',  'Leukocytes',           'Leukocytes [#/volume] in Blood',                  'HEM/BC', '10*3/uL'),
  ('789-8',   'Erythrocytes',         'Erythrocytes [#/volume] in Blood',                'HEM/BC', '10*6/uL'),
  ('718-7',   'Hemoglobin',           'Hemoglobin [Mass/volume] in Blood',               'HEM/BC', 'g/dL'),
  ('4544-3',  'Hematocrit',           'Hematocrit [Volume Fraction] of Blood',           'HEM/BC', '%'),
  ('787-2',   'MCV',                  'MCV [Entitic volume]',                            'HEM/BC', 'fL'),
  ('785-6',   'MCH',                  'MCH [Entitic mass]',                              'HEM/BC', 'pg'),
  ('786-4',   'MCHC',                 'MCHC [Mass/volume]',                              'HEM/BC', 'g/dL'),
  ('777-3',   'Platelets',            'Platelets [#/volume] in Blood',                   'HEM/BC', '10*3/uL'),
  ('26515-7', 'Platelet count',       'Platelets [#/volume] in Blood by Automated count','HEM/BC', '10*3/uL'),
  ('770-8',   'Neutrophils %',        'Neutrophils/100 leukocytes in Blood',             'HEM/BC', '%'),
  ('736-9',   'Lymphocytes %',        'Lymphocytes/100 leukocytes in Blood',             'HEM/BC', '%'),
  ('5905-5',  'Monocytes %',          'Monocytes/100 leukocytes in Blood',               'HEM/BC', '%'),
  ('713-8',   'Eosinophils %',        'Eosinophils/100 leukocytes in Blood',             'HEM/BC', '%'),
  ('706-2',   'Basophils %',          'Basophils/100 leukocytes in Blood',               'HEM/BC', '%'),
  ('4679-7',  'Reticulocytes %',      'Reticulocytes/100 erythrocytes in Blood',         'HEM/BC', '%'),
  ('30385-9', 'ESR',                  'Erythrocyte sedimentation rate',                  'HEM/BC', 'mm/h'),

  -- Basic Metabolic Panel
  ('2345-7',  'Glucose',              'Glucose [Mass/volume] in Serum or Plasma',        'CHEM', 'mg/dL'),
  ('2160-0',  'Creatinine',           'Creatinine [Mass/volume] in Serum or Plasma',     'CHEM', 'mg/dL'),
  ('3094-0',  'BUN',                  'Urea nitrogen [Mass/volume] in Serum or Plasma',  'CHEM', 'mg/dL'),
  ('2951-2',  'Sodium',               'Sodium [Moles/volume] in Serum or Plasma',        'CHEM', 'mmol/L'),
  ('2823-3',  'Potassium',            'Potassium [Moles/volume] in Serum or Plasma',     'CHEM', 'mmol/L'),
  ('2075-0',  'Chloride',             'Chloride [Moles/volume] in Serum or Plasma',      'CHEM', 'mmol/L'),
  ('2028-9',  'CO2',                  'Carbon dioxide [Moles/volume] in Serum or Plasma','CHEM', 'mmol/L'),
  ('17861-6', 'Calcium',              'Calcium [Mass/volume] in Serum or Plasma',        'CHEM', 'mg/dL'),
  ('2777-1',  'Phosphate',            'Phosphate [Mass/volume] in Serum or Plasma',      'CHEM', 'mg/dL'),
  ('2532-0',  'LDH',                  'Lactate dehydrogenase [Enzymatic activity/volume] in Serum','CHEM','U/L'),
  ('2798-7',  'Uric acid',            'Urate [Mass/volume] in Serum or Plasma',          'CHEM', 'mg/dL'),

  -- Liver Panel
  ('1742-6',  'ALT',                  'Alanine aminotransferase [Enzymatic activity/volume] in Serum','CHEM','U/L'),
  ('1920-8',  'AST',                  'Aspartate aminotransferase [Enzymatic activity/volume] in Serum','CHEM','U/L'),
  ('6768-6',  'ALP',                  'Alkaline phosphatase [Enzymatic activity/volume] in Serum','CHEM','U/L'),
  ('1975-2',  'Total Bilirubin',      'Bilirubin.total [Mass/volume] in Serum or Plasma','CHEM', 'mg/dL'),
  ('1968-7',  'Direct Bilirubin',     'Bilirubin.direct [Mass/volume] in Serum or Plasma','CHEM','mg/dL'),
  ('1751-7',  'Albumin',              'Albumin [Mass/volume] in Serum or Plasma',        'CHEM', 'g/dL'),
  ('2885-2',  'Total Protein',        'Protein [Mass/volume] in Serum or Plasma',        'CHEM', 'g/dL'),
  ('2324-2',  'GGT',                  'Gamma glutamyl transferase [Enzymatic activity/volume] in Serum','CHEM','U/L'),

  -- Lipid Panel
  ('2093-3',  'Total Cholesterol',    'Cholesterol [Mass/volume] in Serum or Plasma',    'CHEM', 'mg/dL'),
  ('2571-8',  'Triglycerides',        'Triglyceride [Mass/volume] in Serum or Plasma',   'CHEM', 'mg/dL'),
  ('2085-9',  'HDL Cholesterol',      'Cholesterol in HDL [Mass/volume] in Serum',       'CHEM', 'mg/dL'),
  ('2089-1',  'LDL Cholesterol',      'Cholesterol in LDL [Mass/volume] in Serum',       'CHEM', 'mg/dL'),

  -- Diabetes / Endocrine
  ('4548-4',  'HbA1c',                'Hemoglobin A1c/Hemoglobin.total in Blood',        'CHEM', '%'),
  ('1558-6',  'Fasting Glucose',      'Fasting glucose [Mass/volume] in Serum or Plasma','CHEM', 'mg/dL'),
  ('11557-6', 'TSH',                  'Thyrotropin [Units/volume] in Serum or Plasma',   'CHEM', 'mIU/L'),
  ('3016-3',  'Free T4',              'Thyroxine (T4) free [Mass/volume] in Serum',      'CHEM', 'ng/dL'),
  ('3053-6',  'Free T3',              'Triiodothyronine (T3) free [Mass/volume] in Serum','CHEM','pg/mL'),

  -- Coagulation
  ('5902-2',  'PT',                   'Prothrombin time (PT)',                            'COAG', 'seconds'),
  ('6301-6',  'INR',                  'INR in Platelet poor plasma',                     'COAG', '{ratio}'),
  ('3173-2',  'aPTT',                 'Activated partial thromboplastin time',            'COAG', 'seconds'),
  ('30313-1', 'D-dimer',              'Fibrin D-dimer [Mass/volume] in Platelet poor plasma','COAG','mg/L'),

  -- Urinalysis
  ('5811-5',  'Specific gravity (Urine)','Specific gravity of Urine by Test strip',      'UA',  '{ratio}'),
  ('5803-2',  'pH (Urine)',            'pH of Urine by Test strip',                      'UA',  '{pH}'),
  ('5804-0',  'Protein (Urine)',       'Protein [Presence] in Urine by Test strip',      'UA',  ''),
  ('5792-7',  'Glucose (Urine)',       'Glucose [Presence] in Urine by Test strip',      'UA',  ''),
  ('20505-4', 'Bilirubin (Urine)',     'Bilirubin.total [Presence] in Urine by Test strip','UA',''),
  ('5794-3',  'RBC (Urine)',           'Hemoglobin [Presence] in Urine by Test strip',   'UA',  ''),
  ('5799-2',  'Leukocytes (Urine)',    'Leukocytes [Presence] in Urine by Test strip',   'UA',  ''),
  ('5802-4',  'Nitrite (Urine)',       'Nitrite [Presence] in Urine by Test strip',      'UA',  ''),

  -- Infectious / Tropical
  ('7905-3',  'Dengue NS1 Ag',        'Dengue virus NS1 Ag [Presence] in Serum',         'MICRO', ''),
  ('75377-2', 'Dengue IgM',           'Dengue virus IgM Ab [Presence] in Serum',         'MICRO', ''),
  ('75378-0', 'Dengue IgG',           'Dengue virus IgG Ab [Presence] in Serum',         'MICRO', ''),
  ('32700-7', 'Malaria smear',        'Plasmodium sp identified in Blood by Light microscopy','MICRO',''),
  ('94500-6', 'SARS-CoV-2 RNA',       'SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen','MICRO',''),
  ('94558-4', 'SARS-CoV-2 Ag',        'SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen','MICRO',''),
  ('22587-0', 'Widal (Typhi O)',      'Salmonella typhi O Ab [Titer] in Serum',           'MICRO', ''),
  ('5196-1',  'HBsAg',                'Hepatitis B virus surface Ag [Presence] in Serum','MICRO', ''),
  ('16128-1', 'Anti-HCV',             'Hepatitis C virus Ab [Presence] in Serum',        'MICRO', ''),
  ('7917-8',  'HIV 1+2 Ab',           'HIV 1+2 Ab [Presence] in Serum',                  'MICRO', ''),
  ('5334-8',  'VDRL',                 'Reagin Ab [Presence] in Serum by VDRL',           'MICRO', ''),
  ('31147-2', 'Blood culture',        'Bacteria identified in Blood by Culture',         'MICRO', ''),
  ('630-4',   'Urine culture',        'Bacteria identified in Urine by Culture',         'MICRO', ''),

  -- Blood Bank
  ('882-1',   'ABO group',            'ABO group [Type] in Blood',                       'BLDBK', ''),
  ('10331-7', 'Rh type',              'Rh [Type] in Blood',                              'BLDBK', ''),
  ('1250-0',  'Direct Coombs',        'Direct antiglobulin test [Interpretation]',        'BLDBK', ''),
  ('1252-6',  'Indirect Coombs',      'Indirect antiglobulin test [Interpretation]',      'BLDBK', ''),

  -- Cardiac Markers
  ('10839-9', 'Troponin I',           'Troponin I.cardiac [Mass/volume] in Serum',       'CHEM', 'ng/mL'),
  ('33762-6', 'NT-proBNP',            'Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Serum','CHEM','pg/mL'),
  ('2157-6',  'CK',                   'Creatine kinase [Enzymatic activity/volume] in Serum','CHEM','U/L'),
  ('49563-0', 'CK-MB',                'Creatine kinase.MB [Mass/volume] in Serum',       'CHEM', 'ng/mL'),

  -- Inflammatory
  ('1988-5',  'CRP',                  'C reactive protein [Mass/volume] in Serum',       'CHEM', 'mg/L'),
  ('33959-8', 'Procalcitonin',        'Procalcitonin [Mass/volume] in Serum or Plasma',  'CHEM', 'ng/mL'),
  ('4537-7',  'Ferritin',             'Ferritin [Mass/volume] in Serum or Plasma',       'CHEM', 'ng/mL'),

  -- Others
  ('2502-3',  'Iron',                 'Iron [Mass/volume] in Serum or Plasma',           'CHEM', 'ug/dL'),
  ('2276-4',  'TIBC',                 'Iron binding capacity [Mass/volume] in Serum',    'CHEM', 'ug/dL'),
  ('33037-3', 'Amylase',              'Amylase [Enzymatic activity/volume] in Serum',    'CHEM', 'U/L'),
  ('1798-8',  'Lipase',               'Lipase [Enzymatic activity/volume] in Serum',     'CHEM', 'U/L'),
  ('2857-1',  'PSA',                  'Prostate specific Ag [Mass/volume] in Serum',     'CHEM', 'ng/mL')
ON CONFLICT(loinc_num) DO NOTHING;

-- ============================================================
-- PART 3: SNOMED CT Subset (~30 common findings)
-- ============================================================
INSERT INTO catalog_snomed (sctid, term, semantic_tag) VALUES
  ('38341003',  'Essential hypertension',             'disorder'),
  ('44054006',  'Type 2 diabetes mellitus',           'disorder'),
  ('73211009',  'Diabetes mellitus',                  'disorder'),
  ('195967001', 'Asthma',                             'disorder'),
  ('13645005',  'Chronic obstructive lung disease',   'disorder'),
  ('22298006',  'Myocardial infarction',              'disorder'),
  ('84114007',  'Heart failure',                      'disorder'),
  ('230690007', 'Cerebrovascular accident',           'disorder'),
  ('386661006', 'Fever',                              'finding'),
  ('25064002',  'Headache',                           'finding'),
  ('21522001',  'Abdominal pain',                     'finding'),
  ('49727002',  'Cough',                              'finding'),
  ('267036007', 'Dyspnoea',                           'finding'),
  ('422587007', 'Nausea',                             'finding'),
  ('422400008', 'Vomiting',                           'finding'),
  ('62315008',  'Diarrhoea',                          'finding'),
  ('29857009',  'Chest pain',                         'finding'),
  ('271681002', 'Low back pain',                      'finding'),
  ('56018004',  'Wheezing',                           'finding'),
  ('40739000',  'Dysphagia',                          'finding'),
  ('34014006',  'Viral disease',                      'disorder'),
  ('186431008', 'Tuberculosis',                       'disorder'),
  ('38362002',  'Dengue',                             'disorder'),
  ('4834000',   'Typhoid fever',                      'disorder'),
  ('61462000',  'Malaria',                            'disorder'),
  ('235856003', 'Liver disease',                      'disorder'),
  ('709044004', 'Chronic kidney disease',             'disorder'),
  ('398254007', 'Pre-eclampsia',                      'disorder'),
  ('161152002', 'Iron deficiency anaemia',            'disorder'),
  ('40930008',  'Hypothyroidism',                     'disorder')
ON CONFLICT(sctid) DO NOTHING;

-- ============================================================
-- PART 4: Version tracking
-- ============================================================
INSERT INTO catalog_versions (code_system, version, record_count, notes) VALUES
  ('ICD11',  '2024-01', 560, 'Curated BD-common subset'),
  ('LOINC',  '2.77',    90,  'Common lab tests + vital signs'),
  ('SNOMED', '2024-03', 30,  'Phase 1 minimal subset');

-- ============================================================
-- PART 5: Schema Updates to link Clinical Data to ICD-11
-- ============================================================
ALTER TABLE ClinicalDiagnosis ADD COLUMN icd11_code TEXT;
ALTER TABLE ClinicalDiagnosis ADD COLUMN icd11_title TEXT;

ALTER TABLE visits ADD COLUMN icd11_code TEXT;
ALTER TABLE visits ADD COLUMN icd11_description TEXT;

ALTER TABLE final_diagnosis ADD COLUMN icd11_code TEXT;
ALTER TABLE final_diagnosis ADD COLUMN icd11_title TEXT;
