import { sql } from 'drizzle-orm';
import { check, foreignKey, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { canonicalOutboxEvents } from './meta';

const utcNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const canonicalAccountingAccounts = sqliteTable('canonical_accounting_accounts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  accountPublicId: text('account_public_id').notNull(),
  accountCode: text('account_code').notNull(),
  displayName: text('display_name').notNull(),
  accountType: text('account_type').notNull(),
  normalBalance: text('normal_balance').notNull(),
  parentAccountPublicId: text('parent_account_public_id'),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_accounting_accounts_public').on(table.tenantId, table.accountPublicId),
  uniqueIndex('uq_canonical_accounting_accounts_code').on(table.tenantId, table.accountCode),
  index('idx_canonical_accounting_accounts_type').on(table.tenantId, table.accountType, table.status, table.accountCode),
  foreignKey({ name: 'fk_canonical_accounting_accounts_parent', columns: [table.tenantId, table.parentAccountPublicId], foreignColumns: [table.tenantId, table.accountPublicId] }).onDelete('restrict'),
  check('canonical_accounting_accounts_code_check', sql`length(trim(account_code))>0`),
  check('canonical_accounting_accounts_name_check', sql`length(trim(display_name))>0`),
  check('canonical_accounting_accounts_type_check', sql`account_type IN ('asset','liability','equity','revenue','contra_revenue','expense','contra_expense','other')`),
  check('canonical_accounting_accounts_normal_check', sql`normal_balance IN ('debit','credit')`),
  check('canonical_accounting_accounts_status_check', sql`status IN ('active','inactive','retired')`),
  check('canonical_accounting_accounts_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalAccountingMappings = sqliteTable('canonical_accounting_mappings', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  mappingKey: text('mapping_key').notNull(),
  accountPublicId: text('account_public_id').notNull(),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_accounting_mappings_key').on(table.tenantId, table.mappingKey),
  index('idx_canonical_accounting_mappings_account').on(table.tenantId, table.accountPublicId, table.status),
  foreignKey({ name: 'fk_canonical_accounting_mappings_account', columns: [table.tenantId, table.accountPublicId], foreignColumns: [canonicalAccountingAccounts.tenantId, canonicalAccountingAccounts.accountPublicId] }).onDelete('restrict'),
  check('canonical_accounting_mappings_key_check', sql`length(trim(mapping_key))>0`),
  check('canonical_accounting_mappings_status_check', sql`status IN ('active','inactive','retired')`),
  check('canonical_accounting_mappings_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalAccountingPeriods = sqliteTable('canonical_accounting_periods', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  periodPublicId: text('period_public_id').notNull(),
  periodName: text('period_name').notNull(),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  status: text('status').notNull().default('open'),
  closedAtUtc: text('closed_at_utc'),
  closedByPublicId: text('closed_by_public_id'),
  reopenedAtUtc: text('reopened_at_utc'),
  reopenedByPublicId: text('reopened_by_public_id'),
  reopenAuthorizationPublicId: text('reopen_authorization_public_id'),
  reopenReasonCode: text('reopen_reason_code'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_accounting_periods_public').on(table.tenantId, table.periodPublicId),
  uniqueIndex('uq_canonical_accounting_periods_name').on(table.tenantId, table.periodName),
  uniqueIndex('uq_canonical_accounting_periods_range').on(table.tenantId, table.startDate, table.endDate),
  index('idx_canonical_accounting_periods_lookup').on(table.tenantId, table.startDate, table.endDate, table.status),
  check('canonical_accounting_periods_name_check', sql`length(trim(period_name))>0`),
  check('canonical_accounting_periods_start_check', sql`start_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_accounting_periods_end_check', sql`end_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND end_date>=start_date`),
  check('canonical_accounting_periods_status_check', sql`status IN ('open','closed','reopened')`),
  check('canonical_accounting_periods_shape_check', sql`(status='open' AND closed_at_utc IS NULL AND closed_by_public_id IS NULL AND reopened_at_utc IS NULL AND reopened_by_public_id IS NULL AND reopen_authorization_public_id IS NULL AND reopen_reason_code IS NULL) OR (status='closed' AND closed_at_utc IS NOT NULL AND closed_by_public_id IS NOT NULL AND reopened_at_utc IS NULL AND reopened_by_public_id IS NULL AND reopen_authorization_public_id IS NULL AND reopen_reason_code IS NULL) OR (status='reopened' AND closed_at_utc IS NOT NULL AND closed_by_public_id IS NOT NULL AND reopened_at_utc IS NOT NULL AND reopened_by_public_id IS NOT NULL AND reopen_authorization_public_id IS NOT NULL AND reopen_reason_code IS NOT NULL)`),
  check('canonical_accounting_periods_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalAccountingVouchers = sqliteTable('canonical_accounting_vouchers', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  voucherPublicId: text('voucher_public_id').notNull(),
  voucherNumber: text('voucher_number').notNull(),
  voucherType: text('voucher_type').notNull(),
  outboxEventPublicId: text('outbox_event_public_id'),
  sourceEventType: text('source_event_type').notNull(),
  sourceAggregateType: text('source_aggregate_type'),
  sourceAggregatePublicId: text('source_aggregate_public_id'),
  currencyCode: text('currency_code').notNull(),
  businessDate: text('business_date').notNull(),
  occurredAtUtc: text('occurred_at_utc').notNull(),
  status: text('status').notNull().default('posted'),
  debitTotalMinor: integer('debit_total_minor').notNull(),
  creditTotalMinor: integer('credit_total_minor').notNull(),
  entryCount: integer('entry_count').notNull(),
  reversalOfVoucherPublicId: text('reversal_of_voucher_public_id'),
  reversalReasonCode: text('reversal_reason_code'),
  idempotencyKey: text('idempotency_key'),
  requestFingerprint: text('request_fingerprint'),
  postingGuard: integer('posting_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_accounting_vouchers_public').on(table.tenantId, table.voucherPublicId),
  uniqueIndex('uq_canonical_accounting_vouchers_number').on(table.tenantId, table.voucherNumber),
  uniqueIndex('uq_canonical_accounting_vouchers_outbox').on(table.tenantId, table.outboxEventPublicId).where(sql`${table.outboxEventPublicId} IS NOT NULL`),
  uniqueIndex('uq_canonical_accounting_vouchers_reversal').on(table.tenantId, table.reversalOfVoucherPublicId).where(sql`${table.reversalOfVoucherPublicId} IS NOT NULL`),
  uniqueIndex('uq_canonical_accounting_vouchers_reversal_idempotency').on(table.tenantId, table.idempotencyKey).where(sql`${table.idempotencyKey} IS NOT NULL`),
  index('idx_canonical_accounting_vouchers_date').on(table.tenantId, table.businessDate, table.voucherType, table.id),
  foreignKey({ name: 'fk_canonical_accounting_vouchers_outbox', columns: [table.tenantId, table.outboxEventPublicId], foreignColumns: [canonicalOutboxEvents.tenantId, canonicalOutboxEvents.eventPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_accounting_vouchers_reversal', columns: [table.tenantId, table.reversalOfVoucherPublicId], foreignColumns: [table.tenantId, table.voucherPublicId] }).onDelete('restrict'),
  check('canonical_accounting_vouchers_type_check', sql`voucher_type IN ('journal','receipt','payment','credit','reversal')`),
  check('canonical_accounting_vouchers_currency_check', sql`length(currency_code)=3 AND currency_code=upper(currency_code)`),
  check('canonical_accounting_vouchers_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_accounting_vouchers_occurred_check', sql`substr(occurred_at_utc,-1)='Z'`),
  check('canonical_accounting_vouchers_status_check', sql`status='posted'`),
  check('canonical_accounting_vouchers_totals_check', sql`debit_total_minor BETWEEN 1 AND 9007199254740991 AND credit_total_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_accounting_vouchers_entry_count_check', sql`entry_count BETWEEN 2 AND 10000`),
  check('canonical_accounting_vouchers_posting_guard', sql`posting_guard=1 AND debit_total_minor=credit_total_minor`),
  check('canonical_accounting_vouchers_reversal_shape_check', sql`(voucher_type='reversal' AND reversal_of_voucher_public_id IS NOT NULL AND reversal_reason_code IS NOT NULL AND outbox_event_public_id IS NULL AND idempotency_key IS NOT NULL AND request_fingerprint IS NOT NULL) OR (voucher_type<>'reversal' AND reversal_of_voucher_public_id IS NULL AND reversal_reason_code IS NULL AND outbox_event_public_id IS NOT NULL AND idempotency_key IS NULL AND request_fingerprint IS NULL)`),
  check('canonical_accounting_vouchers_fingerprint_check', sql`request_fingerprint IS NULL OR length(request_fingerprint)=64`),
  check('canonical_accounting_vouchers_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalAccountingEntries = sqliteTable('canonical_accounting_entries', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  entryPublicId: text('entry_public_id').notNull(),
  voucherPublicId: text('voucher_public_id').notNull(),
  lineNo: integer('line_no').notNull(),
  accountPublicId: text('account_public_id').notNull(),
  debitMinor: integer('debit_minor').notNull().default(0),
  creditMinor: integer('credit_minor').notNull().default(0),
  memoCode: text('memo_code').notNull(),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_accounting_entries_public').on(table.tenantId, table.entryPublicId),
  uniqueIndex('uq_canonical_accounting_entries_line').on(table.tenantId, table.voucherPublicId, table.lineNo),
  index('idx_canonical_accounting_entries_account').on(table.tenantId, table.accountPublicId, table.voucherPublicId),
  foreignKey({ name: 'fk_canonical_accounting_entries_voucher', columns: [table.tenantId, table.voucherPublicId], foreignColumns: [canonicalAccountingVouchers.tenantId, canonicalAccountingVouchers.voucherPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_accounting_entries_account', columns: [table.tenantId, table.accountPublicId], foreignColumns: [canonicalAccountingAccounts.tenantId, canonicalAccountingAccounts.accountPublicId] }).onDelete('restrict'),
  check('canonical_accounting_entries_line_check', sql`line_no BETWEEN 1 AND 10000`),
  check('canonical_accounting_entries_amount_check', sql`debit_minor BETWEEN 0 AND 9007199254740991 AND credit_minor BETWEEN 0 AND 9007199254740991 AND ((debit_minor>0 AND credit_minor=0) OR (credit_minor>0 AND debit_minor=0))`),
  check('canonical_accounting_entries_memo_check', sql`length(trim(memo_code))>0`),
  check('canonical_accounting_entries_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCashCustodyBalances = sqliteTable('canonical_cash_custody_balances', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  custodyPublicId: text('custody_public_id').notNull(),
  custodyType: text('custody_type').notNull(),
  legacyCounterId: integer('legacy_counter_id'),
  legacyCounterSessionId: integer('legacy_counter_session_id'),
  balanceMinor: integer('balance_minor').notNull().default(0),
  version: integer('version').notNull().default(0),
  projectionGuard: integer('projection_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_cash_custody_balances_public').on(table.tenantId, table.custodyPublicId),
  index('idx_canonical_cash_custody_balances_session').on(table.tenantId, table.legacyCounterSessionId, table.custodyType),
  check('canonical_cash_custody_balances_type_check', sql`custody_type IN ('counter_session','user','safe','bank_transit','other')`),
  check('canonical_cash_custody_balances_amount_check', sql`balance_minor BETWEEN -9007199254740991 AND 9007199254740991`),
  check('canonical_cash_custody_balances_version_check', sql`version>=0`),
  check('canonical_cash_custody_balances_projection_guard', sql`projection_guard=1`),
  check('canonical_cash_custody_balances_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCashCustodyMovements = sqliteTable('canonical_cash_custody_movements', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  custodyMovementPublicId: text('custody_movement_public_id').notNull(),
  outboxEventPublicId: text('outbox_event_public_id').notNull(),
  custodyPublicId: text('custody_public_id').notNull(),
  movementType: text('movement_type').notNull(),
  direction: text('direction').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  signedAmountMinor: integer('signed_amount_minor').notNull(),
  balanceBeforeMinor: integer('balance_before_minor').notNull(),
  balanceAfterMinor: integer('balance_after_minor').notNull(),
  legacyCounterId: integer('legacy_counter_id'),
  legacyCounterSessionId: integer('legacy_counter_session_id'),
  occurredAtUtc: text('occurred_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_cash_custody_movements_public').on(table.tenantId, table.custodyMovementPublicId),
  uniqueIndex('uq_canonical_cash_custody_movements_outbox').on(table.tenantId, table.outboxEventPublicId),
  index('idx_canonical_cash_custody_movements_balance').on(table.tenantId, table.custodyPublicId, table.occurredAtUtc, table.id),
  foreignKey({ name: 'fk_canonical_cash_custody_movements_outbox', columns: [table.tenantId, table.outboxEventPublicId], foreignColumns: [canonicalOutboxEvents.tenantId, canonicalOutboxEvents.eventPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_cash_custody_movements_balance', columns: [table.tenantId, table.custodyPublicId], foreignColumns: [canonicalCashCustodyBalances.tenantId, canonicalCashCustodyBalances.custodyPublicId] }).onDelete('restrict'),
  check('canonical_cash_custody_movements_type_check', sql`movement_type IN ('collection','refund','expense','payroll','practitioner_payout','handover','adjustment','shadow')`),
  check('canonical_cash_custody_movements_direction_check', sql`direction IN ('in','out','neutral')`),
  check('canonical_cash_custody_movements_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_cash_custody_movements_signed_check', sql`signed_amount_minor=CASE WHEN direction='in' THEN amount_minor WHEN direction='out' THEN -amount_minor ELSE 0 END`),
  check('canonical_cash_custody_movements_balance_math_check', sql`balance_after_minor=balance_before_minor+signed_amount_minor`),
  check('canonical_cash_custody_movements_occurred_check', sql`substr(occurred_at_utc,-1)='Z'`),
  check('canonical_cash_custody_movements_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_cash_custody_movements_balance_guard', sql`balance_guard=1`),
  check('canonical_cash_custody_movements_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalAccountingPostingJobs = sqliteTable('canonical_accounting_posting_jobs', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  postingJobPublicId: text('posting_job_public_id').notNull(),
  outboxEventPublicId: text('outbox_event_public_id').notNull(),
  sourceEventType: text('source_event_type').notNull(),
  sourceFingerprint: text('source_fingerprint').notNull(),
  postingKind: text('posting_kind').notNull(),
  status: text('status').notNull().default('pending'),
  attempts: integer('attempts').notNull().default(0),
  maxAttempts: integer('max_attempts').notNull().default(3),
  voucherPublicId: text('voucher_public_id'),
  custodyMovementPublicId: text('custody_movement_public_id'),
  skipCode: text('skip_code'),
  lastErrorCode: text('last_error_code'),
  lastErrorSummary: text('last_error_summary'),
  firstAttemptAtUtc: text('first_attempt_at_utc'),
  lastAttemptAtUtc: text('last_attempt_at_utc'),
  postedAtUtc: text('posted_at_utc'),
  nextAttemptAtUtc: text('next_attempt_at_utc'),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_accounting_posting_jobs_public').on(table.tenantId, table.postingJobPublicId),
  uniqueIndex('uq_canonical_accounting_posting_jobs_outbox').on(table.tenantId, table.outboxEventPublicId),
  index('idx_canonical_accounting_posting_jobs_queue').on(table.tenantId, table.status, table.nextAttemptAtUtc, table.id),
  index('idx_canonical_accounting_posting_jobs_event').on(table.tenantId, table.sourceEventType, table.status),
  foreignKey({ name: 'fk_canonical_accounting_posting_jobs_outbox', columns: [table.tenantId, table.outboxEventPublicId], foreignColumns: [canonicalOutboxEvents.tenantId, canonicalOutboxEvents.eventPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_accounting_posting_jobs_voucher', columns: [table.tenantId, table.voucherPublicId], foreignColumns: [canonicalAccountingVouchers.tenantId, canonicalAccountingVouchers.voucherPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_accounting_posting_jobs_custody', columns: [table.tenantId, table.custodyMovementPublicId], foreignColumns: [canonicalCashCustodyMovements.tenantId, canonicalCashCustodyMovements.custodyMovementPublicId] }).onDelete('restrict'),
  check('canonical_accounting_posting_jobs_fingerprint_check', sql`length(source_fingerprint)=64`),
  check('canonical_accounting_posting_jobs_kind_check', sql`posting_kind IN ('voucher','cash_custody','skip')`),
  check('canonical_accounting_posting_jobs_status_check', sql`status IN ('pending','processing','retry','posted','skipped','dead_letter')`),
  check('canonical_accounting_posting_jobs_attempts_check', sql`attempts BETWEEN 0 AND 1000 AND max_attempts BETWEEN 1 AND 1000 AND attempts<=max_attempts`),
  check('canonical_accounting_posting_jobs_shape_check', sql`(status='posted' AND posted_at_utc IS NOT NULL AND ((posting_kind='voucher' AND voucher_public_id IS NOT NULL AND custody_movement_public_id IS NULL) OR (posting_kind='cash_custody' AND custody_movement_public_id IS NOT NULL AND voucher_public_id IS NULL))) OR (status='skipped' AND posting_kind='skip' AND posted_at_utc IS NOT NULL AND skip_code IS NOT NULL AND voucher_public_id IS NULL AND custody_movement_public_id IS NULL) OR (status IN ('pending','processing','retry','dead_letter') AND voucher_public_id IS NULL AND custody_movement_public_id IS NULL AND posted_at_utc IS NULL)`),
]);
