import { sql } from 'drizzle-orm';
import { check, foreignKey, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { canonicalServiceEvents } from './service-operations';
import { canonicalEncounters } from './clinical';

const utcNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const canonicalInvoices = sqliteTable('canonical_invoices', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  invoiceNumber: text('invoice_number').notNull(),
  legacyPatientId: integer('legacy_patient_id').notNull(),
  currencyCode: text('currency_code').notNull(),
  subtotalMinor: integer('subtotal_minor').notNull(),
  adjustmentTotalMinor: integer('adjustment_total_minor').notNull(),
  totalMinor: integer('total_minor').notNull(),
  paidMinor: integer('paid_minor').notNull().default(0),
  dueMinor: integer('due_minor').notNull().default(0),
  creditedMinor: integer('credited_minor').notNull().default(0),
  netDueMinor: integer('net_due_minor').notNull(),
  adjustmentProjectionGuard: integer('adjustment_projection_guard').notNull().default(1),
  status: text('status').notNull(),
  issuedAtUtc: text('issued_at_utc').notNull(),
  postedAtUtc: text('posted_at_utc'),
  cancelledAtUtc: text('cancelled_at_utc'),
  reversedAtUtc: text('reversed_at_utc'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_invoices_public_id').on(table.tenantId, table.invoicePublicId),
  uniqueIndex('uq_canonical_invoices_number').on(table.tenantId, table.invoiceNumber),
  index('idx_canonical_invoices_patient_time').on(table.tenantId, table.legacyPatientId, table.issuedAtUtc, table.invoicePublicId),
  index('idx_canonical_invoices_status_time').on(table.tenantId, table.status, table.issuedAtUtc, table.invoicePublicId),
  check('canonical_invoices_number_check', sql`length(trim(invoice_number)) > 0`),
  check('canonical_invoices_currency_check', sql`length(currency_code) = 3 AND currency_code = upper(currency_code)`),
  check('canonical_invoices_subtotal_check', sql`subtotal_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_invoices_adjustment_check', sql`adjustment_total_minor BETWEEN -9007199254740991 AND 9007199254740991`),
  check('canonical_invoices_total_range_check', sql`total_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_invoices_total_check', sql`total_minor = subtotal_minor + adjustment_total_minor`),
  check('canonical_invoices_paid_range_check', sql`paid_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_invoices_due_range_check', sql`due_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_invoices_balance_check', sql`paid_minor + due_minor = total_minor`),
  check('canonical_invoices_credited_range_check', sql`credited_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_invoices_net_due_range_check', sql`net_due_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_invoices_adjustment_projection_guard', sql`adjustment_projection_guard = 1 AND net_due_minor = due_minor - credited_minor`),
  check('canonical_invoices_status_check', sql`status IN ('draft','posted','cancelled','reversed')`),
  check('canonical_invoices_issued_check', sql`substr(issued_at_utc, -1) = 'Z'`),
  check('canonical_invoices_posted_check', sql`posted_at_utc IS NULL OR substr(posted_at_utc, -1) = 'Z'`),
  check('canonical_invoices_cancelled_check', sql`cancelled_at_utc IS NULL OR substr(cancelled_at_utc, -1) = 'Z'`),
  check('canonical_invoices_reversed_check', sql`reversed_at_utc IS NULL OR substr(reversed_at_utc, -1) = 'Z'`),
  check('canonical_invoices_lifecycle_check', sql`(status = 'draft' AND posted_at_utc IS NULL AND cancelled_at_utc IS NULL AND reversed_at_utc IS NULL) OR (status = 'posted' AND posted_at_utc IS NOT NULL AND cancelled_at_utc IS NULL AND reversed_at_utc IS NULL) OR (status = 'cancelled' AND posted_at_utc IS NOT NULL AND cancelled_at_utc IS NOT NULL AND reversed_at_utc IS NULL) OR (status = 'reversed' AND posted_at_utc IS NOT NULL AND cancelled_at_utc IS NULL AND reversed_at_utc IS NOT NULL)`),
  check('canonical_invoices_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalInvoiceLines = sqliteTable('canonical_invoice_lines', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  linePublicId: text('line_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  lineType: text('line_type').notNull(),
  serviceEventPublicId: text('service_event_public_id'),
  adjustmentCode: text('adjustment_code'),
  quantity: integer('quantity').notNull(),
  unitAmountMinor: integer('unit_amount_minor').notNull(),
  lineAmountMinor: integer('line_amount_minor').notNull(),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_invoice_lines_public_id').on(table.tenantId, table.linePublicId),
  uniqueIndex('uq_canonical_invoice_lines_invoice_line').on(table.tenantId, table.invoicePublicId, table.linePublicId),
  uniqueIndex('uq_canonical_invoice_lines_service_event')
    .on(table.tenantId, table.serviceEventPublicId)
    .where(sql`${table.serviceEventPublicId} IS NOT NULL`),
  index('idx_canonical_invoice_lines_invoice').on(table.tenantId, table.invoicePublicId, table.id),
  index('idx_canonical_invoice_lines_type').on(table.tenantId, table.lineType, table.adjustmentCode, table.invoicePublicId),
  foreignKey({ name: 'fk_canonical_invoice_lines_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_invoice_lines_event', columns: [table.tenantId, table.serviceEventPublicId], foreignColumns: [canonicalServiceEvents.tenantId, canonicalServiceEvents.eventPublicId] }).onDelete('restrict'),
  check('canonical_invoice_lines_type_check', sql`line_type IN ('service','discount','tax','rounding','surcharge','waiver','other_adjustment')`),
  check('canonical_invoice_lines_quantity_check', sql`quantity BETWEEN 1 AND 9007199254740991`),
  check('canonical_invoice_lines_unit_range_check', sql`unit_amount_minor BETWEEN -9007199254740991 AND 9007199254740991`),
  check('canonical_invoice_lines_amount_range_check', sql`line_amount_minor BETWEEN -9007199254740991 AND 9007199254740991`),
  check('canonical_invoice_lines_shape_check', sql`(line_type = 'service' AND service_event_public_id IS NOT NULL AND adjustment_code IS NULL AND unit_amount_minor >= 0 AND (unit_amount_minor = 0 OR quantity <= 9007199254740991 / unit_amount_minor) AND line_amount_minor = quantity * unit_amount_minor) OR (line_type <> 'service' AND service_event_public_id IS NULL AND adjustment_code IS NOT NULL AND quantity = 1 AND line_amount_minor = unit_amount_minor)`),
  check('canonical_invoice_lines_discount_check', sql`line_type NOT IN ('discount','waiver') OR line_amount_minor <= 0`),
  check('canonical_invoice_lines_tax_check', sql`line_type NOT IN ('tax','surcharge') OR line_amount_minor >= 0`),
  check('canonical_invoice_lines_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalInvoiceEncounterLinks = sqliteTable('canonical_invoice_encounter_links', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  encounterPublicId: text('encounter_public_id').notNull(),
  legacyAdmissionId: integer('legacy_admission_id').notNull(),
  linkType: text('link_type').notNull(),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_invoice_encounter_invoice').on(table.tenantId, table.invoicePublicId),
  uniqueIndex('uq_canonical_invoice_encounter_discharge')
    .on(table.tenantId, table.encounterPublicId)
    .where(sql`${table.linkType} = 'discharge_invoice'`),
  index('idx_canonical_invoice_encounter_admission')
    .on(table.tenantId, table.legacyAdmissionId, table.encounterPublicId),
  foreignKey({
    name: 'fk_canonical_invoice_encounter_invoice',
    columns: [table.tenantId, table.invoicePublicId],
    foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_invoice_encounter_encounter',
    columns: [table.tenantId, table.encounterPublicId],
    foreignColumns: [canonicalEncounters.tenantId, canonicalEncounters.encounterPublicId],
  }).onDelete('restrict'),
  check('canonical_invoice_encounter_admission_check', sql`legacy_admission_id > 0`),
  check('canonical_invoice_encounter_type_check', sql`link_type IN ('discharge_invoice')`),
  check('canonical_invoice_encounter_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalPaymentReceipts = sqliteTable('canonical_payment_receipts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  receiptNumber: text('receipt_number').notNull(),
  legacyPatientId: integer('legacy_patient_id').notNull(),
  currencyCode: text('currency_code').notNull(),
  totalMinor: integer('total_minor').notNull(),
  allocatedTotalMinor: integer('allocated_total_minor').notNull(),
  unallocatedMinor: integer('unallocated_minor').notNull(),
  status: text('status').notNull(),
  receivedAtUtc: text('received_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  legacyCollectorId: integer('legacy_collector_id'),
  legacyCounterId: integer('legacy_counter_id'),
  legacyCounterSessionId: integer('legacy_counter_session_id'),
  externalTransactionId: text('external_transaction_id'),
  postedAtUtc: text('posted_at_utc'),
  failedAtUtc: text('failed_at_utc'),
  reversedAtUtc: text('reversed_at_utc'),
  refundedMinor: integer('refunded_minor').notNull().default(0),
  netReceivedMinor: integer('net_received_minor').notNull(),
  refundProjectionGuard: integer('refund_projection_guard').notNull().default(1),
  reconciliationGuard: integer('reconciliation_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_payment_receipts_public_id').on(table.tenantId, table.receiptPublicId),
  uniqueIndex('uq_canonical_payment_receipts_number').on(table.tenantId, table.receiptNumber),
  index('idx_canonical_payment_receipts_patient_time').on(table.tenantId, table.legacyPatientId, table.receivedAtUtc, table.receiptPublicId),
  index('idx_canonical_payment_receipts_status_time').on(table.tenantId, table.status, table.receivedAtUtc, table.receiptPublicId),
  index('idx_canonical_payment_receipts_external')
    .on(table.tenantId, table.externalTransactionId)
    .where(sql`${table.externalTransactionId} IS NOT NULL`),
  check('canonical_payment_receipts_number_check', sql`length(trim(receipt_number)) > 0`),
  check('canonical_payment_receipts_patient_check', sql`legacy_patient_id > 0`),
  check('canonical_payment_receipts_currency_check', sql`length(currency_code) = 3 AND currency_code = upper(currency_code)`),
  check('canonical_payment_receipts_total_check', sql`total_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_payment_receipts_allocated_check', sql`allocated_total_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_receipts_unallocated_check', sql`unallocated_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_receipts_reconciliation_check', sql`total_minor = allocated_total_minor + unallocated_minor`),
  check('canonical_payment_receipts_status_check', sql`status IN ('pending','posted','failed','reversed')`),
  check('canonical_payment_receipts_received_check', sql`substr(received_at_utc, -1) = 'Z'`),
  check('canonical_payment_receipts_business_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_payment_receipts_posted_check', sql`posted_at_utc IS NULL OR substr(posted_at_utc, -1) = 'Z'`),
  check('canonical_payment_receipts_failed_check', sql`failed_at_utc IS NULL OR substr(failed_at_utc, -1) = 'Z'`),
  check('canonical_payment_receipts_reversed_check', sql`reversed_at_utc IS NULL OR substr(reversed_at_utc, -1) = 'Z'`),
  check('canonical_payment_receipts_lifecycle_check', sql`(status = 'pending' AND posted_at_utc IS NULL AND failed_at_utc IS NULL AND reversed_at_utc IS NULL AND allocated_total_minor = 0 AND unallocated_minor = total_minor) OR (status = 'posted' AND posted_at_utc IS NOT NULL AND failed_at_utc IS NULL AND reversed_at_utc IS NULL) OR (status = 'failed' AND posted_at_utc IS NULL AND failed_at_utc IS NOT NULL AND reversed_at_utc IS NULL AND allocated_total_minor = 0 AND unallocated_minor = total_minor) OR (status = 'reversed' AND posted_at_utc IS NOT NULL AND failed_at_utc IS NULL AND reversed_at_utc IS NOT NULL)`),
  check('canonical_payment_receipts_refunded_range_check', sql`refunded_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_receipts_net_received_range_check', sql`net_received_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_receipts_refund_projection_guard', sql`refund_projection_guard = 1 AND net_received_minor = total_minor - refunded_minor`),
  check('canonical_payment_receipts_reconciliation_guard', sql`reconciliation_guard = 1`),
  check('canonical_payment_receipts_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalPaymentTenders = sqliteTable('canonical_payment_tenders', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  tenderPublicId: text('tender_public_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  tenderType: text('tender_type').notNull(),
  methodCode: text('method_code').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  status: text('status').notNull(),
  externalTransactionId: text('external_transaction_id'),
  capturedAtUtc: text('captured_at_utc'),
  failedAtUtc: text('failed_at_utc'),
  reversedAtUtc: text('reversed_at_utc'),
  reversedMinor: integer('reversed_minor').notNull().default(0),
  remainingMinor: integer('remaining_minor').notNull(),
  reversalProjectionGuard: integer('reversal_projection_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_payment_tenders_public_id').on(table.tenantId, table.tenderPublicId),
  uniqueIndex('uq_canonical_payment_tenders_external')
    .on(table.tenantId, table.externalTransactionId)
    .where(sql`${table.externalTransactionId} IS NOT NULL`),
  index('idx_canonical_payment_tenders_receipt').on(table.tenantId, table.receiptPublicId, table.id),
  index('idx_canonical_payment_tenders_status').on(table.tenantId, table.status, table.tenderType, table.receiptPublicId),
  foreignKey({ name: 'fk_canonical_payment_tenders_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  check('canonical_payment_tenders_type_check', sql`tender_type IN ('cash','card','mobile_wallet','bank_transfer','gateway','other')`),
  check('canonical_payment_tenders_method_check', sql`length(trim(method_code)) > 0`),
  check('canonical_payment_tenders_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_payment_tenders_status_check', sql`status IN ('verifying','captured','failed','reversed')`),
  check('canonical_payment_tenders_captured_check', sql`captured_at_utc IS NULL OR substr(captured_at_utc, -1) = 'Z'`),
  check('canonical_payment_tenders_failed_check', sql`failed_at_utc IS NULL OR substr(failed_at_utc, -1) = 'Z'`),
  check('canonical_payment_tenders_reversed_check', sql`reversed_at_utc IS NULL OR substr(reversed_at_utc, -1) = 'Z'`),
  check('canonical_payment_tenders_lifecycle_check', sql`(status = 'verifying' AND captured_at_utc IS NULL AND failed_at_utc IS NULL AND reversed_at_utc IS NULL) OR (status = 'captured' AND captured_at_utc IS NOT NULL AND failed_at_utc IS NULL AND reversed_at_utc IS NULL) OR (status = 'failed' AND captured_at_utc IS NULL AND failed_at_utc IS NOT NULL AND reversed_at_utc IS NULL) OR (status = 'reversed' AND captured_at_utc IS NOT NULL AND failed_at_utc IS NULL AND reversed_at_utc IS NOT NULL)`),
  check('canonical_payment_tenders_reversed_range_check', sql`reversed_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_tenders_remaining_range_check', sql`remaining_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_tenders_reversal_projection_guard', sql`reversal_projection_guard = 1 AND reversed_minor + remaining_minor = amount_minor`),
  check('canonical_payment_tenders_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalPaymentAllocations = sqliteTable('canonical_payment_allocations', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  allocationPublicId: text('allocation_public_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  invoiceLinePublicId: text('invoice_line_public_id'),
  amountMinor: integer('amount_minor').notNull(),
  invoiceDueBeforeMinor: integer('invoice_due_before_minor').notNull(),
  invoiceDueAfterMinor: integer('invoice_due_after_minor').notNull(),
  status: text('status').notNull().default('active'),
  allocatedAtUtc: text('allocated_at_utc').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  reversedMinor: integer('reversed_minor').notNull().default(0),
  remainingMinor: integer('remaining_minor').notNull(),
  reversalProjectionGuard: integer('reversal_projection_guard').notNull().default(1),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_payment_allocations_public_id').on(table.tenantId, table.allocationPublicId),
  index('idx_canonical_payment_allocations_receipt').on(table.tenantId, table.receiptPublicId, table.status, table.id),
  index('idx_canonical_payment_allocations_invoice').on(table.tenantId, table.invoicePublicId, table.status, table.id),
  index('idx_canonical_payment_allocations_line')
    .on(table.tenantId, table.invoicePublicId, table.invoiceLinePublicId, table.status)
    .where(sql`${table.invoiceLinePublicId} IS NOT NULL`),
  foreignKey({ name: 'fk_canonical_payment_allocations_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_payment_allocations_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_payment_allocations_invoice_line', columns: [table.tenantId, table.invoicePublicId, table.invoiceLinePublicId], foreignColumns: [canonicalInvoiceLines.tenantId, canonicalInvoiceLines.invoicePublicId, canonicalInvoiceLines.linePublicId] }).onDelete('restrict'),
  check('canonical_payment_allocations_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_payment_allocations_due_before_check', sql`invoice_due_before_minor BETWEEN amount_minor AND 9007199254740991`),
  check('canonical_payment_allocations_due_after_check', sql`invoice_due_after_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_allocations_balance_math_check', sql`invoice_due_after_minor = invoice_due_before_minor - amount_minor`),
  check('canonical_payment_allocations_status_check', sql`status IN ('active','reversed')`),
  check('canonical_payment_allocations_allocated_check', sql`substr(allocated_at_utc, -1) = 'Z'`),
  check('canonical_payment_allocations_reversed_check', sql`reversed_at_utc IS NULL OR substr(reversed_at_utc, -1) = 'Z'`),
  check('canonical_payment_allocations_lifecycle_check', sql`(status = 'active' AND reversed_at_utc IS NULL) OR (status = 'reversed' AND reversed_at_utc IS NOT NULL)`),
  check('canonical_payment_allocations_reversed_range_check', sql`reversed_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_allocations_remaining_range_check', sql`remaining_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_payment_allocations_reversal_projection_guard', sql`reversal_projection_guard = 1 AND reversed_minor + remaining_minor = amount_minor`),
  check('canonical_payment_allocations_stale_invoice_balance_guard', sql`balance_guard = 1`),
  check('canonical_payment_allocations_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalDeposits = sqliteTable('canonical_deposits', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  depositPublicId: text('deposit_public_id').notNull(),
  depositNumber: text('deposit_number').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  legacyPatientId: integer('legacy_patient_id').notNull(),
  currencyCode: text('currency_code').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  appliedMinor: integer('applied_minor').notNull().default(0),
  refundedMinor: integer('refunded_minor').notNull().default(0),
  availableMinor: integer('available_minor').notNull(),
  status: text('status').notNull(),
  receivedAtUtc: text('received_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  postedAtUtc: text('posted_at_utc').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  reconciliationGuard: integer('reconciliation_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_deposits_public_id').on(table.tenantId, table.depositPublicId),
  uniqueIndex('uq_canonical_deposits_number').on(table.tenantId, table.depositNumber),
  uniqueIndex('uq_canonical_deposits_receipt').on(table.tenantId, table.receiptPublicId),
  index('idx_canonical_deposits_patient_status').on(table.tenantId, table.legacyPatientId, table.status, table.receivedAtUtc),
  index('idx_canonical_deposits_available').on(table.tenantId, table.status, table.availableMinor, table.receivedAtUtc),
  foreignKey({ name: 'fk_canonical_deposits_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  check('canonical_deposits_number_check', sql`length(trim(deposit_number)) > 0`),
  check('canonical_deposits_patient_check', sql`legacy_patient_id > 0`),
  check('canonical_deposits_currency_check', sql`length(currency_code) = 3 AND currency_code = upper(currency_code)`),
  check('canonical_deposits_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_deposits_applied_check', sql`applied_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_deposits_refunded_check', sql`refunded_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_deposits_available_check', sql`available_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_deposits_balance_check', sql`amount_minor = applied_minor + refunded_minor + available_minor`),
  check('canonical_deposits_status_check', sql`status IN ('posted','reversed')`),
  check('canonical_deposits_received_check', sql`substr(received_at_utc, -1) = 'Z'`),
  check('canonical_deposits_business_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_deposits_lifecycle_check', sql`(status = 'posted' AND reversed_at_utc IS NULL) OR (status = 'reversed' AND reversed_at_utc IS NOT NULL)`),
  check('canonical_deposits_reconciliation_guard', sql`reconciliation_guard = 1`),
  check('canonical_deposits_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalDepositApplications = sqliteTable('canonical_deposit_applications', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  applicationPublicId: text('application_public_id').notNull(),
  depositPublicId: text('deposit_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  invoiceLinePublicId: text('invoice_line_public_id'),
  amountMinor: integer('amount_minor').notNull(),
  depositAvailableBeforeMinor: integer('deposit_available_before_minor').notNull(),
  depositAvailableAfterMinor: integer('deposit_available_after_minor').notNull(),
  invoicePaidBeforeMinor: integer('invoice_paid_before_minor').notNull(),
  invoicePaidAfterMinor: integer('invoice_paid_after_minor').notNull(),
  invoiceDueBeforeMinor: integer('invoice_due_before_minor').notNull(),
  invoiceDueAfterMinor: integer('invoice_due_after_minor').notNull(),
  invoiceNetDueBeforeMinor: integer('invoice_net_due_before_minor').notNull(),
  invoiceNetDueAfterMinor: integer('invoice_net_due_after_minor').notNull(),
  status: text('status').notNull().default('active'),
  appliedAtUtc: text('applied_at_utc').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_deposit_applications_public_id').on(table.tenantId, table.applicationPublicId),
  index('idx_canonical_deposit_applications_deposit').on(table.tenantId, table.depositPublicId, table.status, table.appliedAtUtc),
  index('idx_canonical_deposit_applications_invoice').on(table.tenantId, table.invoicePublicId, table.status, table.appliedAtUtc),
  foreignKey({ name: 'fk_canonical_deposit_applications_deposit', columns: [table.tenantId, table.depositPublicId], foreignColumns: [canonicalDeposits.tenantId, canonicalDeposits.depositPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_deposit_applications_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_deposit_applications_invoice_line', columns: [table.tenantId, table.invoicePublicId, table.invoiceLinePublicId], foreignColumns: [canonicalInvoiceLines.tenantId, canonicalInvoiceLines.invoicePublicId, canonicalInvoiceLines.linePublicId] }).onDelete('restrict'),
  check('canonical_deposit_applications_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_deposit_applications_deposit_math_check', sql`deposit_available_after_minor = deposit_available_before_minor - amount_minor`),
  check('canonical_deposit_applications_paid_math_check', sql`invoice_paid_after_minor = invoice_paid_before_minor + amount_minor`),
  check('canonical_deposit_applications_due_math_check', sql`invoice_due_after_minor = invoice_due_before_minor - amount_minor`),
  check('canonical_deposit_applications_net_due_math_check', sql`invoice_net_due_after_minor = invoice_net_due_before_minor - amount_minor`),
  check('canonical_deposit_applications_lifecycle_check', sql`(status = 'active' AND reversed_at_utc IS NULL) OR (status = 'reversed' AND reversed_at_utc IS NOT NULL)`),
  check('canonical_deposit_applications_balance_guard', sql`balance_guard = 1`),
  check('canonical_deposit_applications_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalCreditNotes = sqliteTable('canonical_credit_notes', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  creditNotePublicId: text('credit_note_public_id').notNull(),
  creditNoteNumber: text('credit_note_number').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  legacyPatientId: integer('legacy_patient_id').notNull(),
  currencyCode: text('currency_code').notNull(),
  reasonCode: text('reason_code').notNull(),
  totalMinor: integer('total_minor').notNull(),
  invoiceCreditedBeforeMinor: integer('invoice_credited_before_minor').notNull(),
  invoiceCreditedAfterMinor: integer('invoice_credited_after_minor').notNull(),
  invoiceNetDueBeforeMinor: integer('invoice_net_due_before_minor').notNull(),
  invoiceNetDueAfterMinor: integer('invoice_net_due_after_minor').notNull(),
  status: text('status').notNull(),
  issuedAtUtc: text('issued_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  postedAtUtc: text('posted_at_utc').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  reconciliationGuard: integer('reconciliation_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_notes_public_id').on(table.tenantId, table.creditNotePublicId),
  uniqueIndex('uq_canonical_credit_notes_number').on(table.tenantId, table.creditNoteNumber),
  index('idx_canonical_credit_notes_invoice').on(table.tenantId, table.invoicePublicId, table.status, table.issuedAtUtc),
  index('idx_canonical_credit_notes_patient').on(table.tenantId, table.legacyPatientId, table.status, table.issuedAtUtc),
  foreignKey({ name: 'fk_canonical_credit_notes_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  check('canonical_credit_notes_number_check', sql`length(trim(credit_note_number)) > 0`),
  check('canonical_credit_notes_reason_check', sql`length(trim(reason_code)) > 0`),
  check('canonical_credit_notes_total_check', sql`total_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_notes_credit_math_check', sql`invoice_credited_after_minor = invoice_credited_before_minor + total_minor`),
  check('canonical_credit_notes_net_due_math_check', sql`invoice_net_due_after_minor = invoice_net_due_before_minor - total_minor`),
  check('canonical_credit_notes_lifecycle_check', sql`(status = 'posted' AND reversed_at_utc IS NULL) OR (status = 'reversed' AND reversed_at_utc IS NOT NULL)`),
  check('canonical_credit_notes_reconciliation_guard', sql`reconciliation_guard = 1`),
  check('canonical_credit_notes_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalCreditNoteLines = sqliteTable('canonical_credit_note_lines', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  creditLinePublicId: text('credit_line_public_id').notNull(),
  creditNotePublicId: text('credit_note_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  invoiceLinePublicId: text('invoice_line_public_id'),
  amountMinor: integer('amount_minor').notNull(),
  reasonCode: text('reason_code').notNull(),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_note_lines_public_id').on(table.tenantId, table.creditLinePublicId),
  index('idx_canonical_credit_note_lines_note').on(table.tenantId, table.creditNotePublicId, table.id),
  index('idx_canonical_credit_note_lines_invoice_line')
    .on(table.tenantId, table.invoicePublicId, table.invoiceLinePublicId)
    .where(sql`${table.invoiceLinePublicId} IS NOT NULL`),
  foreignKey({ name: 'fk_canonical_credit_note_lines_note', columns: [table.tenantId, table.creditNotePublicId], foreignColumns: [canonicalCreditNotes.tenantId, canonicalCreditNotes.creditNotePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_lines_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_lines_invoice_line', columns: [table.tenantId, table.invoicePublicId, table.invoiceLinePublicId], foreignColumns: [canonicalInvoiceLines.tenantId, canonicalInvoiceLines.invoicePublicId, canonicalInvoiceLines.linePublicId] }).onDelete('restrict'),
  check('canonical_credit_note_lines_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_note_lines_reason_check', sql`length(trim(reason_code)) > 0`),
  check('canonical_credit_note_lines_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalCreditNoteCashRefunds = sqliteTable('canonical_credit_note_cash_refunds', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  refundPublicId: text('refund_public_id').notNull(),
  creditNotePublicId: text('credit_note_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  payoutTenderType: text('payout_tender_type').notNull(),
  payoutMethodCode: text('payout_method_code').notNull(),
  legacyCounterId: integer('legacy_counter_id').notNull(),
  legacyCounterSessionId: integer('legacy_counter_session_id').notNull(),
  status: text('status').notNull(),
  refundedAtUtc: text('refunded_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  reconciliationGuard: integer('reconciliation_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_note_cash_refunds_public_id').on(table.tenantId, table.refundPublicId),
  uniqueIndex('uq_canonical_credit_note_cash_refunds_credit_note').on(table.tenantId, table.creditNotePublicId),
  index('idx_canonical_credit_note_cash_refunds_invoice').on(table.tenantId, table.invoicePublicId, table.status, table.refundedAtUtc),
  index('idx_canonical_credit_note_cash_refunds_counter').on(table.tenantId, table.legacyCounterSessionId, table.status, table.refundedAtUtc),
  foreignKey({ name: 'fk_canonical_credit_note_cash_refunds_note', columns: [table.tenantId, table.creditNotePublicId], foreignColumns: [canonicalCreditNotes.tenantId, canonicalCreditNotes.creditNotePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_cash_refunds_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  check('canonical_credit_note_cash_refunds_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_note_cash_refunds_payout_tender_check', sql`payout_tender_type = 'cash'`),
  check('canonical_credit_note_cash_refunds_payout_method_check', sql`length(trim(payout_method_code)) > 0`),
  check('canonical_credit_note_cash_refunds_counter_check', sql`legacy_counter_id > 0 AND legacy_counter_session_id > 0`),
  check('canonical_credit_note_cash_refunds_status_check', sql`status IN ('posted','reversed')`),
  check('canonical_credit_note_cash_refunds_refunded_check', sql`substr(refunded_at_utc, -1) = 'Z'`),
  check('canonical_credit_note_cash_refunds_business_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_credit_note_cash_refunds_reversed_check', sql`reversed_at_utc IS NULL OR substr(reversed_at_utc, -1) = 'Z'`),
  check('canonical_credit_note_cash_refunds_lifecycle_check', sql`(status = 'posted' AND reversed_at_utc IS NULL) OR (status = 'reversed' AND reversed_at_utc IS NOT NULL)`),
  check('canonical_credit_note_cash_refunds_reconciliation_guard', sql`reconciliation_guard = 1`),
  check('canonical_credit_note_cash_refunds_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalCreditNoteCashRefundReversals = sqliteTable('canonical_credit_note_cash_refund_reversals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  reversalPublicId: text('reversal_public_id').notNull(),
  idempotencyKey: text('idempotency_key').notNull(),
  refundPublicId: text('refund_public_id').notNull(),
  creditNotePublicId: text('credit_note_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  creditTotalMinor: integer('credit_total_minor').notNull(),
  currencyCode: text('currency_code').notNull(),
  reasonCode: text('reason_code').notNull(),
  reversedAtUtc: text('reversed_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  actorUserId: integer('actor_user_id').notNull(),
  legacyCounterId: integer('legacy_counter_id').notNull(),
  legacyCounterSessionId: integer('legacy_counter_session_id').notNull(),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  reconciliationGuard: integer('reconciliation_guard').notNull().default(1),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_note_cash_refund_reversals_public_id').on(table.tenantId, table.reversalPublicId),
  uniqueIndex('uq_canonical_credit_note_cash_refund_reversals_key').on(table.tenantId, table.idempotencyKey),
  uniqueIndex('uq_canonical_credit_note_cash_refund_reversals_refund').on(table.tenantId, table.refundPublicId),
  index('idx_canonical_credit_note_cash_refund_reversals_invoice').on(table.tenantId, table.invoicePublicId, table.reversedAtUtc),
  index('idx_canonical_credit_note_cash_refund_reversals_counter').on(table.tenantId, table.legacyCounterSessionId, table.reversedAtUtc),
  foreignKey({ name: 'fk_canonical_credit_note_cash_refund_reversals_refund', columns: [table.tenantId, table.refundPublicId], foreignColumns: [canonicalCreditNoteCashRefunds.tenantId, canonicalCreditNoteCashRefunds.refundPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_cash_refund_reversals_note', columns: [table.tenantId, table.creditNotePublicId], foreignColumns: [canonicalCreditNotes.tenantId, canonicalCreditNotes.creditNotePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_cash_refund_reversals_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  check('canonical_credit_note_cash_refund_reversals_public_id_check', sql`length(trim(reversal_public_id)) > 0`),
  check('canonical_credit_note_cash_refund_reversals_key_check', sql`length(trim(idempotency_key)) > 0`),
  check('canonical_credit_note_cash_refund_reversals_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_note_cash_refund_reversals_credit_total_check', sql`credit_total_minor BETWEEN amount_minor AND 9007199254740991`),
  check('canonical_credit_note_cash_refund_reversals_currency_check', sql`length(currency_code) = 3 AND currency_code = upper(currency_code)`),
  check('canonical_credit_note_cash_refund_reversals_reason_check', sql`length(trim(reason_code)) > 0`),
  check('canonical_credit_note_cash_refund_reversals_reversed_check', sql`substr(reversed_at_utc, -1) = 'Z'`),
  check('canonical_credit_note_cash_refund_reversals_business_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_credit_note_cash_refund_reversals_actor_check', sql`actor_user_id > 0`),
  check('canonical_credit_note_cash_refund_reversals_counter_check', sql`legacy_counter_id > 0 AND legacy_counter_session_id > 0`),
  check('canonical_credit_note_cash_refund_reversals_evidence_check', sql`length(source_evidence_sha256) = 64`),
  check('canonical_credit_note_cash_refund_reversals_reconciliation_guard', sql`reconciliation_guard = 1`),
]);

export const canonicalCreditNoteRefundReceipts = sqliteTable('canonical_credit_note_refund_receipts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  receiptSlicePublicId: text('receipt_slice_public_id').notNull(),
  refundPublicId: text('refund_public_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  receiptRefundedBeforeMinor: integer('receipt_refunded_before_minor').notNull(),
  receiptRefundedAfterMinor: integer('receipt_refunded_after_minor').notNull(),
  receiptNetReceivedBeforeMinor: integer('receipt_net_received_before_minor').notNull(),
  receiptNetReceivedAfterMinor: integer('receipt_net_received_after_minor').notNull(),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_note_refund_receipts_public_id').on(table.tenantId, table.receiptSlicePublicId),
  uniqueIndex('uq_canonical_credit_note_refund_receipts_source').on(table.tenantId, table.refundPublicId, table.receiptPublicId),
  uniqueIndex('uq_canonical_credit_note_refund_receipts_parent_slice').on(table.tenantId, table.refundPublicId, table.receiptSlicePublicId),
  index('idx_canonical_credit_note_refund_receipts_refund').on(table.tenantId, table.refundPublicId, table.id),
  index('idx_canonical_credit_note_refund_receipts_source').on(table.tenantId, table.receiptPublicId, table.id),
  foreignKey({ name: 'fk_canonical_credit_note_refund_receipts_refund', columns: [table.tenantId, table.refundPublicId], foreignColumns: [canonicalCreditNoteCashRefunds.tenantId, canonicalCreditNoteCashRefunds.refundPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_refund_receipts_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  check('canonical_credit_note_refund_receipts_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_note_refund_receipts_refunded_before_check', sql`receipt_refunded_before_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_credit_note_refund_receipts_refunded_math_check', sql`receipt_refunded_after_minor = receipt_refunded_before_minor + amount_minor`),
  check('canonical_credit_note_refund_receipts_net_before_check', sql`receipt_net_received_before_minor BETWEEN amount_minor AND 9007199254740991`),
  check('canonical_credit_note_refund_receipts_net_math_check', sql`receipt_net_received_after_minor = receipt_net_received_before_minor - amount_minor`),
  check('canonical_credit_note_refund_receipts_balance_guard', sql`balance_guard = 1`),
  check('canonical_credit_note_refund_receipts_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalCreditNoteRefundAllocations = sqliteTable('canonical_credit_note_refund_allocations', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  allocationSlicePublicId: text('allocation_slice_public_id').notNull(),
  refundPublicId: text('refund_public_id').notNull(),
  receiptSlicePublicId: text('receipt_slice_public_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  allocationPublicId: text('allocation_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  allocationReversedBeforeMinor: integer('allocation_reversed_before_minor').notNull(),
  allocationReversedAfterMinor: integer('allocation_reversed_after_minor').notNull(),
  allocationRemainingBeforeMinor: integer('allocation_remaining_before_minor').notNull(),
  allocationRemainingAfterMinor: integer('allocation_remaining_after_minor').notNull(),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_note_refund_allocations_public_id').on(table.tenantId, table.allocationSlicePublicId),
  uniqueIndex('uq_canonical_credit_note_refund_allocations_source').on(table.tenantId, table.refundPublicId, table.allocationPublicId),
  index('idx_canonical_credit_note_refund_allocations_refund').on(table.tenantId, table.refundPublicId, table.id),
  index('idx_canonical_credit_note_refund_allocations_source').on(table.tenantId, table.allocationPublicId, table.id),
  foreignKey({ name: 'fk_canonical_credit_note_refund_allocations_receipt_slice', columns: [table.tenantId, table.refundPublicId, table.receiptSlicePublicId], foreignColumns: [canonicalCreditNoteRefundReceipts.tenantId, canonicalCreditNoteRefundReceipts.refundPublicId, canonicalCreditNoteRefundReceipts.receiptSlicePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_refund_allocations_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_refund_allocations_allocation', columns: [table.tenantId, table.allocationPublicId], foreignColumns: [canonicalPaymentAllocations.tenantId, canonicalPaymentAllocations.allocationPublicId] }).onDelete('restrict'),
  check('canonical_credit_note_refund_allocations_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_note_refund_allocations_reversed_before_check', sql`allocation_reversed_before_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_credit_note_refund_allocations_reversed_math_check', sql`allocation_reversed_after_minor = allocation_reversed_before_minor + amount_minor`),
  check('canonical_credit_note_refund_allocations_remaining_before_check', sql`allocation_remaining_before_minor BETWEEN amount_minor AND 9007199254740991`),
  check('canonical_credit_note_refund_allocations_remaining_math_check', sql`allocation_remaining_after_minor = allocation_remaining_before_minor - amount_minor`),
  check('canonical_credit_note_refund_allocations_balance_guard', sql`balance_guard = 1`),
  check('canonical_credit_note_refund_allocations_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalCreditNoteRefundTenderAttributions = sqliteTable('canonical_credit_note_refund_tender_attributions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  tenderAttributionPublicId: text('tender_attribution_public_id').notNull(),
  refundPublicId: text('refund_public_id').notNull(),
  receiptSlicePublicId: text('receipt_slice_public_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  tenderPublicId: text('tender_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  originalTenderType: text('original_tender_type').notNull(),
  originalMethodCode: text('original_method_code').notNull(),
  attributableBeforeMinor: integer('attributable_before_minor').notNull(),
  attributableAfterMinor: integer('attributable_after_minor').notNull(),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_credit_note_refund_tender_attr_public_id').on(table.tenantId, table.tenderAttributionPublicId),
  uniqueIndex('uq_canonical_credit_note_refund_tender_attr_source').on(table.tenantId, table.refundPublicId, table.tenderPublicId),
  index('idx_canonical_credit_note_refund_tender_attr_refund').on(table.tenantId, table.refundPublicId, table.id),
  index('idx_canonical_credit_note_refund_tender_attr_source').on(table.tenantId, table.tenderPublicId, table.id),
  foreignKey({ name: 'fk_canonical_credit_note_refund_tender_attr_receipt_slice', columns: [table.tenantId, table.refundPublicId, table.receiptSlicePublicId], foreignColumns: [canonicalCreditNoteRefundReceipts.tenantId, canonicalCreditNoteRefundReceipts.refundPublicId, canonicalCreditNoteRefundReceipts.receiptSlicePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_refund_tender_attr_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_credit_note_refund_tender_attr_tender', columns: [table.tenantId, table.tenderPublicId], foreignColumns: [canonicalPaymentTenders.tenantId, canonicalPaymentTenders.tenderPublicId] }).onDelete('restrict'),
  check('canonical_credit_note_refund_tender_attr_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_credit_note_refund_tender_attr_type_check', sql`original_tender_type IN ('cash','card','mobile_wallet','bank_transfer','gateway','other')`),
  check('canonical_credit_note_refund_tender_attr_method_check', sql`length(trim(original_method_code)) > 0`),
  check('canonical_credit_note_refund_tender_attr_before_check', sql`attributable_before_minor BETWEEN amount_minor AND 9007199254740991`),
  check('canonical_credit_note_refund_tender_attr_math_check', sql`attributable_after_minor = attributable_before_minor - amount_minor`),
  check('canonical_credit_note_refund_tender_attr_balance_guard', sql`balance_guard = 1`),
  check('canonical_credit_note_refund_tender_attr_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalPaymentReversals = sqliteTable('canonical_payment_reversals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  reversalPublicId: text('reversal_public_id').notNull(),
  receiptPublicId: text('receipt_public_id').notNull(),
  tenderPublicId: text('tender_public_id').notNull(),
  allocationPublicId: text('allocation_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  reasonCode: text('reason_code').notNull(),
  status: text('status').notNull().default('posted'),
  reversedAtUtc: text('reversed_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  allocationReversedBeforeMinor: integer('allocation_reversed_before_minor').notNull(),
  allocationReversedAfterMinor: integer('allocation_reversed_after_minor').notNull(),
  tenderReversedBeforeMinor: integer('tender_reversed_before_minor').notNull(),
  tenderReversedAfterMinor: integer('tender_reversed_after_minor').notNull(),
  receiptRefundedBeforeMinor: integer('receipt_refunded_before_minor').notNull(),
  receiptRefundedAfterMinor: integer('receipt_refunded_after_minor').notNull(),
  invoicePaidBeforeMinor: integer('invoice_paid_before_minor').notNull(),
  invoicePaidAfterMinor: integer('invoice_paid_after_minor').notNull(),
  invoiceDueBeforeMinor: integer('invoice_due_before_minor').notNull(),
  invoiceDueAfterMinor: integer('invoice_due_after_minor').notNull(),
  invoiceNetDueBeforeMinor: integer('invoice_net_due_before_minor').notNull(),
  invoiceNetDueAfterMinor: integer('invoice_net_due_after_minor').notNull(),
  compensationGuard: integer('compensation_guard').notNull().default(1),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_payment_reversals_public_id').on(table.tenantId, table.reversalPublicId),
  index('idx_canonical_payment_reversals_receipt').on(table.tenantId, table.receiptPublicId, table.reversedAtUtc),
  index('idx_canonical_payment_reversals_allocation').on(table.tenantId, table.allocationPublicId, table.reversedAtUtc),
  foreignKey({ name: 'fk_canonical_payment_reversals_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_payment_reversals_tender', columns: [table.tenantId, table.tenderPublicId], foreignColumns: [canonicalPaymentTenders.tenantId, canonicalPaymentTenders.tenderPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_payment_reversals_allocation', columns: [table.tenantId, table.allocationPublicId], foreignColumns: [canonicalPaymentAllocations.tenantId, canonicalPaymentAllocations.allocationPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_payment_reversals_invoice', columns: [table.tenantId, table.invoicePublicId], foreignColumns: [canonicalInvoices.tenantId, canonicalInvoices.invoicePublicId] }).onDelete('restrict'),
  check('canonical_payment_reversals_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_payment_reversals_allocation_math_check', sql`allocation_reversed_after_minor = allocation_reversed_before_minor + amount_minor`),
  check('canonical_payment_reversals_tender_math_check', sql`tender_reversed_after_minor = tender_reversed_before_minor + amount_minor`),
  check('canonical_payment_reversals_receipt_math_check', sql`receipt_refunded_after_minor = receipt_refunded_before_minor + amount_minor`),
  check('canonical_payment_reversals_paid_math_check', sql`invoice_paid_after_minor = invoice_paid_before_minor - amount_minor`),
  check('canonical_payment_reversals_due_math_check', sql`invoice_due_after_minor = invoice_due_before_minor + amount_minor`),
  check('canonical_payment_reversals_net_due_math_check', sql`invoice_net_due_after_minor = invoice_net_due_before_minor + amount_minor`),
  check('canonical_payment_reversals_compensation_guard', sql`compensation_guard = 1`),
  check('canonical_payment_reversals_balance_guard', sql`balance_guard = 1`),
  check('canonical_payment_reversals_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);

export const canonicalRefunds = sqliteTable('canonical_refunds', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  refundPublicId: text('refund_public_id').notNull(),
  sourceType: text('source_type').notNull(),
  depositPublicId: text('deposit_public_id'),
  receiptPublicId: text('receipt_public_id'),
  tenderPublicId: text('tender_public_id'),
  allocationPublicId: text('allocation_public_id'),
  paymentReversalPublicId: text('payment_reversal_public_id'),
  amountMinor: integer('amount_minor').notNull(),
  tenderType: text('tender_type').notNull(),
  methodCode: text('method_code').notNull(),
  status: text('status').notNull(),
  refundedAtUtc: text('refunded_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  sourceAvailableBeforeMinor: integer('source_available_before_minor'),
  sourceAvailableAfterMinor: integer('source_available_after_minor'),
  liabilityGuard: integer('liability_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_refunds_public_id').on(table.tenantId, table.refundPublicId),
  uniqueIndex('uq_canonical_refunds_payment_reversal')
    .on(table.tenantId, table.paymentReversalPublicId)
    .where(sql`${table.paymentReversalPublicId} IS NOT NULL`),
  index('idx_canonical_refunds_source').on(table.tenantId, table.sourceType, table.status, table.refundedAtUtc),
  index('idx_canonical_refunds_deposit')
    .on(table.tenantId, table.depositPublicId, table.status)
    .where(sql`${table.depositPublicId} IS NOT NULL`),
  foreignKey({ name: 'fk_canonical_refunds_deposit', columns: [table.tenantId, table.depositPublicId], foreignColumns: [canonicalDeposits.tenantId, canonicalDeposits.depositPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_refunds_receipt', columns: [table.tenantId, table.receiptPublicId], foreignColumns: [canonicalPaymentReceipts.tenantId, canonicalPaymentReceipts.receiptPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_refunds_tender', columns: [table.tenantId, table.tenderPublicId], foreignColumns: [canonicalPaymentTenders.tenantId, canonicalPaymentTenders.tenderPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_refunds_allocation', columns: [table.tenantId, table.allocationPublicId], foreignColumns: [canonicalPaymentAllocations.tenantId, canonicalPaymentAllocations.allocationPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_refunds_payment_reversal', columns: [table.tenantId, table.paymentReversalPublicId], foreignColumns: [canonicalPaymentReversals.tenantId, canonicalPaymentReversals.reversalPublicId] }).onDelete('restrict'),
  check('canonical_refunds_source_type_check', sql`source_type IN ('deposit','payment')`),
  check('canonical_refunds_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_refunds_tender_type_check', sql`tender_type IN ('cash','card','mobile_wallet','bank_transfer','gateway','other')`),
  check('canonical_refunds_status_check', sql`status IN ('posted','reversed')`),
  check('canonical_refunds_liability_guard', sql`liability_guard = 1`),
  check('canonical_refunds_evidence_check', sql`length(source_evidence_sha256) = 64`),
]);
