import { sql } from 'drizzle-orm';
import { check, foreignKey, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { canonicalPractitioners } from './identity';
import { canonicalInvoiceLines } from './billing';
import { canonicalServiceEvents } from './service-operations';
import { canonicalServiceCatalogItems } from './services';

const utcNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const canonicalCompensationRules = sqliteTable('canonical_compensation_rules', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  rulePublicId: text('rule_public_id').notNull(),
  ruleVersion: integer('rule_version').notNull(),
  scopeType: text('scope_type').notNull(),
  servicePublicId: text('service_public_id'),
  categoryKey: text('category_key'),
  practitionerPublicId: text('practitioner_public_id'),
  practitionerRole: text('practitioner_role').notNull(),
  accrualStage: text('accrual_stage').notNull(),
  rateType: text('rate_type').notNull(),
  rateValue: integer('rate_value').notNull(),
  waiverPolicy: text('waiver_policy').notNull().default('full_earned'),
  protectedRateValue: integer('protected_rate_value').notNull().default(0),
  calculationBasis: text('calculation_basis').notNull(),
  discountTreatment: text('discount_treatment').notNull(),
  taxTreatment: text('tax_treatment').notNull(),
  minimumMinor: integer('minimum_minor').notNull().default(0),
  capMinor: integer('cap_minor'),
  priority: integer('priority').notNull().default(100),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_compensation_rules_version').on(table.tenantId, table.rulePublicId, table.ruleVersion),
  index('idx_canonical_compensation_rules_lookup').on(
    table.tenantId,
    table.scopeType,
    table.servicePublicId,
    table.categoryKey,
    table.practitionerPublicId,
    table.practitionerRole,
    table.status,
    table.effectiveFrom,
    table.effectiveTo,
    table.priority,
  ),
  foreignKey({
    name: 'fk_canonical_compensation_rules_service',
    columns: [table.tenantId, table.servicePublicId],
    foreignColumns: [canonicalServiceCatalogItems.tenantId, canonicalServiceCatalogItems.servicePublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_rules_practitioner',
    columns: [table.tenantId, table.practitionerPublicId],
    foreignColumns: [canonicalPractitioners.tenantId, canonicalPractitioners.practitionerPublicId],
  }).onDelete('restrict'),
  check('canonical_compensation_rules_scope_check', sql`(scope_type='service' AND service_public_id IS NOT NULL AND category_key IS NULL) OR (scope_type='category' AND service_public_id IS NULL AND category_key IS NOT NULL) OR (scope_type='all' AND service_public_id IS NULL AND category_key IS NULL)`),
  check('canonical_compensation_rules_version_check', sql`rule_version > 0`),
  check('canonical_compensation_rules_role_check', sql`practitioner_role IN ('performing','referring','prescribing','treating','reporting')`),
  check('canonical_compensation_rules_stage_check', sql`accrual_stage IN ('performer_reserve','commission','professional_fee')`),
  check('canonical_compensation_rules_rate_type_check', sql`rate_type IN ('fixed','basis_points')`),
  check('canonical_compensation_rules_rate_value_check', sql`rate_value BETWEEN 0 AND 9007199254740991 AND (rate_type <> 'basis_points' OR rate_value <= 10000)`),
  check('canonical_compensation_rules_basis_check', sql`calculation_basis IN ('gross','net_after_discount','remaining_after_performer','collected')`),
  check('canonical_compensation_rules_discount_check', sql`discount_treatment IN ('deduct','ignore')`),
  check('canonical_compensation_rules_tax_check', sql`tax_treatment IN ('include','exclude')`),
  check('canonical_compensation_rules_minimum_check', sql`minimum_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_compensation_rules_cap_check', sql`cap_minor IS NULL OR cap_minor BETWEEN minimum_minor AND 9007199254740991`),
  check('canonical_compensation_rules_priority_check', sql`priority >= 0`),
  check('canonical_compensation_rules_period_check', sql`effective_to IS NULL OR effective_to >= effective_from`),
  check('canonical_compensation_rules_status_check', sql`status IN ('active','inactive','retired')`),
  check('canonical_compensation_rules_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationAccruals = sqliteTable('canonical_compensation_accruals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  accrualPublicId: text('accrual_public_id').notNull(),
  invoicePublicId: text('invoice_public_id').notNull(),
  invoiceLinePublicId: text('invoice_line_public_id').notNull(),
  serviceEventPublicId: text('service_event_public_id'),
  practitionerPublicId: text('practitioner_public_id'),
  practitionerRole: text('practitioner_role').notNull(),
  accrualStage: text('accrual_stage').notNull(),
  rulePublicId: text('rule_public_id').notNull(),
  ruleVersion: integer('rule_version').notNull(),
  calculationBasis: text('calculation_basis').notNull(),
  rateType: text('rate_type').notNull(),
  rateValue: integer('rate_value').notNull(),
  currencyCode: text('currency_code').notNull(),
  grossMinor: integer('gross_minor').notNull(),
  discountMinor: integer('discount_minor').notNull(),
  taxMinor: integer('tax_minor').notNull(),
  performerReserveMinor: integer('performer_reserve_minor').notNull(),
  eligibleBaseMinor: integer('eligible_base_minor').notNull(),
  earnedMinor: integer('earned_minor').notNull(),
  protectedMinor: integer('protected_minor').notNull().default(0),
  waiverCapacityMinor: integer('waiver_capacity_minor').notNull().default(0),
  requestedWaiverMinor: integer('requested_waiver_minor').notNull().default(0),
  hospitalFundedOverflowMinor: integer('hospital_funded_overflow_minor').notNull().default(0),
  adjustedMinor: integer('adjusted_minor').notNull().default(0),
  settledMinor: integer('settled_minor').notNull().default(0),
  payableMinor: integer('payable_minor').notNull(),
  status: text('status').notNull(),
  accruedAtUtc: text('accrued_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  payableProjectionGuard: integer('payable_projection_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_compensation_accruals_public_id').on(table.tenantId, table.accrualPublicId),
  uniqueIndex('uq_canonical_compensation_accruals_assigned')
    .on(
      table.tenantId,
      table.invoiceLinePublicId,
      table.practitionerPublicId,
      table.practitionerRole,
      table.rulePublicId,
      table.ruleVersion,
      table.sourceEvidenceSha256,
    )
    .where(sql`${table.practitionerPublicId} IS NOT NULL`),
  uniqueIndex('uq_canonical_compensation_accruals_unassigned')
    .on(
      table.tenantId,
      table.invoiceLinePublicId,
      table.practitionerRole,
      table.rulePublicId,
      table.ruleVersion,
      table.sourceEvidenceSha256,
    )
    .where(sql`${table.practitionerPublicId} IS NULL`),
  index('idx_canonical_compensation_accruals_payable').on(
    table.tenantId,
    table.practitionerPublicId,
    table.status,
    table.businessDate,
  ),
  foreignKey({
    name: 'fk_canonical_compensation_accruals_invoice_line',
    columns: [table.tenantId, table.invoicePublicId, table.invoiceLinePublicId],
    foreignColumns: [canonicalInvoiceLines.tenantId, canonicalInvoiceLines.invoicePublicId, canonicalInvoiceLines.linePublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_accruals_service_event',
    columns: [table.tenantId, table.serviceEventPublicId],
    foreignColumns: [canonicalServiceEvents.tenantId, canonicalServiceEvents.eventPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_accruals_practitioner',
    columns: [table.tenantId, table.practitionerPublicId],
    foreignColumns: [canonicalPractitioners.tenantId, canonicalPractitioners.practitionerPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_accruals_rule',
    columns: [table.tenantId, table.rulePublicId, table.ruleVersion],
    foreignColumns: [canonicalCompensationRules.tenantId, canonicalCompensationRules.rulePublicId, canonicalCompensationRules.ruleVersion],
  }).onDelete('restrict'),
  check('canonical_compensation_accruals_role_check', sql`practitioner_role IN ('performing','referring','prescribing','treating','reporting')`),
  check('canonical_compensation_accruals_stage_check', sql`accrual_stage IN ('performer_reserve','commission','professional_fee')`),
  check('canonical_compensation_accruals_basis_check', sql`calculation_basis IN ('gross','net_after_discount','remaining_after_performer','collected')`),
  check('canonical_compensation_accruals_rate_check', sql`rate_type IN ('fixed','basis_points') AND rate_value BETWEEN 0 AND 9007199254740991`),
  check('canonical_compensation_accruals_currency_check', sql`length(currency_code)=3 AND currency_code=upper(currency_code)`),
  check('canonical_compensation_accruals_money_check', sql`gross_minor BETWEEN 0 AND 9007199254740991 AND discount_minor BETWEEN 0 AND gross_minor AND tax_minor BETWEEN 0 AND 9007199254740991 AND performer_reserve_minor BETWEEN 0 AND gross_minor AND eligible_base_minor BETWEEN 0 AND 9007199254740991 AND earned_minor BETWEEN 0 AND 9007199254740991 AND adjusted_minor BETWEEN 0 AND earned_minor AND settled_minor BETWEEN 0 AND earned_minor-adjusted_minor AND payable_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_compensation_accruals_payable_projection_guard', sql`payable_projection_guard=1 AND payable_minor=earned_minor-adjusted_minor-settled_minor`),
  check('canonical_compensation_accruals_status_check', sql`status IN ('unassigned','accrued','partially_settled','settled','reversed')`),
  check('canonical_compensation_accruals_lifecycle_check', sql`(status='unassigned' AND practitioner_public_id IS NULL AND settled_minor=0) OR (status='accrued' AND practitioner_public_id IS NOT NULL AND settled_minor=0 AND payable_minor>0) OR (status='partially_settled' AND practitioner_public_id IS NOT NULL AND settled_minor>0 AND payable_minor>0) OR (status='settled' AND practitioner_public_id IS NOT NULL AND payable_minor=0) OR (status='reversed' AND payable_minor=0)`),
  check('canonical_compensation_accruals_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationReportingContext = sqliteTable('canonical_compensation_reporting_context', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  accrualPublicId: text('accrual_public_id').notNull(),
  sourceKind: text('source_kind').notNull(),
  incentiveType: text('incentive_type'),
  legacyBillId: integer('legacy_bill_id'),
  legacyInvoiceItemId: integer('legacy_invoice_item_id'),
  legacyLabOrderItemId: integer('legacy_lab_order_item_id'),
  detailName: text('detail_name'),
  sourceReference: text('source_reference'),
  waiverReason: text('waiver_reason'),
  doctorWaiverMinor: integer('doctor_waiver_minor').notNull().default(0),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_compensation_reporting_context_accrual').on(table.tenantId, table.accrualPublicId),
  index('idx_canonical_compensation_reporting_context_source').on(
    table.tenantId,
    table.sourceKind,
    table.incentiveType,
    table.legacyBillId,
    table.legacyInvoiceItemId,
  ),
  index('idx_canonical_compensation_reporting_context_lab_item')
    .on(table.tenantId, table.legacyLabOrderItemId)
    .where(sql`${table.legacyLabOrderItemId} IS NOT NULL`),
  foreignKey({
    name: 'fk_canonical_compensation_reporting_context_accrual',
    columns: [table.tenantId, table.accrualPublicId],
    foreignColumns: [canonicalCompensationAccruals.tenantId, canonicalCompensationAccruals.accrualPublicId],
  }).onDelete('restrict'),
  check('canonical_compensation_reporting_context_source_check', sql`length(trim(source_kind)) > 0`),
  check('canonical_compensation_reporting_context_ids_check', sql`(legacy_bill_id IS NULL OR legacy_bill_id > 0) AND (legacy_invoice_item_id IS NULL OR legacy_invoice_item_id > 0) AND (legacy_lab_order_item_id IS NULL OR legacy_lab_order_item_id > 0)`),
  check('canonical_compensation_reporting_context_waiver_check', sql`doctor_waiver_minor BETWEEN 0 AND 9007199254740991`),
  check('canonical_compensation_reporting_context_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationSettlements = sqliteTable('canonical_compensation_settlements', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  settlementPublicId: text('settlement_public_id').notNull(),
  settlementNumber: text('settlement_number').notNull(),
  practitionerPublicId: text('practitioner_public_id').notNull(),
  currencyCode: text('currency_code').notNull(),
  paymentMethod: text('payment_method').notNull(),
  totalMinor: integer('total_minor').notNull(),
  allocatedMinor: integer('allocated_minor').notNull(),
  reversedMinor: integer('reversed_minor').notNull().default(0),
  netPaidMinor: integer('net_paid_minor').notNull(),
  status: text('status').notNull(),
  settledAtUtc: text('settled_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  settlementProjectionGuard: integer('settlement_projection_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_compensation_settlements_public_id').on(table.tenantId, table.settlementPublicId),
  uniqueIndex('uq_canonical_compensation_settlements_number').on(table.tenantId, table.settlementNumber),
  index('idx_canonical_compensation_settlements_practitioner').on(
    table.tenantId,
    table.practitionerPublicId,
    table.status,
    table.businessDate,
  ),
  foreignKey({
    name: 'fk_canonical_compensation_settlements_practitioner',
    columns: [table.tenantId, table.practitionerPublicId],
    foreignColumns: [canonicalPractitioners.tenantId, canonicalPractitioners.practitionerPublicId],
  }).onDelete('restrict'),
  check('canonical_compensation_settlements_number_check', sql`length(trim(settlement_number))>0`),
  check('canonical_compensation_settlements_currency_check', sql`length(currency_code)=3 AND currency_code=upper(currency_code)`),
  check('canonical_compensation_settlements_method_check', sql`payment_method IN ('cash','bank_transfer','mobile_wallet','card','other')`),
  check('canonical_compensation_settlements_money_check', sql`total_minor BETWEEN 1 AND 9007199254740991 AND allocated_minor=total_minor AND reversed_minor BETWEEN 0 AND total_minor`),
  check('canonical_compensation_settlements_settlement_projection_guard', sql`settlement_projection_guard=1 AND net_paid_minor=total_minor-reversed_minor`),
  check('canonical_compensation_settlements_status_check', sql`status IN ('posted','partially_reversed','reversed')`),
  check('canonical_compensation_settlements_lifecycle_check', sql`(status='posted' AND reversed_minor=0 AND reversed_at_utc IS NULL) OR (status='partially_reversed' AND reversed_minor>0 AND reversed_minor<total_minor AND reversed_at_utc IS NOT NULL) OR (status='reversed' AND reversed_minor=total_minor AND reversed_at_utc IS NOT NULL)`),
  check('canonical_compensation_settlements_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationSettlementAllocations = sqliteTable('canonical_compensation_settlement_allocations', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  allocationPublicId: text('allocation_public_id').notNull(),
  settlementPublicId: text('settlement_public_id').notNull(),
  accrualPublicId: text('accrual_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  reversedMinor: integer('reversed_minor').notNull().default(0),
  remainingMinor: integer('remaining_minor').notNull(),
  accrualSettledBeforeMinor: integer('accrual_settled_before_minor').notNull(),
  accrualSettledAfterMinor: integer('accrual_settled_after_minor').notNull(),
  accrualPayableBeforeMinor: integer('accrual_payable_before_minor').notNull(),
  accrualPayableAfterMinor: integer('accrual_payable_after_minor').notNull(),
  status: text('status').notNull().default('active'),
  allocatedAtUtc: text('allocated_at_utc').notNull(),
  reversedAtUtc: text('reversed_at_utc'),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_compensation_settlement_allocations_public_id').on(table.tenantId, table.allocationPublicId),
  uniqueIndex('uq_canonical_compensation_settlement_allocations_accrual').on(
    table.tenantId,
    table.settlementPublicId,
    table.accrualPublicId,
  ),
  index('idx_canonical_compensation_settlement_allocations_accrual').on(table.tenantId, table.accrualPublicId, table.status),
  foreignKey({
    name: 'fk_canonical_compensation_settlement_allocations_settlement',
    columns: [table.tenantId, table.settlementPublicId],
    foreignColumns: [canonicalCompensationSettlements.tenantId, canonicalCompensationSettlements.settlementPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_settlement_allocations_accrual',
    columns: [table.tenantId, table.accrualPublicId],
    foreignColumns: [canonicalCompensationAccruals.tenantId, canonicalCompensationAccruals.accrualPublicId],
  }).onDelete('restrict'),
  check('canonical_compensation_settlement_allocations_money_check', sql`amount_minor BETWEEN 1 AND 9007199254740991 AND reversed_minor BETWEEN 0 AND amount_minor AND remaining_minor=amount_minor-reversed_minor`),
  check('canonical_compensation_settlement_allocations_balance_math_check', sql`accrual_settled_after_minor=accrual_settled_before_minor+amount_minor AND accrual_payable_after_minor=accrual_payable_before_minor-amount_minor`),
  check('canonical_compensation_settlement_allocations_balance_guard', sql`balance_guard=1`),
  check('canonical_compensation_settlement_allocations_status_check', sql`status IN ('active','partially_reversed','reversed')`),
  check('canonical_compensation_settlement_allocations_lifecycle_check', sql`(status='active' AND reversed_minor=0 AND reversed_at_utc IS NULL) OR (status='partially_reversed' AND reversed_minor>0 AND reversed_minor<amount_minor AND reversed_at_utc IS NOT NULL) OR (status='reversed' AND reversed_minor=amount_minor AND reversed_at_utc IS NOT NULL)`),
  check('canonical_compensation_settlement_allocations_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationAdjustments = sqliteTable('canonical_compensation_adjustments', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  adjustmentPublicId: text('adjustment_public_id').notNull(),
  accrualPublicId: text('accrual_public_id').notNull(),
  settlementPublicId: text('settlement_public_id'),
  settlementAllocationPublicId: text('settlement_allocation_public_id'),
  adjustmentType: text('adjustment_type').notNull(),
  reasonCode: text('reason_code').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  accrualAdjustedBeforeMinor: integer('accrual_adjusted_before_minor').notNull(),
  accrualAdjustedAfterMinor: integer('accrual_adjusted_after_minor').notNull(),
  accrualSettledBeforeMinor: integer('accrual_settled_before_minor').notNull(),
  accrualSettledAfterMinor: integer('accrual_settled_after_minor').notNull(),
  accrualPayableBeforeMinor: integer('accrual_payable_before_minor').notNull(),
  accrualPayableAfterMinor: integer('accrual_payable_after_minor').notNull(),
  occurredAtUtc: text('occurred_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_compensation_adjustments_public_id').on(table.tenantId, table.adjustmentPublicId),
  index('idx_canonical_compensation_adjustments_accrual').on(table.tenantId, table.accrualPublicId, table.occurredAtUtc),
  foreignKey({
    name: 'fk_canonical_compensation_adjustments_accrual',
    columns: [table.tenantId, table.accrualPublicId],
    foreignColumns: [canonicalCompensationAccruals.tenantId, canonicalCompensationAccruals.accrualPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_adjustments_settlement',
    columns: [table.tenantId, table.settlementPublicId],
    foreignColumns: [canonicalCompensationSettlements.tenantId, canonicalCompensationSettlements.settlementPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_compensation_adjustments_settlement_allocation',
    columns: [table.tenantId, table.settlementAllocationPublicId],
    foreignColumns: [canonicalCompensationSettlementAllocations.tenantId, canonicalCompensationSettlementAllocations.allocationPublicId],
  }).onDelete('restrict'),
  check('canonical_compensation_adjustments_type_check', sql`adjustment_type IN ('credit','refund','service_cancellation','settlement_reversal','manual_recovery')`),
  check('canonical_compensation_adjustments_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_compensation_adjustments_balance_guard', sql`balance_guard=1`),
  check('canonical_compensation_adjustments_shape_check', sql`(adjustment_type<>'settlement_reversal' AND settlement_public_id IS NULL AND settlement_allocation_public_id IS NULL AND accrual_adjusted_after_minor=accrual_adjusted_before_minor+amount_minor AND accrual_settled_after_minor=accrual_settled_before_minor AND accrual_payable_after_minor=accrual_payable_before_minor-amount_minor) OR (adjustment_type='settlement_reversal' AND settlement_public_id IS NOT NULL AND settlement_allocation_public_id IS NOT NULL AND accrual_adjusted_after_minor=accrual_adjusted_before_minor AND accrual_settled_after_minor=accrual_settled_before_minor-amount_minor AND accrual_payable_after_minor=accrual_payable_before_minor+amount_minor)`),
  check('canonical_compensation_adjustments_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationRefundReservations = sqliteTable('canonical_compensation_refund_reservations', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  reservationPublicId: text('reservation_public_id').notNull(),
  accrualPublicId: text('accrual_public_id').notNull(),
  adjustmentPublicId: text('adjustment_public_id').notNull(),
  refundSourcePublicId: text('refund_source_public_id').notNull(),
  legacyApprovalRequestId: integer('legacy_approval_request_id'),
  legacyAccrualId: integer('legacy_accrual_id').notNull(),
  originalBaseMinor: integer('original_base_minor').notNull(),
  reservedBaseMinor: integer('reserved_base_minor').notNull(),
  originalEarnedMinor: integer('original_earned_minor').notNull(),
  reservedEarnedMinor: integer('reserved_earned_minor').notNull(),
  originalWaiverMinor: integer('original_waiver_minor').notNull(),
  reservedWaiverMinor: integer('reserved_waiver_minor').notNull(),
  originalPayableMinor: integer('original_payable_minor').notNull(),
  reservedPayableMinor: integer('reserved_payable_minor').notNull(),
  paidMinor: integer('paid_minor').notNull(),
  reversalMinor: integer('reversal_minor').notNull(),
  status: text('status').notNull().default('held'),
  reversalPublicId: text('reversal_public_id'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  resolvedAtUtc: text('resolved_at_utc'),
}, (table) => [
  uniqueIndex('uq_canonical_comp_refund_reservation_public_id').on(table.tenantId, table.reservationPublicId),
  uniqueIndex('uq_canonical_comp_refund_reservation_source').on(
    table.tenantId,
    table.accrualPublicId,
    table.refundSourcePublicId,
  ),
  index('idx_canonical_comp_refund_reservation_active').on(
    table.tenantId,
    table.accrualPublicId,
    table.status,
    table.id,
  ),
  index('idx_canonical_comp_refund_reservation_approval')
    .on(table.tenantId, table.legacyApprovalRequestId, table.status)
    .where(sql`${table.legacyApprovalRequestId} IS NOT NULL`),
  foreignKey({
    name: 'fk_canonical_comp_refund_reservation_accrual',
    columns: [table.tenantId, table.accrualPublicId],
    foreignColumns: [canonicalCompensationAccruals.tenantId, canonicalCompensationAccruals.accrualPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_comp_refund_reservation_adjustment',
    columns: [table.tenantId, table.adjustmentPublicId],
    foreignColumns: [canonicalCompensationAdjustments.tenantId, canonicalCompensationAdjustments.adjustmentPublicId],
  }).onDelete('restrict'),
  check('canonical_comp_refund_reservation_source_check', sql`length(trim(refund_source_public_id)) > 0`),
  check('canonical_comp_refund_reservation_ids_check', sql`(legacy_approval_request_id IS NULL OR legacy_approval_request_id > 0) AND legacy_accrual_id > 0`),
  check('canonical_comp_refund_reservation_money_check', sql`original_base_minor BETWEEN 0 AND 9007199254740991 AND reserved_base_minor BETWEEN 0 AND original_base_minor AND original_earned_minor BETWEEN 0 AND 9007199254740991 AND reserved_earned_minor BETWEEN 0 AND original_earned_minor AND original_waiver_minor BETWEEN 0 AND original_earned_minor AND reserved_waiver_minor BETWEEN 0 AND reserved_earned_minor AND original_payable_minor=original_earned_minor-original_waiver_minor AND reserved_payable_minor=reserved_earned_minor-reserved_waiver_minor AND paid_minor BETWEEN 0 AND reserved_payable_minor AND reversal_minor=original_payable_minor-reserved_payable_minor AND reversal_minor > 0`),
  check('canonical_comp_refund_reservation_status_check', sql`status IN ('held','consumed','disputed','released','written_off')`),
  check('canonical_comp_refund_reservation_release_check', sql`(status='released' AND reversal_public_id IS NOT NULL AND resolved_at_utc IS NOT NULL) OR (status<>'released' AND reversal_public_id IS NULL)`),
  check('canonical_comp_refund_reservation_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalCompensationAdjustmentReversals = sqliteTable('canonical_compensation_adjustment_reversals', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  reversalPublicId: text('reversal_public_id').notNull(),
  adjustmentPublicId: text('adjustment_public_id').notNull(),
  accrualPublicId: text('accrual_public_id').notNull(),
  amountMinor: integer('amount_minor').notNull(),
  reasonCode: text('reason_code').notNull(),
  accrualAdjustedBeforeMinor: integer('accrual_adjusted_before_minor').notNull(),
  accrualAdjustedAfterMinor: integer('accrual_adjusted_after_minor').notNull(),
  accrualSettledBeforeMinor: integer('accrual_settled_before_minor').notNull(),
  accrualSettledAfterMinor: integer('accrual_settled_after_minor').notNull(),
  accrualPayableBeforeMinor: integer('accrual_payable_before_minor').notNull(),
  accrualPayableAfterMinor: integer('accrual_payable_after_minor').notNull(),
  occurredAtUtc: text('occurred_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_comp_adjustment_reversal_public_id').on(table.tenantId, table.reversalPublicId),
  uniqueIndex('uq_canonical_comp_adjustment_reversal_adjustment').on(table.tenantId, table.adjustmentPublicId),
  index('idx_canonical_comp_adjustment_reversals_accrual').on(
    table.tenantId,
    table.accrualPublicId,
    table.occurredAtUtc,
  ),
  foreignKey({
    name: 'fk_canonical_comp_adjustment_reversal_adjustment',
    columns: [table.tenantId, table.adjustmentPublicId],
    foreignColumns: [canonicalCompensationAdjustments.tenantId, canonicalCompensationAdjustments.adjustmentPublicId],
  }).onDelete('restrict'),
  foreignKey({
    name: 'fk_canonical_comp_adjustment_reversal_accrual',
    columns: [table.tenantId, table.accrualPublicId],
    foreignColumns: [canonicalCompensationAccruals.tenantId, canonicalCompensationAccruals.accrualPublicId],
  }).onDelete('restrict'),
  check('canonical_comp_adjustment_reversal_amount_check', sql`amount_minor BETWEEN 1 AND 9007199254740991`),
  check('canonical_comp_adjustment_reversal_reason_check', sql`length(trim(reason_code)) > 0`),
  check('canonical_comp_adjustment_reversal_math_check', sql`accrual_adjusted_after_minor=accrual_adjusted_before_minor-amount_minor AND accrual_settled_after_minor=accrual_settled_before_minor AND accrual_payable_after_minor=accrual_payable_before_minor+amount_minor`),
  check('canonical_comp_adjustment_reversal_balance_guard', sql`balance_guard=1`),
  check('canonical_comp_adjustment_reversal_evidence_check', sql`length(source_evidence_sha256)=64`),
]);
