import { sql } from 'drizzle-orm';
import { check, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const utcNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const canonicalEmergencyCases = sqliteTable(
  'canonical_emergency_cases',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    emergencyCasePublicId: text('emergency_case_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    emergencyNumberNamespace: text('emergency_number_namespace'),
    emergencyNumberValue: text('emergency_number_value'),
    currentStatus: text('current_status').notNull().default('arrived'),
    statusVersion: integer('status_version').notNull().default(1),
    currentArrivalAssessmentPublicId: text('current_arrival_assessment_public_id'),
    currentStatusEventPublicId: text('current_status_event_public_id'),
    currentTriageAssessmentPublicId: text('current_triage_assessment_public_id'),
    currentDispositionEventPublicId: text('current_disposition_event_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    idempotencyKey: text('idempotency_key').notNull(),
    requestFingerprintSha256: text('request_fingerprint_sha256').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
    updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_emergency_cases_public_id').on(table.tenantId, table.emergencyCasePublicId),
    uniqueIndex('uq_canonical_emergency_cases_encounter').on(table.tenantId, table.encounterPublicId),
    uniqueIndex('uq_canonical_emergency_cases_idempotency').on(table.tenantId, table.idempotencyKey),
    uniqueIndex('uq_canonical_emergency_cases_number').on(
      table.tenantId,
      table.emergencyNumberNamespace,
      table.emergencyNumberValue,
    ),
    index('idx_canonical_emergency_cases_patient_status').on(
      table.tenantId,
      table.patientLinkPublicId,
      table.currentStatus,
      table.emergencyCasePublicId,
    ),
    index('idx_canonical_emergency_cases_encounter').on(
      table.tenantId,
      table.encounterPublicId,
      table.emergencyCasePublicId,
    ),
    check(
      'canonical_emergency_cases_status_check',
      sql`${table.currentStatus} IN ('arrived','awaiting_triage','triaged','care_in_progress','observation','disposition_pending','admitted','discharged','transferred','lama','dor','death','entered_in_error')`,
    ),
    check('canonical_emergency_cases_version_check', sql`${table.statusVersion} > 0`),
    check(
      'canonical_emergency_cases_number_pair_check',
      sql`(${table.emergencyNumberNamespace} IS NULL) = (${table.emergencyNumberValue} IS NULL)`,
    ),
    check(
      'canonical_emergency_cases_actor_check',
      sql`${table.actorUserPublicId} IS NOT NULL OR ${table.actorSystemKey} IS NOT NULL`,
    ),
  ],
);

export const canonicalEmergencyArrivalAssessments = sqliteTable(
  'canonical_emergency_arrival_assessments',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    arrivalAssessmentPublicId: text('arrival_assessment_public_id').notNull(),
    emergencyCasePublicId: text('emergency_case_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    versionNumber: integer('version_number').notNull(),
    supersedesArrivalAssessmentPublicId: text('supersedes_arrival_assessment_public_id'),
    versionKind: text('version_kind').notNull(),
    arrivalAtUtc: text('arrival_at_utc').notNull(),
    modeOfArrivalCode: text('mode_of_arrival_code').notNull(),
    modeSourceType: text('mode_source_type'),
    modeSourcePublicId: text('mode_source_public_id'),
    referralSourceType: text('referral_source_type'),
    referralSourcePublicId: text('referral_source_public_id'),
    referralSnapshot: text('referral_snapshot'),
    conditionOnArrivalCode: text('condition_on_arrival_code').notNull(),
    conditionSnapshot: text('condition_snapshot'),
    broughtByCategory: text('brought_by_category'),
    broughtByRelationshipCategory: text('brought_by_relationship_category'),
    policeCaseIndicator: integer('police_case_indicator').notNull().default(0),
    actorPractitionerPublicId: text('actor_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    observedAtUtc: text('observed_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code'),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_emergency_arrivals_public_id').on(table.tenantId, table.arrivalAssessmentPublicId),
    uniqueIndex('uq_canonical_emergency_arrivals_scope').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.arrivalAssessmentPublicId,
    ),
    uniqueIndex('uq_canonical_emergency_arrivals_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.versionNumber,
    ),
    uniqueIndex('uq_canonical_emergency_arrivals_replacement').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.supersedesArrivalAssessmentPublicId,
    ),
    index('idx_canonical_emergency_arrivals_case_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.versionNumber,
    ),
    check('canonical_emergency_arrivals_version_check', sql`${table.versionNumber} > 0`),
    check(
      'canonical_emergency_arrivals_kind_check',
      sql`${table.versionKind} IN ('initial','correction','entered_in_error')`,
    ),
    check(
      'canonical_emergency_arrivals_time_check',
      sql`${table.recordedAtUtc} >= ${table.observedAtUtc} AND ${table.arrivalAtUtc} <= ${table.recordedAtUtc}`,
    ),
    check('canonical_emergency_arrivals_police_check', sql`${table.policeCaseIndicator} IN (0,1)`),
  ],
);

export const canonicalEmergencyCaseStatusEvents = sqliteTable(
  'canonical_emergency_case_status_events',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    eventPublicId: text('event_public_id').notNull(),
    emergencyCasePublicId: text('emergency_case_public_id').notNull(),
    fromStatus: text('from_status'),
    toStatus: text('to_status').notNull(),
    eventVersion: integer('event_version').notNull(),
    eventType: text('event_type').notNull(),
    actorPractitionerPublicId: text('actor_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    occurredAtUtc: text('occurred_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_emergency_status_events_public_id').on(table.tenantId, table.eventPublicId),
    uniqueIndex('uq_canonical_emergency_status_events_scope').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.eventPublicId,
    ),
    uniqueIndex('uq_canonical_emergency_status_events_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.eventVersion,
    ),
    index('idx_canonical_emergency_status_events_case_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.eventVersion,
      table.occurredAtUtc,
    ),
    check('canonical_emergency_status_events_version_check', sql`${table.eventVersion} > 0`),
    check(
      'canonical_emergency_status_events_to_status_check',
      sql`${table.toStatus} IN ('arrived','awaiting_triage','triaged','care_in_progress','observation','disposition_pending','admitted','discharged','transferred','lama','dor','death','entered_in_error')`,
    ),
    check('canonical_emergency_status_events_time_check', sql`${table.recordedAtUtc} >= ${table.occurredAtUtc}`),
  ],
);

export const canonicalEmergencyTriageAssessments = sqliteTable(
  'canonical_emergency_triage_assessments',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    triageAssessmentPublicId: text('triage_assessment_public_id').notNull(),
    emergencyCasePublicId: text('emergency_case_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    versionNumber: integer('version_number').notNull(),
    supersedesTriageAssessmentPublicId: text('supersedes_triage_assessment_public_id'),
    versionKind: text('version_kind').notNull(),
    acuityCode: text('acuity_code').notNull(),
    legacyAcuityCode: text('legacy_acuity_code'),
    triagePractitionerPublicId: text('triage_practitioner_public_id').notNull(),
    vitalObservationSetPublicId: text('vital_observation_set_public_id'),
    presentingRiskCode: text('presenting_risk_code'),
    immediateInterventionCode: text('immediate_intervention_code'),
    clinicalRationaleSnapshot: text('clinical_rationale_snapshot'),
    observedAtUtc: text('observed_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code'),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_emergency_triage_public_id').on(table.tenantId, table.triageAssessmentPublicId),
    uniqueIndex('uq_canonical_emergency_triage_scope').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.triageAssessmentPublicId,
    ),
    uniqueIndex('uq_canonical_emergency_triage_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.versionNumber,
    ),
    uniqueIndex('uq_canonical_emergency_triage_replacement').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.supersedesTriageAssessmentPublicId,
    ),
    index('idx_canonical_emergency_triage_case_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.versionNumber,
      table.observedAtUtc,
    ),
    index('idx_canonical_emergency_triage_acuity').on(
      table.tenantId,
      table.acuityCode,
      table.observedAtUtc,
      table.emergencyCasePublicId,
    ),
    check('canonical_emergency_triage_version_check', sql`${table.versionNumber} > 0`),
    check(
      'canonical_emergency_triage_kind_check',
      sql`${table.versionKind} IN ('initial','reassessment','correction','entered_in_error')`,
    ),
    check('canonical_emergency_triage_acuity_check', sql`${table.acuityCode} IN ('red','yellow','green')`),
    check('canonical_emergency_triage_time_check', sql`${table.recordedAtUtc} >= ${table.observedAtUtc}`),
  ],
);

export const canonicalEmergencyCaseClassifications = sqliteTable(
  'canonical_emergency_case_classifications',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    classificationPublicId: text('classification_public_id').notNull(),
    classificationFamilyPublicId: text('classification_family_public_id').notNull(),
    emergencyCasePublicId: text('emergency_case_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    versionNumber: integer('version_number').notNull(),
    supersedesClassificationPublicId: text('supersedes_classification_public_id'),
    versionKind: text('version_kind').notNull(),
    classificationNamespace: text('classification_namespace').notNull(),
    classificationCode: text('classification_code').notNull(),
    categoryCode: text('category_code').notNull(),
    subcategoryCode: text('subcategory_code'),
    animalCategoryCode: text('animal_category_code'),
    biteSiteCode: text('bite_site_code'),
    biteAtUtc: text('bite_at_utc'),
    firstAidCode: text('first_aid_code'),
    policeCaseIndicator: integer('police_case_indicator').notNull().default(0),
    boundedSourceSnapshot: text('bounded_source_snapshot'),
    actorPractitionerPublicId: text('actor_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    occurredAtUtc: text('occurred_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code'),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_emergency_classifications_public_id').on(
      table.tenantId,
      table.classificationPublicId,
    ),
    uniqueIndex('uq_canonical_emergency_classifications_version').on(
      table.tenantId,
      table.classificationFamilyPublicId,
      table.versionNumber,
    ),
    uniqueIndex('uq_canonical_emergency_classifications_replacement').on(
      table.tenantId,
      table.classificationFamilyPublicId,
      table.supersedesClassificationPublicId,
    ),
    index('idx_canonical_emergency_classifications_case').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.classificationNamespace,
      table.classificationCode,
      table.versionNumber,
    ),
    check('canonical_emergency_classifications_version_check', sql`${table.versionNumber} > 0`),
    check(
      'canonical_emergency_classifications_kind_check',
      sql`${table.versionKind} IN ('initial','correction','entered_in_error')`,
    ),
    check('canonical_emergency_classifications_police_check', sql`${table.policeCaseIndicator} IN (0,1)`),
    check(
      'canonical_emergency_classifications_time_check',
      sql`${table.recordedAtUtc} >= ${table.occurredAtUtc}`,
    ),
  ],
);

export const canonicalEmergencyDispositionEvents = sqliteTable(
  'canonical_emergency_disposition_events',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    dispositionEventPublicId: text('disposition_event_public_id').notNull(),
    emergencyCasePublicId: text('emergency_case_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    dispositionVersion: integer('disposition_version').notNull(),
    dispositionCode: text('disposition_code').notNull(),
    actorPractitionerPublicId: text('actor_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    canonicalAdmissionPublicId: text('canonical_admission_public_id'),
    dischargeDocumentPublicId: text('discharge_document_public_id'),
    dischargeDocumentVersionPublicId: text('discharge_document_version_public_id'),
    dischargeDocumentContentSha256: text('discharge_document_content_sha256'),
    receivingOrganizationSourceType: text('receiving_organization_source_type'),
    receivingOrganizationSourcePublicId: text('receiving_organization_source_public_id'),
    receivingEncounterSourceType: text('receiving_encounter_source_type'),
    receivingEncounterSourcePublicId: text('receiving_encounter_source_public_id'),
    transportServiceEventPublicId: text('transport_service_event_public_id'),
    terminalEvidenceCode: text('terminal_evidence_code'),
    occurredAtUtc: text('occurred_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code').notNull(),
    remarksSnapshot: text('remarks_snapshot'),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_emergency_dispositions_public_id').on(
      table.tenantId,
      table.dispositionEventPublicId,
    ),
    uniqueIndex('uq_canonical_emergency_dispositions_scope').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.dispositionEventPublicId,
    ),
    uniqueIndex('uq_canonical_emergency_dispositions_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.dispositionVersion,
    ),
    index('idx_canonical_emergency_dispositions_case_version').on(
      table.tenantId,
      table.emergencyCasePublicId,
      table.dispositionVersion,
      table.occurredAtUtc,
    ),
    check('canonical_emergency_dispositions_version_check', sql`${table.dispositionVersion} > 0`),
    check(
      'canonical_emergency_dispositions_code_check',
      sql`${table.dispositionCode} IN ('admitted','discharged','transferred','lama','dor','death','observation_continuation','entered_in_error')`,
    ),
    check('canonical_emergency_dispositions_time_check', sql`${table.recordedAtUtc} >= ${table.occurredAtUtc}`),
    check(
      'canonical_emergency_dispositions_actor_check',
      sql`${table.actorPractitionerPublicId} IS NOT NULL OR ${table.actorUserPublicId} IS NOT NULL OR ${table.actorSystemKey} IS NOT NULL`,
    ),
  ],
);
