import { sql } from 'drizzle-orm';
import { check, foreignKey, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { canonicalInvoiceLines } from './billing';
import { canonicalServiceEvents } from './service-operations';
import { canonicalServiceCatalogItems } from './services';

const utcNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const canonicalInventoryItems = sqliteTable('canonical_inventory_items', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  itemKind: text('item_kind').notNull(),
  legacyInventoryItemId: integer('legacy_inventory_item_id'),
  legacyPharmacyItemId: integer('legacy_pharmacy_item_id'),
  legacyMedicineId: integer('legacy_medicine_id'),
  servicePublicId: text('service_public_id'),
  displayName: text('display_name').notNull(),
  baseUnitCode: text('base_unit_code').notNull(),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_items_public').on(table.tenantId, table.itemPublicId),
  uniqueIndex('uq_canonical_inventory_items_legacy_inventory').on(table.tenantId, table.legacyInventoryItemId).where(sql`${table.legacyInventoryItemId} IS NOT NULL`),
  uniqueIndex('uq_canonical_inventory_items_legacy_pharmacy').on(table.tenantId, table.legacyPharmacyItemId).where(sql`${table.legacyPharmacyItemId} IS NOT NULL`),
  uniqueIndex('uq_canonical_inventory_items_legacy_medicine').on(table.tenantId, table.legacyMedicineId).where(sql`${table.legacyMedicineId} IS NOT NULL`),
  index('idx_canonical_inventory_items_service').on(table.tenantId, table.servicePublicId, table.status),
  foreignKey({ name: 'fk_canonical_inventory_items_service', columns: [table.tenantId, table.servicePublicId], foreignColumns: [canonicalServiceCatalogItems.tenantId, canonicalServiceCatalogItems.servicePublicId] }).onDelete('restrict'),
  check('canonical_inventory_items_kind_check', sql`item_kind IN ('general','medicine','reagent','supply','fixed_asset','other')`),
  check('canonical_inventory_items_name_check', sql`length(trim(display_name))>0`),
  check('canonical_inventory_items_unit_check', sql`length(trim(base_unit_code))>0`),
  check('canonical_inventory_items_status_check', sql`status IN ('active','inactive','retired')`),
  check('canonical_inventory_items_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryLocations = sqliteTable('canonical_inventory_locations', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  locationPublicId: text('location_public_id').notNull(),
  locationType: text('location_type').notNull(),
  legacyInventoryStoreId: integer('legacy_inventory_store_id'),
  locationCode: text('location_code'),
  displayName: text('display_name').notNull(),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_locations_public').on(table.tenantId, table.locationPublicId),
  uniqueIndex('uq_canonical_inventory_locations_legacy_store').on(table.tenantId, table.legacyInventoryStoreId).where(sql`${table.legacyInventoryStoreId} IS NOT NULL`),
  uniqueIndex('uq_canonical_inventory_locations_code').on(table.tenantId, table.locationCode).where(sql`${table.locationCode} IS NOT NULL`),
  check('canonical_inventory_locations_type_check', sql`location_type IN ('store','pharmacy','ward','department','dispensary','virtual','other')`),
  check('canonical_inventory_locations_name_check', sql`length(trim(display_name))>0`),
  check('canonical_inventory_locations_status_check', sql`status IN ('active','inactive','retired')`),
  check('canonical_inventory_locations_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryLots = sqliteTable('canonical_inventory_lots', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  lotPublicId: text('lot_public_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  legacyInventoryStockId: integer('legacy_inventory_stock_id'),
  legacyPharmacyStockId: integer('legacy_pharmacy_stock_id'),
  legacyMedicineBatchId: integer('legacy_medicine_batch_id'),
  lotCode: text('lot_code').notNull(),
  manufactureDate: text('manufacture_date'),
  expiryDate: text('expiry_date'),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_lots_public').on(table.tenantId, table.lotPublicId),
  uniqueIndex('uq_canonical_inventory_lots_legacy_inventory').on(table.tenantId, table.legacyInventoryStockId).where(sql`${table.legacyInventoryStockId} IS NOT NULL`),
  uniqueIndex('uq_canonical_inventory_lots_legacy_pharmacy').on(table.tenantId, table.legacyPharmacyStockId).where(sql`${table.legacyPharmacyStockId} IS NOT NULL`),
  uniqueIndex('uq_canonical_inventory_lots_legacy_medicine').on(table.tenantId, table.legacyMedicineBatchId).where(sql`${table.legacyMedicineBatchId} IS NOT NULL`),
  index('idx_canonical_inventory_lots_item_expiry').on(table.tenantId, table.itemPublicId, table.status, table.expiryDate, table.lotPublicId),
  foreignKey({ name: 'fk_canonical_inventory_lots_item', columns: [table.tenantId, table.itemPublicId], foreignColumns: [canonicalInventoryItems.tenantId, canonicalInventoryItems.itemPublicId] }).onDelete('restrict'),
  check('canonical_inventory_lots_code_check', sql`length(trim(lot_code))>0`),
  check('canonical_inventory_lots_manufacture_check', sql`manufacture_date IS NULL OR manufacture_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_inventory_lots_expiry_check', sql`expiry_date IS NULL OR expiry_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_inventory_lots_interval_check', sql`expiry_date IS NULL OR manufacture_date IS NULL OR expiry_date>=manufacture_date`),
  check('canonical_inventory_lots_status_check', sql`status IN ('active','blocked','expired','retired')`),
  check('canonical_inventory_lots_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryUnitConversions = sqliteTable('canonical_inventory_unit_conversions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  conversionPublicId: text('conversion_public_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  sourceUnitCode: text('source_unit_code').notNull(),
  baseUnitCode: text('base_unit_code').notNull(),
  numerator: integer('numerator').notNull(),
  denominator: integer('denominator').notNull(),
  status: text('status').notNull().default('active'),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_unit_conversions_public').on(table.tenantId, table.conversionPublicId),
  uniqueIndex('uq_canonical_inventory_unit_conversions_scope').on(table.tenantId, table.itemPublicId, table.sourceUnitCode, table.status),
  index('idx_canonical_inventory_unit_conversions_lookup').on(table.tenantId, table.itemPublicId, table.sourceUnitCode, table.status),
  foreignKey({ name: 'fk_canonical_inventory_unit_conversions_item', columns: [table.tenantId, table.itemPublicId], foreignColumns: [canonicalInventoryItems.tenantId, canonicalInventoryItems.itemPublicId] }).onDelete('restrict'),
  check('canonical_inventory_unit_conversions_source_check', sql`length(trim(source_unit_code))>0`),
  check('canonical_inventory_unit_conversions_base_check', sql`length(trim(base_unit_code))>0`),
  check('canonical_inventory_unit_conversions_numerator_check', sql`numerator BETWEEN 1 AND 9007199254740991`),
  check('canonical_inventory_unit_conversions_denominator_check', sql`denominator BETWEEN 1 AND 9007199254740991`),
  check('canonical_inventory_unit_conversions_status_check', sql`status IN ('active','inactive','retired')`),
  check('canonical_inventory_unit_conversions_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryStockPolicies = sqliteTable('canonical_inventory_stock_policies', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  locationPublicId: text('location_public_id').notNull(),
  allowNegativeStock: integer('allow_negative_stock').notNull().default(0),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_stock_policies_scope').on(table.tenantId, table.itemPublicId, table.locationPublicId),
  foreignKey({ name: 'fk_canonical_inventory_stock_policies_item', columns: [table.tenantId, table.itemPublicId], foreignColumns: [canonicalInventoryItems.tenantId, canonicalInventoryItems.itemPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_stock_policies_location', columns: [table.tenantId, table.locationPublicId], foreignColumns: [canonicalInventoryLocations.tenantId, canonicalInventoryLocations.locationPublicId] }).onDelete('restrict'),
  check('canonical_inventory_stock_policies_negative_check', sql`allow_negative_stock IN (0,1)`),
  check('canonical_inventory_stock_policies_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryBalances = sqliteTable('canonical_inventory_balances', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  locationPublicId: text('location_public_id').notNull(),
  lotPublicId: text('lot_public_id').notNull(),
  quantityBase: integer('quantity_base').notNull().default(0),
  version: integer('version').notNull().default(0),
  projectionGuard: integer('projection_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_balances_scope').on(table.tenantId, table.itemPublicId, table.locationPublicId, table.lotPublicId),
  index('idx_canonical_inventory_balances_location').on(table.tenantId, table.locationPublicId, table.itemPublicId, table.lotPublicId),
  foreignKey({ name: 'fk_canonical_inventory_balances_item', columns: [table.tenantId, table.itemPublicId], foreignColumns: [canonicalInventoryItems.tenantId, canonicalInventoryItems.itemPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_balances_location', columns: [table.tenantId, table.locationPublicId], foreignColumns: [canonicalInventoryLocations.tenantId, canonicalInventoryLocations.locationPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_balances_lot', columns: [table.tenantId, table.lotPublicId], foreignColumns: [canonicalInventoryLots.tenantId, canonicalInventoryLots.lotPublicId] }).onDelete('restrict'),
  check('canonical_inventory_balances_quantity_check', sql`quantity_base BETWEEN -9007199254740991 AND 9007199254740991`),
  check('canonical_inventory_balances_version_check', sql`version>=0`),
  check('canonical_inventory_balances_projection_guard', sql`projection_guard=1`),
  check('canonical_inventory_balances_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryTransfers = sqliteTable('canonical_inventory_transfers', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  transferPublicId: text('transfer_public_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  lotPublicId: text('lot_public_id').notNull(),
  fromLocationPublicId: text('from_location_public_id').notNull(),
  toLocationPublicId: text('to_location_public_id').notNull(),
  quantityBase: integer('quantity_base').notNull(),
  status: text('status').notNull().default('posted'),
  occurredAtUtc: text('occurred_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_transfers_public').on(table.tenantId, table.transferPublicId),
  foreignKey({ name: 'fk_canonical_inventory_transfers_item', columns: [table.tenantId, table.itemPublicId], foreignColumns: [canonicalInventoryItems.tenantId, canonicalInventoryItems.itemPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_transfers_lot', columns: [table.tenantId, table.lotPublicId], foreignColumns: [canonicalInventoryLots.tenantId, canonicalInventoryLots.lotPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_transfers_from', columns: [table.tenantId, table.fromLocationPublicId], foreignColumns: [canonicalInventoryLocations.tenantId, canonicalInventoryLocations.locationPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_transfers_to', columns: [table.tenantId, table.toLocationPublicId], foreignColumns: [canonicalInventoryLocations.tenantId, canonicalInventoryLocations.locationPublicId] }).onDelete('restrict'),
  check('canonical_inventory_transfers_location_check', sql`from_location_public_id<>to_location_public_id`),
  check('canonical_inventory_transfers_quantity_check', sql`quantity_base BETWEEN 1 AND 9007199254740991`),
  check('canonical_inventory_transfers_status_check', sql`status IN ('posted','reversed')`),
  check('canonical_inventory_transfers_occurred_check', sql`substr(occurred_at_utc,-1)='Z'`),
  check('canonical_inventory_transfers_business_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_inventory_transfers_evidence_check', sql`length(source_evidence_sha256)=64`),
]);

export const canonicalInventoryMovements = sqliteTable('canonical_inventory_movements', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  tenantId: text('tenant_id').notNull(),
  movementPublicId: text('movement_public_id').notNull(),
  itemPublicId: text('item_public_id').notNull(),
  locationPublicId: text('location_public_id').notNull(),
  lotPublicId: text('lot_public_id').notNull(),
  movementType: text('movement_type').notNull(),
  direction: text('direction').notNull(),
  sourceQuantity: integer('source_quantity').notNull(),
  sourceUnitCode: text('source_unit_code').notNull(),
  conversionNumerator: integer('conversion_numerator').notNull(),
  conversionDenominator: integer('conversion_denominator').notNull(),
  quantityBase: integer('quantity_base').notNull(),
  signedQuantityBase: integer('signed_quantity_base').notNull(),
  balanceBeforeBase: integer('balance_before_base').notNull(),
  balanceAfterBase: integer('balance_after_base').notNull(),
  transferPublicId: text('transfer_public_id'),
  serviceEventPublicId: text('service_event_public_id'),
  invoicePublicId: text('invoice_public_id'),
  invoiceLinePublicId: text('invoice_line_public_id'),
  reversalOfMovementPublicId: text('reversal_of_movement_public_id'),
  sourceType: text('source_type').notNull(),
  sourcePublicId: text('source_public_id').notNull(),
  sourceLinePublicId: text('source_line_public_id').notNull(),
  sourceTable: text('source_table').notNull(),
  status: text('status').notNull().default('posted'),
  occurredAtUtc: text('occurred_at_utc').notNull(),
  businessDate: text('business_date').notNull(),
  actorUserId: integer('actor_user_id'),
  balanceGuard: integer('balance_guard').notNull().default(1),
  sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
  createdAtUtc: text('created_at_utc').notNull().default(utcNow),
}, (table) => [
  uniqueIndex('uq_canonical_inventory_movements_public').on(table.tenantId, table.movementPublicId),
  uniqueIndex('uq_canonical_inventory_movements_source').on(table.tenantId, table.sourceType, table.sourcePublicId, table.sourceLinePublicId, table.movementType),
  uniqueIndex('uq_canonical_inventory_movements_transfer_leg').on(table.tenantId, table.transferPublicId, table.movementType).where(sql`${table.transferPublicId} IS NOT NULL`),
  uniqueIndex('uq_canonical_inventory_movements_service_stockout').on(table.tenantId, table.serviceEventPublicId).where(sql`${table.serviceEventPublicId} IS NOT NULL AND ${table.movementType} IN ('dispense','sale')`),
  uniqueIndex('uq_canonical_inventory_movements_invoice_stockout').on(table.tenantId, table.invoicePublicId, table.invoiceLinePublicId).where(sql`${table.invoiceLinePublicId} IS NOT NULL AND ${table.movementType}='sale'`),
  index('idx_canonical_inventory_movements_balance').on(table.tenantId, table.itemPublicId, table.locationPublicId, table.lotPublicId, table.occurredAtUtc, table.id),
  index('idx_canonical_inventory_movements_source').on(table.tenantId, table.sourceType, table.sourcePublicId, table.sourceLinePublicId),
  foreignKey({ name: 'fk_canonical_inventory_movements_item', columns: [table.tenantId, table.itemPublicId], foreignColumns: [canonicalInventoryItems.tenantId, canonicalInventoryItems.itemPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_movements_location', columns: [table.tenantId, table.locationPublicId], foreignColumns: [canonicalInventoryLocations.tenantId, canonicalInventoryLocations.locationPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_movements_lot', columns: [table.tenantId, table.lotPublicId], foreignColumns: [canonicalInventoryLots.tenantId, canonicalInventoryLots.lotPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_movements_transfer', columns: [table.tenantId, table.transferPublicId], foreignColumns: [canonicalInventoryTransfers.tenantId, canonicalInventoryTransfers.transferPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_movements_service_event', columns: [table.tenantId, table.serviceEventPublicId], foreignColumns: [canonicalServiceEvents.tenantId, canonicalServiceEvents.eventPublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_movements_invoice_line', columns: [table.tenantId, table.invoicePublicId, table.invoiceLinePublicId], foreignColumns: [canonicalInvoiceLines.tenantId, canonicalInvoiceLines.invoicePublicId, canonicalInvoiceLines.linePublicId] }).onDelete('restrict'),
  foreignKey({ name: 'fk_canonical_inventory_movements_reversal', columns: [table.tenantId, table.reversalOfMovementPublicId], foreignColumns: [table.tenantId, table.movementPublicId] }).onDelete('restrict'),
  check('canonical_inventory_movements_type_check', sql`movement_type IN ('migration_opening','purchase_receipt','transfer_out','transfer_in','issue','dispense','sale','patient_return','supplier_return','waste','expiry','adjustment_in','adjustment_out','reversal_in','reversal_out')`),
  check('canonical_inventory_movements_direction_check', sql`direction IN ('in','out')`),
  check('canonical_inventory_movements_source_quantity_check', sql`source_quantity BETWEEN 1 AND 9007199254740991`),
  check('canonical_inventory_movements_conversion_check', sql`conversion_numerator BETWEEN 1 AND 9007199254740991 AND conversion_denominator BETWEEN 1 AND 9007199254740991 AND source_quantity<=9007199254740991/conversion_numerator AND (source_quantity*conversion_numerator)%conversion_denominator=0 AND quantity_base=(source_quantity*conversion_numerator)/conversion_denominator`),
  check('canonical_inventory_movements_quantity_check', sql`quantity_base BETWEEN 1 AND 9007199254740991`),
  check('canonical_inventory_movements_signed_check', sql`signed_quantity_base=CASE WHEN direction='in' THEN quantity_base ELSE -quantity_base END`),
  check('canonical_inventory_movements_balance_math_check', sql`balance_after_base=balance_before_base+signed_quantity_base`),
  check('canonical_inventory_movements_type_direction_check', sql`(movement_type IN ('migration_opening','purchase_receipt','transfer_in','patient_return','adjustment_in','reversal_in') AND direction='in') OR (movement_type IN ('transfer_out','issue','dispense','sale','supplier_return','waste','expiry','adjustment_out','reversal_out') AND direction='out')`),
  check('canonical_inventory_movements_transfer_check', sql`(movement_type IN ('transfer_out','transfer_in') AND transfer_public_id IS NOT NULL) OR (movement_type NOT IN ('transfer_out','transfer_in') AND transfer_public_id IS NULL)`),
  check('canonical_inventory_movements_link_check', sql`(movement_type='dispense' AND invoice_public_id IS NULL AND invoice_line_public_id IS NULL) OR (movement_type='sale' AND ((service_event_public_id IS NULL AND invoice_public_id IS NULL AND invoice_line_public_id IS NULL) OR (service_event_public_id IS NOT NULL AND invoice_public_id IS NOT NULL AND invoice_line_public_id IS NOT NULL))) OR (movement_type NOT IN ('dispense','sale') AND service_event_public_id IS NULL AND invoice_public_id IS NULL AND invoice_line_public_id IS NULL)`),
  check('canonical_inventory_movements_invoice_shape_check', sql`(invoice_public_id IS NULL)=(invoice_line_public_id IS NULL)`),
  check('canonical_inventory_movements_status_check', sql`status IN ('posted','reversed')`),
  check('canonical_inventory_movements_occurred_check', sql`substr(occurred_at_utc,-1)='Z'`),
  check('canonical_inventory_movements_business_date_check', sql`business_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'`),
  check('canonical_inventory_movements_balance_guard', sql`balance_guard=1`),
  check('canonical_inventory_movements_evidence_check', sql`length(source_evidence_sha256)=64`),
]);
