import { sql } from 'drizzle-orm';
import { check, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

const utcNow = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

export const canonicalImagingAcquisitions = sqliteTable(
  'canonical_imaging_acquisitions',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    acquisitionPublicId: text('acquisition_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    requestPublicId: text('request_public_id').notNull(),
    eventPublicId: text('event_public_id'),
    servicePublicId: text('service_public_id').notNull(),
    accessionNamespace: text('accession_namespace').notNull(),
    accessionValue: text('accession_value').notNull(),
    modalityCode: text('modality_code').notNull(),
    bodySiteCode: text('body_site_code'),
    procedureSnapshot: text('procedure_snapshot'),
    currentStatus: text('current_status').notNull().default('scheduled'),
    statusVersion: integer('status_version').notNull().default(1),
    currentStatusEventPublicId: text('current_status_event_public_id'),
    scheduledAtUtc: text('scheduled_at_utc'),
    startedAtUtc: text('started_at_utc'),
    completedAtUtc: text('completed_at_utc'),
    cancelledAtUtc: text('cancelled_at_utc'),
    enteredInErrorAtUtc: text('entered_in_error_at_utc'),
    performingPractitionerPublicId: text('performing_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    idempotencyKey: text('idempotency_key').notNull(),
    requestFingerprintSha256: text('request_fingerprint_sha256').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
    updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_acquisitions_public_id').on(table.tenantId, table.acquisitionPublicId),
    uniqueIndex('uq_canonical_imaging_acquisitions_scope').on(
      table.tenantId, table.acquisitionPublicId, table.patientLinkPublicId,
      table.encounterPublicId, table.requestPublicId, table.servicePublicId,
    ),
    uniqueIndex('uq_canonical_imaging_acquisitions_accession').on(
      table.tenantId, table.accessionNamespace, table.accessionValue,
    ),
    uniqueIndex('uq_canonical_imaging_acquisitions_idempotency').on(table.tenantId, table.idempotencyKey),
    index('idx_canonical_imaging_acquisitions_patient_status').on(
      table.tenantId, table.patientLinkPublicId, table.currentStatus, table.acquisitionPublicId,
    ),
    check('canonical_imaging_acquisitions_status_check', sql`${table.currentStatus} IN ('scheduled','ready','in_progress','completed','cancelled','entered_in_error')`),
    check('canonical_imaging_acquisitions_version_check', sql`${table.statusVersion} > 0`),
  ],
);

export const canonicalImagingAcquisitionStatusEvents = sqliteTable(
  'canonical_imaging_acquisition_status_events',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    eventPublicId: text('event_public_id').notNull(),
    acquisitionPublicId: text('acquisition_public_id').notNull(),
    fromStatus: text('from_status'),
    toStatus: text('to_status').notNull(),
    eventVersion: integer('event_version').notNull(),
    eventType: text('event_type').notNull(),
    actorPractitionerPublicId: text('actor_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    modalitySourceType: text('modality_source_type'),
    modalitySourcePublicId: text('modality_source_public_id'),
    pacsEndpointSourceType: text('pacs_endpoint_source_type'),
    pacsEndpointSourcePublicId: text('pacs_endpoint_source_public_id'),
    occurredAtUtc: text('occurred_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_acquisition_event_public_id').on(table.tenantId, table.eventPublicId),
    uniqueIndex('uq_canonical_imaging_acquisition_event_scope').on(table.tenantId, table.acquisitionPublicId, table.eventPublicId),
    uniqueIndex('uq_canonical_imaging_acquisition_event_version').on(table.tenantId, table.acquisitionPublicId, table.eventVersion),
    index('idx_canonical_imaging_acquisition_events_timeline').on(
      table.tenantId, table.acquisitionPublicId, table.eventVersion, table.occurredAtUtc,
    ),
    check('canonical_imaging_acquisition_event_version_check', sql`${table.eventVersion} > 0`),
  ],
);

export const canonicalImagingStudies = sqliteTable(
  'canonical_imaging_studies',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    studyPublicId: text('study_public_id').notNull(),
    acquisitionPublicId: text('acquisition_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    requestPublicId: text('request_public_id').notNull(),
    servicePublicId: text('service_public_id').notNull(),
    studyUidNamespace: text('study_uid_namespace').notNull(),
    studyInstanceUid: text('study_instance_uid').notNull(),
    accessionNamespace: text('accession_namespace').notNull(),
    accessionValue: text('accession_value').notNull(),
    modalityCode: text('modality_code').notNull(),
    studyStartedAtUtc: text('study_started_at_utc').notNull(),
    currentStatus: text('current_status').notNull().default('active'),
    statusVersion: integer('status_version').notNull().default(1),
    currentProvenanceEventPublicId: text('current_provenance_event_public_id'),
    seriesCount: integer('series_count').notNull().default(0),
    instanceCount: integer('instance_count').notNull().default(0),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    idempotencyKey: text('idempotency_key').notNull(),
    requestFingerprintSha256: text('request_fingerprint_sha256').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
    updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_studies_public_id').on(table.tenantId, table.studyPublicId),
    uniqueIndex('uq_canonical_imaging_studies_scope').on(
      table.tenantId, table.studyPublicId, table.acquisitionPublicId, table.patientLinkPublicId,
      table.encounterPublicId, table.requestPublicId, table.servicePublicId,
    ),
    uniqueIndex('uq_canonical_imaging_studies_uid').on(table.tenantId, table.studyUidNamespace, table.studyInstanceUid),
    uniqueIndex('uq_canonical_imaging_studies_idempotency').on(table.tenantId, table.idempotencyKey),
    index('idx_canonical_imaging_studies_acquisition').on(
      table.tenantId, table.acquisitionPublicId, table.currentStatus, table.studyPublicId,
    ),
    check('canonical_imaging_studies_version_check', sql`${table.statusVersion} > 0`),
  ],
);

export const canonicalImagingSeries = sqliteTable(
  'canonical_imaging_series',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    seriesPublicId: text('series_public_id').notNull(),
    studyPublicId: text('study_public_id').notNull(),
    seriesUidNamespace: text('series_uid_namespace').notNull(),
    seriesInstanceUid: text('series_instance_uid').notNull(),
    seriesNumber: integer('series_number'),
    modalityCode: text('modality_code').notNull(),
    bodyPartCode: text('body_part_code'),
    protocolName: text('protocol_name'),
    lateralityCode: text('laterality_code'),
    descriptionSnapshot: text('description_snapshot'),
    currentStatus: text('current_status').notNull().default('active'),
    instanceCount: integer('instance_count').notNull().default(0),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
    updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_series_public_id').on(table.tenantId, table.seriesPublicId),
    uniqueIndex('uq_canonical_imaging_series_scope').on(table.tenantId, table.studyPublicId, table.seriesPublicId),
    uniqueIndex('uq_canonical_imaging_series_uid').on(table.tenantId, table.seriesUidNamespace, table.seriesInstanceUid),
    index('idx_canonical_imaging_series_study').on(table.tenantId, table.studyPublicId, table.currentStatus, table.seriesPublicId),
  ],
);

export const canonicalImagingInstances = sqliteTable(
  'canonical_imaging_instances',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    instancePublicId: text('instance_public_id').notNull(),
    studyPublicId: text('study_public_id').notNull(),
    seriesPublicId: text('series_public_id').notNull(),
    sopUidNamespace: text('sop_uid_namespace').notNull(),
    sopInstanceUid: text('sop_instance_uid').notNull(),
    sopClassUid: text('sop_class_uid').notNull(),
    instanceNumber: integer('instance_number'),
    frameCount: integer('frame_count').notNull().default(1),
    transferSyntaxUid: text('transfer_syntax_uid'),
    objectContentSha256: text('object_content_sha256').notNull(),
    byteSize: integer('byte_size').notNull(),
    storageProviderType: text('storage_provider_type').notNull(),
    storageProviderPublicId: text('storage_provider_public_id').notNull(),
    storageObjectKey: text('storage_object_key').notNull(),
    storageGeneration: text('storage_generation').notNull(),
    currentDisposition: text('current_disposition').notNull().default('accepted'),
    replacesInstancePublicId: text('replaces_instance_public_id'),
    reasonCode: text('reason_code'),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_instances_public_id').on(table.tenantId, table.instancePublicId),
    uniqueIndex('uq_canonical_imaging_instances_scope').on(
      table.tenantId, table.studyPublicId, table.seriesPublicId, table.instancePublicId,
    ),
    uniqueIndex('uq_canonical_imaging_instances_sop_uid').on(table.tenantId, table.sopUidNamespace, table.sopInstanceUid),
    index('idx_canonical_imaging_instances_series').on(
      table.tenantId, table.studyPublicId, table.seriesPublicId, table.instanceNumber, table.instancePublicId,
    ),
    check('canonical_imaging_instances_frame_check', sql`${table.frameCount} > 0 AND ${table.byteSize} >= 0`),
  ],
);

export const canonicalImagingProvenanceEvents = sqliteTable(
  'canonical_imaging_provenance_events',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    provenanceEventPublicId: text('provenance_event_public_id').notNull(),
    acquisitionPublicId: text('acquisition_public_id'),
    studyPublicId: text('study_public_id'),
    seriesPublicId: text('series_public_id'),
    instancePublicId: text('instance_public_id'),
    eventType: text('event_type').notNull(),
    disposition: text('disposition').notNull(),
    eventVersion: integer('event_version').notNull(),
    modalitySourceType: text('modality_source_type'),
    modalitySourcePublicId: text('modality_source_public_id'),
    sourceAeTitle: text('source_ae_title'),
    calledAeTitle: text('called_ae_title'),
    pacsEndpointSourceType: text('pacs_endpoint_source_type'),
    pacsEndpointSourcePublicId: text('pacs_endpoint_source_public_id'),
    bridgeSourceType: text('bridge_source_type'),
    bridgeSourcePublicId: text('bridge_source_public_id'),
    messageSourceType: text('message_source_type'),
    messageSourcePublicId: text('message_source_public_id'),
    protocol: text('protocol'),
    transferSyntaxUid: text('transfer_syntax_uid'),
    objectContentSha256: text('object_content_sha256'),
    storageProviderType: text('storage_provider_type'),
    storageProviderPublicId: text('storage_provider_public_id'),
    storageObjectKey: text('storage_object_key'),
    storageGeneration: text('storage_generation'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    occurredAtUtc: text('occurred_at_utc').notNull(),
    recordedAtUtc: text('recorded_at_utc').notNull(),
    reasonCode: text('reason_code').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_provenance_public_id').on(table.tenantId, table.provenanceEventPublicId),
    uniqueIndex('uq_canonical_imaging_provenance_study_scope').on(table.tenantId, table.studyPublicId, table.provenanceEventPublicId),
    uniqueIndex('uq_canonical_imaging_provenance_instance_hash').on(
      table.tenantId, table.instancePublicId, table.objectContentSha256, table.disposition,
    ),
    index('idx_canonical_imaging_provenance_scope').on(
      table.tenantId, table.acquisitionPublicId, table.studyPublicId,
      table.seriesPublicId, table.instancePublicId, table.eventVersion,
    ),
    check('canonical_imaging_provenance_version_check', sql`${table.eventVersion} > 0`),
  ],
);

export const canonicalImagingReportSets = sqliteTable(
  'canonical_imaging_report_sets',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    reportSetPublicId: text('report_set_public_id').notNull(),
    patientLinkPublicId: text('patient_link_public_id').notNull(),
    encounterPublicId: text('encounter_public_id').notNull(),
    requestPublicId: text('request_public_id').notNull(),
    servicePublicId: text('service_public_id').notNull(),
    acquisitionPublicId: text('acquisition_public_id').notNull(),
    studyPublicId: text('study_public_id').notNull(),
    currentVersionPublicId: text('current_version_public_id'),
    currentStatus: text('current_status').notNull().default('draft'),
    statusVersion: integer('status_version').notNull().default(1),
    currentStatusEventPublicId: text('current_status_event_public_id'),
    reportingPractitionerPublicId: text('reporting_practitioner_public_id').notNull(),
    reportNumberNamespace: text('report_number_namespace').notNull(),
    reportNumberValue: text('report_number_value').notNull(),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    idempotencyKey: text('idempotency_key').notNull(),
    requestFingerprintSha256: text('request_fingerprint_sha256').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
    updatedAtUtc: text('updated_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_report_sets_public_id').on(table.tenantId, table.reportSetPublicId),
    uniqueIndex('uq_canonical_imaging_report_sets_scope').on(
      table.tenantId, table.reportSetPublicId, table.patientLinkPublicId, table.encounterPublicId,
      table.requestPublicId, table.servicePublicId, table.acquisitionPublicId, table.studyPublicId,
    ),
    uniqueIndex('uq_canonical_imaging_report_sets_number').on(
      table.tenantId, table.reportNumberNamespace, table.reportNumberValue,
    ),
    uniqueIndex('uq_canonical_imaging_report_sets_idempotency').on(table.tenantId, table.idempotencyKey),
    index('idx_canonical_imaging_report_sets_patient_status').on(
      table.tenantId, table.patientLinkPublicId, table.currentStatus, table.reportSetPublicId,
    ),
    check('canonical_imaging_report_sets_version_check', sql`${table.statusVersion} > 0`),
  ],
);

export const canonicalImagingReportVersions = sqliteTable(
  'canonical_imaging_report_versions',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    versionPublicId: text('version_public_id').notNull(),
    reportSetPublicId: text('report_set_public_id').notNull(),
    versionNumber: integer('version_number').notNull(),
    supersedesVersionPublicId: text('supersedes_version_public_id'),
    versionKind: text('version_kind').notNull(),
    versionStatus: text('version_status').notNull().default('draft'),
    contentJson: text('content_json').notNull(),
    contentSha256: text('content_sha256').notNull(),
    signedContentSha256: text('signed_content_sha256'),
    authoringPractitionerPublicId: text('authoring_practitioner_public_id').notNull(),
    verifyingPractitionerPublicId: text('verifying_practitioner_public_id'),
    finalisingPractitionerPublicId: text('finalising_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    authoredAtUtc: text('authored_at_utc').notNull(),
    verifiedAtUtc: text('verified_at_utc'),
    finalisedAtUtc: text('finalised_at_utc'),
    publishedAtUtc: text('published_at_utc'),
    retractedAtUtc: text('retracted_at_utc'),
    reasonCode: text('reason_code'),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_report_versions_public_id').on(table.tenantId, table.versionPublicId),
    uniqueIndex('uq_canonical_imaging_report_versions_scope').on(table.tenantId, table.reportSetPublicId, table.versionPublicId),
    uniqueIndex('uq_canonical_imaging_report_versions_number').on(table.tenantId, table.reportSetPublicId, table.versionNumber),
    uniqueIndex('uq_canonical_imaging_report_versions_supersedes').on(
      table.tenantId, table.reportSetPublicId, table.supersedesVersionPublicId,
    ),
    index('idx_canonical_imaging_report_versions_timeline').on(
      table.tenantId, table.reportSetPublicId, table.versionNumber, table.versionPublicId,
    ),
    check('canonical_imaging_report_versions_number_check', sql`${table.versionNumber} > 0`),
  ],
);

export const canonicalImagingReportStatusEvents = sqliteTable(
  'canonical_imaging_report_status_events',
  {
    id: integer('id').primaryKey({ autoIncrement: true }),
    tenantId: text('tenant_id').notNull(),
    eventPublicId: text('event_public_id').notNull(),
    reportSetPublicId: text('report_set_public_id').notNull(),
    versionPublicId: text('version_public_id').notNull(),
    fromStatus: text('from_status'),
    toStatus: text('to_status').notNull(),
    eventVersion: integer('event_version').notNull(),
    eventType: text('event_type').notNull(),
    actorPractitionerPublicId: text('actor_practitioner_public_id'),
    actorUserPublicId: text('actor_user_public_id'),
    actorSystemKey: text('actor_system_key'),
    signedContentSha256: text('signed_content_sha256'),
    reasonCode: text('reason_code').notNull(),
    occurredAtUtc: text('occurred_at_utc').notNull(),
    sourceEvidenceSha256: text('source_evidence_sha256').notNull(),
    createdAtUtc: text('created_at_utc').notNull().default(utcNow),
  },
  (table) => [
    uniqueIndex('uq_canonical_imaging_report_event_public_id').on(table.tenantId, table.eventPublicId),
    uniqueIndex('uq_canonical_imaging_report_event_scope').on(table.tenantId, table.reportSetPublicId, table.eventPublicId),
    uniqueIndex('uq_canonical_imaging_report_event_version').on(table.tenantId, table.reportSetPublicId, table.eventVersion),
    index('idx_canonical_imaging_report_events_timeline').on(
      table.tenantId, table.reportSetPublicId, table.eventVersion, table.occurredAtUtc,
    ),
    check('canonical_imaging_report_event_version_check', sql`${table.eventVersion} > 0`),
  ],
);
