export const IPD_BN_COPY: Record<string, string> = {
  'adminDashboard.ipdBilling.eyebrow': 'ইনডোর রোগীর আর্থিক হিসাব',
  'adminDashboard.ipdBilling.title': 'নির্বাচিত সময়ের IPD আর্থিক সারসংক্ষেপ',
  'adminDashboard.ipdBilling.subtitle': 'চার্জ, চূড়ান্ত বিল, বিল পেমেন্ট, নতুন ডিপোজিট এবং ডিপোজিট সমন্বয় আলাদাভাবে দেখানো হয়েছে।',
  'adminDashboard.ipdBilling.open': 'IPD বিলিং খুলুন',
  'adminDashboard.ipdBilling.openAria': 'IPD বিলিং ওয়ার্কস্পেস খুলুন',
  'adminDashboard.ipdBilling.loadFailed': 'IPD আর্থিক সারসংক্ষেপ লোড করা যায়নি।',
  'adminDashboard.ipdBilling.chargesAddedToday': 'নির্বাচিত সময়ে নতুন চার্জ যোগ হয়েছে',
  'adminDashboard.ipdBilling.chargesAddedDetail': 'নির্বাচিত সময়ে ভর্তি রোগীর হিসাবে যোগ হওয়া প্রভিশনাল চার্জ; এটি নগদ আদায় নয়।',
  'adminDashboard.ipdBilling.finalBillsToday': 'নির্বাচিত সময়ের চূড়ান্ত IPD বিল',
  'adminDashboard.ipdBilling.finalBillsDetail': 'ডিসকাউন্টের পর চূড়ান্ত করা ভর্তি রোগীর বিল।',
  'adminDashboard.ipdBilling.collectionReceivedToday': 'নির্বাচিত সময়ে IPD মোট টাকা গ্রহণ',
  'adminDashboard.ipdBilling.collectionReceivedDetail': 'নির্বাচিত সময়ের বিল পেমেন্ট ও নতুন ডিপোজিট মিলিয়ে মোট টাকা গ্রহণ।',
  'adminDashboard.ipdBilling.currentProvisionalDue': 'নির্বাচিত সময়ের শেষ দিনের প্রভিশনাল বকেয়া',
  'adminDashboard.ipdBilling.currentProvisionalDueDetail': 'নির্বাচিত সময়ের শেষ দিনে ভর্তি রোগীর সক্রিয় চার্জ থেকে অবশিষ্ট ডিপোজিট বাদ দেওয়ার পরের অঙ্ক।',
  'adminDashboard.ipdBilling.reconciliationTitle': 'নির্বাচিত সময়ের IPD সেটেলমেন্ট মিল',
  'adminDashboard.ipdBilling.reconciliationHelp': 'গ্রস বিল থেকে ডিসকাউন্ট বাদ দিলে নেট বিল; পেমেন্ট ও ডিপোজিট যোগ করলে সেটেল হওয়া টাকা।',
  'adminDashboard.ipdBilling.settledBills': 'নির্বাচিত সময়ে সেটেল হওয়া IPD বিল',
  'adminDashboard.ipdBilling.grossBill': 'গ্রস বিল',
  'adminDashboard.ipdBilling.discount': 'ডিসকাউন্ট',
  'adminDashboard.ipdBilling.netBill': 'নেট বিল',
  'adminDashboard.ipdBilling.paymentReceived': 'পেমেন্ট সমন্বয়',
  'adminDashboard.ipdBilling.depositApplied': 'ডিপোজিট সমন্বয়',
  'adminDashboard.ipdBilling.settledAmount': 'সেটেল হওয়া টাকা',
  'adminDashboard.ipdBilling.currentlyAdmitted': 'নির্বাচিত সময়ের শেষ দিনে ভর্তি',
  'adminDashboard.ipdBilling.admissionsToday': 'নির্বাচিত সময়ে ভর্তি',
  'adminDashboard.ipdBilling.dischargesToday': 'নির্বাচিত সময়ে ডিসচার্জ',
  'adminDashboard.ipdBilling.pendingBilling': 'বিলিং অপেক্ষমাণ',
  'adminDashboard.ipdBilling.highDuePatients': 'বেশি বকেয়ার রোগী',
  'adminDashboard.ipdBilling.packagePatients': 'প্যাকেজ রোগী',
  'adminDashboard.ipdBilling.activityTitle': 'নির্বাচিত সময়ের IPD আর্থিক কার্যক্রম',
  'adminDashboard.ipdBilling.activityHelp': 'নির্বাচিত সময়ের ইনভয়েস, বিল পেমেন্ট, নতুন ডিপোজিট এবং ডিপোজিট সমন্বয়—ইনভয়েস তৈরি না হলেও—আলাদা সারিতে দেখানো হয়েছে।',
  'adminDashboard.ipdBilling.invoiceAdmission': 'ইনভয়েস / ভর্তি',
  'adminDashboard.ipdBilling.patient': 'রোগী',
  'adminDashboard.ipdBilling.items': 'আইটেম',
  'adminDashboard.ipdBilling.gross': 'গ্রস',
  'adminDashboard.ipdBilling.net': 'নেট',
  'adminDashboard.ipdBilling.deposit': 'ডিপোজিট সমন্বয়',
  'adminDashboard.ipdBilling.paidToday': 'নির্বাচিত সময়ে টাকা গ্রহণ',
  'adminDashboard.ipdBilling.totalReceivedLine': 'মোট গ্রহণ',
  'adminDashboard.ipdBilling.billPaymentLine': 'বিল পেমেন্ট',
  'adminDashboard.ipdBilling.newDepositLine': 'নতুন ডিপোজিট',
  'adminDashboard.ipdBilling.depositReceivedActivity': 'ডিপোজিট গ্রহণ',
  'adminDashboard.ipdBilling.invoicePending': 'ইনভয়েস এখনো তৈরি হয়নি',
  'adminDashboard.ipdBilling.due': 'বকেয়া',
  'adminDashboard.ipdBilling.status': 'অবস্থা',
  'adminDashboard.ipdBilling.noActivity': 'নির্বাচিত সময়ে কোনো IPD আর্থিক কার্যক্রম পাওয়া যায়নি।',
};
